/**
 * generated by Xtext 2.16.0
 */
package org.asmeta.avallaxt;

import org.asmeta.avallaxt.AvallaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AvallaStandaloneSetup extends AvallaStandaloneSetupGenerated {
  public static void doSetup() {
    new AvallaStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
