# ============================================================
# RUNTIME MODEL PATHS
# ============================================================
hardware.RUNTIME_MODEL_PATH=resources/models/MVM/MVMHardware.asm
controller.RUNTIME_MODEL_PATH=resources/models/MVM/MVMcontroller04.asm
supervisor.RUNTIME_MODEL_PATH=resources/models/MVM/supervisor03.asm

# ============================================================
# COMPOSITION FORMULA
# ============================================================
setup.setup_comp= hardware <|> (controller <|> supervisor)

# COMMON
common.HOST=127.0.0.1
common.ASM_ENVIRONMENT_FUNCTIONS=adc_reply_m,fan_working_m,pi_6_m,pi_6_reply_m,temperature_m,startupEnded,selfTestPassed,startVentilation,stopRequested,respirationMode,flowDropPSV,cmdExPause,cmdInPause,cmdRm,pawGTMaxPinsp,dropPAW_ITS,mCurrTimeSecs

hardware.CONSOLE_INPUT_FUNCTIONS=iValve,CLOSED,oValve,OPEN,insp_valve,CLOSED,exp_valve,OPEN,state,STARTUP

controller.CONSOLE_INPUT_FUNCTIONS=watchdog_st,INACTIVE,status_selftest,NOTSTART,al_bit,NONE

supervisor.CONSOLE_INPUT_FUNCTIONS=watchdog,false,enter_self,false,exit_self,false,run_command,false,stop_command,false,breath_sync,EXP,all_cont,NONE,snooze,false,iValve,CLOSED,oValve,OPEN,pi_6,25,pi_6_reply,RESPONSE,adc_reply,RESPONSE,fan_working,true,temperature,25


environment.adc_reply_m= RESPONSE,RESPONSE,RESPONSE,RESPONSE,RESPONSE,RESPONSE
environment.fan_working_m= true,true,true,true,true,true
environment.pi_6_m= 25,25,25,25,25,25
environment.pi_6_reply_m= RESPONSE,RESPONSE,RESPONSE,RESPONSE,RESPONSE,RESPONSE
environment.temperature_m= 25,25,25,25,25,25

# --- Timer (Controller + Hardware import TimeLibrary)
environment.mCurrTimeSecs= 1,2,3,4,5,6

# --- GUI / user input \u2014 sticky events (latch true once set) ---
environment.startupEnded=    false,true,true,true,true,true
environment.selfTestPassed=  false,false,true,true,true,true
environment.startVentilation=false,false,false,true,true,true
environment.stopRequested=   false,false,false,false,false,false
environment.env_functions=adc_reply_m,fan_working_m,pi_6_m,pi_6_reply_m,temperature_m,startupEnded,selfTestPassed,startVentilation,stopRequested,respirationMode,flowDropPSV,cmdExPause,cmdInPause,cmdRm,pawGTMaxPinsp,dropPAW_ITS,mCurrTimeSecs
# --- Other Controller monitoreds: never change in this scenario
environment.respirationMode= PCV,PCV,PCV,PCV,PCV,PCV
environment.flowDropPSV=     false,false,false,false,false,false
environment.cmdExPause=      false,false,false,false,false,false
environment.cmdInPause=      false,false,false,false,false,false
environment.cmdRm=           false,false,false,false,false,false
environment.pawGTMaxPinsp=   false,false,false,false,false,false
environment.dropPAW_ITS=     false,false,false,false,false,false
environment.pause=7000
environment.address=tcp://*:5570