# MODELS AND COMPOSITION
M1.RUNTIME_MODEL_PATH=resources/models/BiPipeFullDuplex/incrementa.asm
M2.RUNTIME_MODEL_PATH=resources/models/BiPipeFullDuplex/decrementa.asm

setup.setup_comp=(M1<||>M2)

# COMMONS
common.HOST=127.0.0.1

# M1 CONFIGURATION 

M1.ZMQ_PUB_SOCKET=tcp://*:5556
M1.ZMQ_SUB_CONNECT_ADDRESSES=tcp://127.0.0.1:5557
M1.ASM_ENVIRONMENT_ADDRESS=tcp://127.0.0.1:5563
M1.ASM_ENVIRONMENT_FUNCTIONS=myinput
M1.CONSOLE_INPUT_FUNCTIONS=funcDec,1

# M2 CONFIGURATION 

M2.ZMQ_PUB_SOCKET=tcp://*:5557
M2.ZMQ_SUB_CONNECT_ADDRESSES=tcp://127.0.0.1:5556
M2.ASM_ENVIRONMENT_ADDRESS=tcp://127.0.0.1:5563
M2.ASM_ENVIRONMENT_FUNCTIONS=myinput
M2.CONSOLE_INPUT_FUNCTIONS=funcInc,0

# ENVIRONMENT
environment.address=tcp://*:5563
# ms pause between sends
environment.pause=3000
environment.env_functions=myinput
# each key = a topic name, value = list of message-values
environment.myinput=2,3,4,5,6