/* Generated By:JavaCC: Do not edit this line. ReadTestsAndTpsConstants.java */
package atgt.project.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ReadTestsAndTpsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LCOMMENT = 5;
  /** RegularExpression Id. */
  int LT = 6;
  /** RegularExpression Id. */
  int LE = 7;
  /** RegularExpression Id. */
  int GT = 8;
  /** RegularExpression Id. */
  int GE = 9;
  /** RegularExpression Id. */
  int NEQ = 10;
  /** RegularExpression Id. */
  int AND = 11;
  /** RegularExpression Id. */
  int OR = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int PLUS = 14;
  /** RegularExpression Id. */
  int MINUS = 15;
  /** RegularExpression Id. */
  int MULT = 16;
  /** RegularExpression Id. */
  int DIV = 17;
  /** RegularExpression Id. */
  int EQ = 18;
  /** RegularExpression Id. */
  int TEST = 19;
  /** RegularExpression Id. */
  int TG = 20;
  /** RegularExpression Id. */
  int ID = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<LCOMMENT>",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!=\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"test\"",
    "\"testgoal\"",
    "<ID>",
    "\":\"",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
  };

}
