package org.asmeta.xt.validation;

@SuppressWarnings("all")
public class ErrorCode {
  public static final String ASM__INVALID_NAME = "ASM_INVALID_NAME";

  public static final String ASM__INVALID_MAINRULE_ARITY = "ASM_INVALID_MAINRULE_ARITY";

  public static final String ASM__MODULE_MAINRULE = "ASM_MODULE_MAINRULE";

  public static final String ASM__MODULE_DEF_INITIAL_STATE = "ASM_MODULE_DEF_INITIAL_STATE";

  public static final String ASM__MODULE_INITIAL_STATE = "ASM_MODULE_INITIAL_STATE";

  public static final String IMPORT_CLAUSE__FILE_NOT_FOUND = "IMPORT_CLAUSE__FILE_NOT_FOUND";

  public static final String IMPORT_CLAUSE__NOT_FOUND = "IMPORT_CLAUSE__NOT_FOUND";

  public static final String IMPORT_CLAUSE__CALLED_TWICE = "IMPORT_CLAUSE__CALLED_TWICE";

  public static final String IMPORT_CLAUSE__NOTHING_TO_IMPORT = "IMPORT_CLAUSE__NOTHING_TO_IMPORT";

  public static final String EXPORT_CLAUSE__NOTHING_TO_EXPORT = "EXPORT_CLAUSE__NOTHING_TO_EXPORT";

  public static final String EXPORT_CLAUSE__NOT_FOUND = "EXPORT_CLAUSE__NOT_FOUND";

  public static final String EXPORT_CLAUSE__CALLED_TWICE = "EXPORT_CLAUSE__CALLED_TWICE";

  public static final String SIGNATURE__DOMAIN_DEFINED_TWICE = "SIGNATURE__DOMAIN_DEFINED_TWICE";

  public static final String SIGNATURE__FUNCTION_DEFINED_TWICE = "SIGNATURE__FUNCTION_DEFINED_TWICE";

  public static final String SIGNATURE__DOMAIN_NOT_FOUND = "SIGNATURE__DOMAIN_NOT_FOUND";

  public static final String SIGNATURE__DOMAIN_NOT_IMPORTED = "SIGNATURE__DOMAIN_NOT_IMPORTED";

  public static final String SIGNATURE__FUNCTION_NOT_FOUND = "SIGNATURE__FUNCTION_NOT_FOUND";

  public static final String SIGNATURE__FUNCTION_NOT_IMPORTED = "SIGNATURE__FUNCTION_NOT_IMPORTED";

  public static final String CONCRETE_DOMAIN__INVALID_TYPE_DOMAIN = "CONCRETE_DOMAIN__INVALID_TYPE_DOMAIN";

  public static final String ENUM_DOMAIN_ALREADY_DECLARED = "ENUM_DOMAIN_ALREADY_DECLARED";

  public static final String BASIC_DOMAIN__INVALID_NAME = "BASIC_DOMAIN__INVALID_NAME";

  public static final String LOCAL_FUNCTION__INVALID_DECLARATION = "LOCAL_FUNCTION__INVALID_DECLARATION";

  public static final String BODY__RULE_NOT_IMPORTED = "BODY_RULE__NOT_IMPORTED";

  public static final String BODY__RULE_NOT_FOUND = "BODY_RULE__NOT_FOUND";

  public static final String DOMAIN_DEFINITION__DOMAIN_NOT_CONCRETE = "DOMAIN_DEFINITION__DOMAIN_NOT_CONCRETE";

  public static final String DOMAIN_DEFINITION__IS_DYNAMIC_DOMAIN = "DOMAIN_DEFINITION__IS_DYNAMIC_DOMAIN";

  public static final String DOMAIN_DEFINITION__DEFINED_TWICE = "DOMAIN_DEFINITION__DEFINED_TWICE";

  public static final String DOMAIN_DEFINITION__ILL_FORMED_BODY = "DOMAIN_DEFINITION__ILL_FORMED_BODY";

  public static final String FUNCTION_DEFINITION__FUNCTION_NOT_STATIC_DERIVED = "FUNCTION_DEFINITION__FUNCTION_NOT_STATIC_DERIVED";

  public static final String FUNCTION_DEFINITION__INVALID_ARITY = "FUNCTION_DEFINITION__INVALID_ARITY";

  public static final String FUNCTION_DEFINITION__INVALID_VARIABLE = "FUNCTION_DEFINITION__INVALID_VARIABLE";

  public static final String FUNCTION_DEFINITION__ILL_FORMED_BODY = "FUNCTION_DEFINITION__ILL_FORMED_BODY";

  public static final String FUNCTION_DEFINITION__DEFINED_TWICE = "FUNCTION_DEFINITION__DEFINED_TWICE";

  public static final String RULE_DECLARATION__DEFINED_TWICE = "RULE_DECLARATION__DEFINED_TWICE";

  public static final String RULE_DECLARATION__INVALID_VARIABLE = "RULE_DECLARATION__INVALID_VARIABLE";

  public static final String CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN = "CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN";

  public static final String INVARINT__NOT_FOUND = "INVARINT__NOT_FOUND";

  public static final String INVARINT__CALLED_TWICE = "INVARINT__CALLED_TWICE";

  public static final String CTL_SPEC__DUPLICATE_NAME = "CTL_SPEC__DUPLICATE_NAME";

  public static final String LTL_SPEC__DUPLICATE_NAME = "LTL_SPEC__DUPLICATE_NAME";

  public static final String INITILIZATION_EMPTY_INIT = "INITILIZATION_EMPTY_INIT";

  public static final String DOMAIN_INIZIALIZATION__DEFINED_TWICE = "DOMAIN_INIZIALIZATION__DEFINED_TWICE";

  public static final String DOMAIN_INIZIALIZATION__IS_STATIC = "DOMAIN_INIZIALIZATION__IS_STATIC";

  public static final String DOMAIN_INIZIALIZATION__ILL_FORMED_BODY = "DOMAIN_INIZIALIZATION__ILL_FORMED_BODY";

  public static final String FUNCTION_INIZIALIZATION__FUNCTION_NOT_DYNAMIC = "FUNCTION_INIZIALIZATION__FUNCTION_NOT_DYNAMIC";

  public static final String FUNCTION_INIZIALIZATION__INVALID_ARITY = "FUNCTION_INIZIALIZATION__INVALID_ARITY";

  public static final String FUNCTION_INIZIALIZATION__INVALID_VARIABLE = "FUNCTION_INIZIALIZATION__INVALID_VARIABLE";

  public static final String FUNCTION_INIZIALIZATION__DEFINED_TWICE = "FUNCTION_INIZIALIZATION__DEFINED_TWICE";

  public static final String FUNCTION_INIZIALIZATION__ILL_FORMED_BODY = "FUNCTION_INIZIALIZATION__ILL_FORMED_BODY";

  public static final String AGENT_INIZIALIZATION__PROGRAM_NOT_FOUND = "AGENT_INIZIALIZATION__PROGRAM_NOT_FOUND";

  public static final String AGENT_INIZIALIZATION__INVALID_DOMAIN = "AGENT_INIZIALIZATION__INVALID_DOMAIN";

  public static final String AGENT_INIZIALIZATION__AGENT_DOMAIN_NOT_DECLARED = "AGENT_INIZIALIZATION__AGENT_DOMAIN_NOT_DECLARED";

  public static final String FUNCTION_TERM__ANY_DOMAIN_NOT_DECLARED = "FUNCTION_TERM__ANY_DOMAIN_NOT_DECLARED";

  public static final String FUNCTION_TERM__INVALID_ARITY_FOR_ZERO_ARITY = "FUNCTION_TERM__INVALID_ARITY_FOR_ZERO_ARITY";

  public static final String FUNCTION_TERM__INVALID_ARITY_FOR_N_ARITY = "FUNCTION_TERM__INVALID_ARITY_FOR_N_ARITY";

  public static final String TERM__DOMAIN_GUARD_NOT_BOOLEAN = "TERM__DOMAIN_GUARD_NOT_BOOLEAN";

  public static final String CONDITIONAL_TERM__IF_ELSE_DOMAIN_NOT_COMPATIBLE = "CONDITIONAL_TERM__IF_ELSE_DOMAIN_NOT_COMPATIBLE";

  public static final String CASE_TERM__RESULT_TERM_DOMAIN_NOT_COMPATIBLE = "CASE_TERM__RESULT_TERM_DOMAIN_NOT_COMPATIBLE";

  public static final String CASE_TERM__OTHERWISE_DOMAIN_NOT_COMPATIBLE = "CASE_TERM__OTHERWISE_DOMAIN_NOT_COMPATIBLE";

  public static final String CASE_TERM__COMPARED_AND_COMPARING_DOMAIN_NOT_COMPATIBLE = "CASE_TERM__COMPARED_AND_COMPARING_DOMAIN_NOT_COMPATIBLE";

  public static final String ENUM_TERM__SYMBOL_NOT_FOUND = "ENUM_TERM__SYMBOL_NOT_FOUND";

  public static final String SET_TERM__ANY_DOMAIN_NOT_DECLARED = "SET_TERM__ANY_DOMAIN_NOT_DECLARED";

  public static final String SET_TERM__ADDED_TWICE = "SET_TERM__ADDED_TWICE";

  public static final String SET_TERM__DIFFERENT_DOMAINS = "SET_TERM__DIFFERENT_DOMAINS";

  public static final String SET_TERM__STEP_NEGATIVE = "SET_TERM__STEP_NEGATIVE";

  public static final String SET_TERM__STEP_NAN = "SET_TERM__STEP_NAN";

  public static final String BAG_TERM__ANY_DOMAIN_NOT_DECLARED = "BAG_TERM__ANY_DOMAIN_NOT_DECLARED";

  public static final String BAG_TERM__ADDED_TWICE = "BAG_TERM__ADDED_TWICE";

  public static final String BAG_TERM__DIFFERENT_DOMAINS = "BAG_TERM__DIFFERENT_DOMAINS";

  public static final String BAG_TERM__STEP_NEGATIVE = "BAG_TERM__STEP_NEGATIVE";

  public static final String BAG_TERM__STEP_NAN = "BAG_TERM__STEP_NAN";

  public static final String SEQUENCE_TERM__ANY_DOMAIN_NOT_DECLARED = "SEQUENCE_TERM__ANY_DOMAIN_NOT_DECLARED";

  public static final String SEQUENCE_TERM__ADDED_TWICE = "SEQUENCE_TERM__ADDED_TWICE";

  public static final String SEQUENCE_TERM__DIFFERENT_DOMAINS = "SEQUENCE_TERM__DIFFERENT_DOMAINS";

  public static final String SEQUENCE_TERM__STEP_NEGATIVE = "SEQUENCE_TERM__STEP_NEGATIVE";

  public static final String SEQUENCE_TERM__STEP_NAN = "SEQUENCE_TERM__STEP_NAN";

  public static final String MAP_TERM__ANY_DOMAIN_NOT_DECLARED = "MAP_TERM__ANY_DOMAIN_NOT_DECLARED";

  public static final String MAP_TERM__DIFFERENT_DOMAINS = "MAP_TERM__DIFFERENT_DOMAINS";

  public static final String LET_TERM__VARIABLE_ALREADY_USED = "LET_TERM__VARIABLE_ALREADY_USED";

  public static final String FINITE_QUANT_TERM__VARIABLE_DOMAIN_NOT_POWERSET = "FINITE_QUANT_TERM__VARIABLE_DOMAIN_NOT_POWERSET";

  public static final String FORALL_TERM__VARIABLE_ALREADY_USED = "FORALL_TERM__VARIABLE_ALREADY_USED";

  public static final String EXIST_TERM__VARIABLE_ALREADY_USED = "EXIST_TERM__VARIABLE_ALREADY_USED";

  public static final String EXIST_UNIQUE_TERM__VARIABLE_ALREADY_USED = "EXIST_UNIQUE_TERM__VARIABLE_ALREADY_USED";

  public static final String SET_CT_TERM__VARIABLE_DOMAIN_NOT_POWERSET = "SET_CT_TERM__VARIABLE_DOMAIN_NOT_POWERSET";

  public static final String SET_CT_TERM__VARIABLE_ALREADY_USED = "SET_CT_TERM__VARIABLE_ALREADY_USED";

  public static final String MAP_CT_TERM__VARIABLE_DOMAIN_NOT_POWERSET = "MAP_CT_TERM__VARIABLE_DOMAIN_NOT_POWERSET";

  public static final String MAP_CT_TERM__VARIABLE_ALREADY_USED = "MAP_CT_TERM__VARIABLE_ALREADY_USED";

  public static final String BAG_CT_TERM__VARIABLE_DOMAIN_NOT_BAG = "BAG_CT_TERM__VARIABLE_DOMAIN_NOT_BAG";

  public static final String BAG_CT_TERM__VARIABLE_ALREADY_USED = "BAG_CT_TERM__VARIABLE_ALREADY_USED";

  public static final String SEQUENCE_CT_TERM__VARIABLE_DOMAIN_NOT_SEQUENCE = "SEQUENCE_CT_TERM__VARIABLE_DOMAIN_NOT_SEQUENCE";

  public static final String SEQUENCE_CT_TERM__VARIABLE_ALREADY_USED = "SEQUENCE_CT_TERM__VARIABLE_ALREADY_USED";

  public static final String LOCATION_TERM__NOT_DYNAMIC = "LOCATION_TERM__NOT_DYNAMIC";

  public static final String VARIABLE_TERM__NOT_DECLARED = "VARIABLE_TERM__NOT_DECLARED";

  public static final String UPDATE_RULE__INVALID_LOCATION = "UPDATE_RULE__INVALID_LOCATION";

  public static final String UPDATE_RULE__DOMAINS_NOT_COMPATIBLE = "UPDATE_RULE__DOMAINS_NOT_COMPATIBLE";

  public static final String UPDATE_RULE__INVALID_VARIABLE = "UPDATE_RULE__INVALID_VARIABLE";

  public static final String EXTENDED_RULE__INVALID_DOMAIN = "EXTENDED_RULE__INVALID_DOMAIN";

  public static final String EXTENDED_RULE__RESERVE_DOMAIN_NOT_DECLARED = "EXTENDED_RULE__RESERVE_DOMAIN_NOT_DECLARED";

  public static final String EXTENDED_RULE__VARIABLE_ALREADY_USED = "EXTENDED_RULE__VARIABLE_ALREADY_USED";

  public static final String CHOOSE_RULE__RANGE_NOT_POWERSET = "CHOOSE_RULE__RANGE_NOT_POWERSET";

  public static final String CHOOSE_RULE__DOMAINS_NOT_COMPATIBLE = "CHOOSE_RULE__DOMAINS_NOT_COMPATIBLE";

  public static final String CHOOSE_RULE__VARIABLE_ALREADY_USED = "CHOOSE_RULE__VARIABLE_ALREADY_USED";

  public static final String FORALL_RULE__RANGE_NOT_POWERSET = "FORALL_RULE__RANGE_NOT_POWERSET";

  public static final String FORALL_RULE__DOMAINS_NOT_COMPATIBLE = "FORALL_RULE__DOMAINS_NOT_COMPATIBLE";

  public static final String FORALL_RULE__VARIABLE_ALREADY_USED = "FORALL_RULE__VARIABLE_ALREADY_USED";

  public static final String LET_RULE__VARIABLE_ALREADY_USED = "LET_RULE__VARIABLE_ALREADY_USED";

  public static final String CASE_RULE__BRANCH_DOMAIN_NOT_COMPATIBLE = "CASE_RULE__BRANCH_DOMAIN_NOT_COMPATIBLE";

  public static final String TERM_AS_RULE_CODOMAIN_NOT_RULE = "TERM_AS_RULE_CODOMAIN_NOT_RULE";
}
