/**
 * generated by Xtext 2.14.0
 */
package org.asmeta.avallaxt.tests.syntax;

import com.google.inject.Inject;
import org.asmeta.avallaxt.avalla.Scenario;
import org.asmeta.avallaxt.tests.AvallaInjectorProvider;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(AvallaInjectorProvider.class)
@SuppressWarnings("all")
public class AvallaXtParsingPickTest {
  @Inject
  private ParseHelper<Scenario> parseHelper;

  @Test
  public void checkPick() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("scenario alpha");
      _builder.newLine();
      _builder.append("load lll");
      _builder.newLine();
      _builder.append("pick $p:= TEA;");
      _builder.newLine();
      final Scenario result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: �errors.join(\", \")�");
      Assert.assertTrue(_builder_1.toString(), errors.isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkPickInRule() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("scenario alpha");
      _builder.newLine();
      _builder.append("load lll");
      _builder.newLine();
      _builder.append("pick $p in r_myRule := TEA;");
      _builder.newLine();
      final Scenario result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: �errors.join(\", \")�");
      Assert.assertTrue(_builder_1.toString(), errors.isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void checkPickInRuleErr() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("scenario alpha");
      _builder.newLine();
      _builder.append("load lll");
      _builder.newLine();
      _builder.append("pick $p in myRule := TEA;");
      _builder.newLine();
      final Scenario result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      int _size = errors.size();
      boolean _equals = (_size == 1);
      Assert.assertTrue(_equals);
      Assert.assertTrue(errors.get(0).toString().contains("expecting RULE_RULE_NAME"));
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
