###############################################################################
###############################################################################
# Sample ResourceBundle properties file
NodeName=atgt
