/**
 * generated by Xtext 2.36.0
 */
package org.asmeta.avallaxt.avalla;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Choose</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.asmeta.avallaxt.avalla.Choose#getVar <em>Var</em>}</li>
 *   <li>{@link org.asmeta.avallaxt.avalla.Choose#getRule <em>Rule</em>}</li>
 *   <li>{@link org.asmeta.avallaxt.avalla.Choose#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.asmeta.avallaxt.avalla.AvallaPackage#getChoose()
 * @model
 * @generated
 */
public interface Choose extends Command
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see org.asmeta.avallaxt.avalla.AvallaPackage#getChoose_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link org.asmeta.avallaxt.avalla.Choose#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

  /**
   * Returns the value of the '<em><b>Rule</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule</em>' attribute.
   * @see #setRule(String)
   * @see org.asmeta.avallaxt.avalla.AvallaPackage#getChoose_Rule()
   * @model
   * @generated
   */
  String getRule();

  /**
   * Sets the value of the '{@link org.asmeta.avallaxt.avalla.Choose#getRule <em>Rule</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rule</em>' attribute.
   * @see #getRule()
   * @generated
   */
  void setRule(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see org.asmeta.avallaxt.avalla.AvallaPackage#getChoose_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link org.asmeta.avallaxt.avalla.Choose#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // Choose
