// SPECIFICATION THAT GIVES THE RESULST:
// java.lang.ArrayIndexOutOfBoundsException: Index 4096 out of bounds for length 4096
//	at org.asmeta.parser.JavaCharStream.readByte(JavaCharStream.java:69)
// problems with javacharstrema generated by the verision of javacc



asm Dragonfly_verification

import ../../STDL/StandardLibrary
import ../../STDL/CTLLibrary

signature:
	
	/*


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque mattis ut nisl at pulvinar. Maecenas eu dolor sed tortor rhoncus bibendum. Integer faucibus turpis nunc, non interdum enim ullamcorper ut. Integer libero magna, mollis et blandit a, lacinia ut lacus. Maecenas ligula leo, posuere ut libero quis, vestibulum tincidunt lacus. Mauris a urna nec orci consectetur imperdiet ac id tortor. Etiam aliquet turpis in pretium tempus. Aliquam vulputate venenatis neque, in lobortis massa placerat id. Aenean augue turpis, ornare viverra neque et, cursus gravida nibh. Cras placerat ex a nisi ultrices vehicula eu sit amet tellus. Mauris in vulputate est. Nulla ac neque eget ligula accumsan congue eleifend non nisi. Quisque semper ipsum quam, vitae placerat sem rutrum in. Nam ultrices vel nulla at ultricies.

Curabitur eu risus neque. Morbi viverra velit nec scelerisque mollis. Morbi sit amet interdum diam, vitae vulputate ligula. Duis sit amet libero dui. Donec eu tellus id felis cursus luctus. Aenean ultricies blandit pulvinar. In convallis nulla ut massa volutpat, sed imperdiet nisi commodo. Donec et metus iaculis ipsum congue iaculis. Suspendisse fringilla vehicula ligula eget cursus. Pellentesque iaculis porta massa porta dapibus. Ut vulputate tempus scelerisque. Phasellus mattis, magna non vulputate ultricies, mi tortor placerat erat, id eleifend felis libero et est.

Nam gravida justo sed dolor ornare, sed consectetur lectus consectetur. Cras id porta enim. Morbi ac nulla hendrerit, euismod tellus non, commodo turpis. Donec dictum, quam at posuere dapibus, dui augue suscipit mauris, nec volutpat nisl nibh at felis. Praesent sapien justo, gravida sed erat eu, varius hendrerit augue. Sed vel purus at tortor fermentum blandit. Phasellus semper quam at erat mattis, a iaculis justo vestibulum. Vivamus imperdiet ultricies massa, a sollicitudin nunc gravida quis. Aenean rutrum mi ut malesuada sodales. Morbi ultricies scelerisque sem id laoreet. Vivamus non consequat leo, vitae pellentesque ligula. Proin vel magna ac justo volutpat congue. Donec a condimentum leo. Quisque pulvinar arcu tortor, eu ornare est sagittis quis. Fusce fringilla ut leo sed maximus. Curabitur euismod lacus odio, eget varius est lobortis consectetur.

Praesent malesuada pulvinar tellus, id gravida odio consequat eu. Aenean dictum dui id vulputate bibendum. Nulla facilisi. Ut arcu lectus, consectetur a lacus id, mollis fermentum sem. Nulla porttitor leo ut augue consequat, a fringilla velit congue. Ut eu egestas nisi. Vivamus vehicula eu sem quis gravida. Mauris non luctus dui, ut imperdiet risus. In sollicitudin turpis lorem, eget rutrum dolor fringilla vel. Nulla et odio id felis hendrerit porttitor at eu quam. Suspendisse accumsan massa ac est porttitor accumsan. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean eget tempus elit. Praesent aliquet, felis nec tincidunt tempor, nisi diam suscipit quam, eget ornare ipsum libero id ipsum. Curabitur nec mauris tortor.

Curabitur eu nunc ultrices, aliquam tortor a, mollis diam. Cras rutrum id nibh et feugiat. Maecenas hendrerit purus id fermentum vulputate. Pellentesque convallis felis odio, a rutrum ligula aliquam et. In non rhoncus magna, sit amet laoreet tellus. Nunc non rutrum libero. Donec pellentesque, sapien non viverra varius, tortor neque finibus ligula, in mollis enim nisl et erat. Pellentesque dictum vulputate fringilla. Sed augue est, pretium et nulla eu, cursus molestie diam. Praesent rhoncus diam quis nibh auctor, vel imperdiet magna placerat. Vivamus nec tincidunt sapien. Aenean sollicitudin ipsum sit amet metus dapibus vulputate.

Nullam quis sapien maximus, finibus elit eu, euismod lorem. Aenean at pulvinar justo, eu bibendum justo. Vivamus convallis mollis ligula id fringilla. Phasellus mattis ex a justo posuere venenatis. Curabitur eu facilisis diam. Sed accumsan consectetur leo et molestie. Morbi convallis odio ligula, vel porta augue gravida eu. Etiam ac facilisis nisl. Maecenas euismod tortor vitae dapibus accumsan.

Phasellus aliquet leo id nulla gravida tincidunt. Sed interdum eros et orci malesuada, aliquam elementum purus egestas. Cras tempor vehicula fringilla. Nunc vel lorem non nunc pellentesque gravida ac euismod turpis. In eget aliquam arcu, vel dictum lectus. Praesent pellentesque eros mauris, non elementum augue maximus at. Aenean iaculis rhoncus molestie.

Vestibulum id arcu ac elit porttitor tempus sed ut orci. Mauris et enim blandit, malesuada augue et, venenatis justo. Suspendisse vel nibh velit. Mauris erat eros, aliquet et mi vel, semper consectetur nunc. Donec sagittis laoreet lorem, sit amet dignissim ante viverra vel. Nam in magna sit amet enim sollicitudin aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce lacinia varius ligula iaculis accumsan. Cras viverra tempus hendrerit. Pellentesque tincidunt placerat sem sodales volutpat. Aenean sed sapien aliquam, vestibulum elit ac, scelerisque nunc. Sed fringilla feugiat lectus, at hendrerit lectus nec.
Generated 8 paragraphs, 754 words, 5090 bytes of Lorem Ipsum


	*/

	/*------------------------------------------------------------------- */
	//            Knowledge  management of the principals
	/*------------------------------------------------------------------- */
	/*


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque mattis ut nisl at pulvinar. Maecenas eu dolor sed tortor rhoncus bibendum. Integer faucibus turpis nunc, non interdum enim ullamcorper ut. Integer libero magna, mollis et blandit a, lacinia ut lacus. Maecenas ligula leo, posuere ut libero quis, vestibulum tincidunt lacus. Mauris a urna nec orci consectetur imperdiet ac id tortor. Etiam aliquet turpis in pretium tempus. Aliquam vulputate venenatis neque, in lobortis massa placerat id. Aenean augue turpis, ornare viverra neque et, cursus gravida nibh. Cras placerat ex a nisi ultrices vehicula eu sit amet tellus. Mauris in vulputate est. Nulla ac neque eget ligula accumsan congue eleifend non nisi. Quisque semper ipsum quam, vitae placerat sem rutrum in. Nam ultrices vel nulla at ultricies.

Curabitur eu risus neque. Morbi viverra velit nec scelerisque mollis. Morbi sit amet interdum diam, vitae vulputate ligula. Duis sit amet libero dui. Donec eu tellus id felis cursus luctus. Aenean ultricies blandit pulvinar. In convallis nulla ut massa volutpat, sed imperdiet nisi commodo. Donec et metus iaculis ipsum congue iaculis. Suspendisse fringilla vehicula ligula eget cursus. Pellentesque iaculis porta massa porta dapibus. Ut vulputate tempus scelerisque. Phasellus mattis, magna non vulputate ultricies, mi tortor placerat erat, id eleifend felis libero et est.

Nam gravida justo sed dolor ornare, sed consectetur lectus consectetur. Cras id porta enim. Morbi ac nulla hendrerit, euismod tellus non, commodo turpis. Donec dictum, quam at posuere dapibus, dui augue suscipit mauris, nec volutpat nisl nibh at felis. Praesent sapien justo, gravida sed erat eu, varius hendrerit augue. Sed vel purus at tortor fermentum blandit. Phasellus semper quam at erat mattis, a iaculis justo vestibulum. Vivamus imperdiet ultricies massa, a sollicitudin nunc gravida quis. Aenean rutrum mi ut malesuada sodales. Morbi ultricies scelerisque sem id laoreet. Vivamus non consequat leo, vitae pellentesque ligula. Proin vel magna ac justo volutpat congue. Donec a condimentum leo. Quisque pulvinar arcu tortor, eu ornare est sagittis quis. Fusce fringilla ut leo sed maximus. Curabitur euismod lacus odio, eget varius est lobortis consectetur.

Praesent malesuada pulvinar tellus, id gravida odio consequat eu. Aenean dictum dui id vulputate bibendum. Nulla facilisi. Ut arcu lectus, consectetur a lacus id, mollis fermentum sem. Nulla porttitor leo ut augue consequat, a fringilla velit congue. Ut eu egestas nisi. Vivamus vehicula eu sem quis gravida. Mauris non luctus dui, ut imperdiet risus. In sollicitudin turpis lorem, eget rutrum dolor fringilla vel. Nulla et odio id felis hendrerit porttitor at eu quam. Suspendisse accumsan massa ac est porttitor accumsan. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean eget tempus elit. Praesent aliquet, felis nec tincidunt tempor, nisi diam suscipit quam, eget ornare ipsum libero id ipsum. Curabitur nec mauris tortor.

Curabitur eu nunc ultrices, aliquam tortor a, mollis diam. Cras rutrum id nibh et feugiat. Maecenas hendrerit purus id fermentum vulputate. Pellentesque convallis felis odio, a rutrum ligula aliquam et. In non rhoncus magna, sit amet laoreet tellus. Nunc non rutrum libero. Donec pellentesque, sapien non viverra varius, tortor neque finibus ligula, in mollis enim nisl et erat. Pellentesque dictum vulputate fringilla. Sed augue est, pretium et nulla eu, cursus molestie diam. Praesent rhoncus diam quis nibh auctor, vel imperdiet magna placerat. Vivamus nec tincidunt sapien. Aenean sollicitudin ipsum sit amet metus dapibus vulputate.

Nullam quis sapien maximus, finibus elit eu, euismod lorem. Aenean at pulvinar justo, eu bibendum justo. Vivamus convallis mollis ligula id fringilla. Phasellus mattis ex a justo posuere venenatis. Curabitur eu facilisis diam. Sed accumsan consectetur leo et molestie. Morbi convallis odio ligula, vel porta augue gravida eu. Etiam ac facilisis nisl. Maecenas euismod tortor vitae dapibus accumsan.

Phasellus aliquet leo id nulla gravida tincidunt. Sed interdum eros et orci malesuada, aliquam elementum purus egestas. Cras tempor vehicula fringilla. Nunc vel lorem non nunc pellentesque gravida ac euismod turpis. In eget aliquam arcu, vel dictum lectus. Praesent pellentesque eros mauris, non elementum augue maximus at. Aenean iaculis rhoncus molestie.

Vestibulum id arcu ac elit porttitor tempus sed ut orci. Mauris et enim blandit, malesuada augue et, venenatis justo. Suspendisse vel nibh velit. Mauris erat eros, aliquet et mi vel, semper consectetur nunc. Donec sagittis laoreet lorem, sit amet dignissim ante viverra vel. Nam in magna sit amet enim sollicitudin aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce lacinia varius ligula iaculis accumsan. Cras viverra tempus hendrerit. Pellentesque tincidunt placerat sem sodales volutpat. Aenean sed sapien aliquam, vestibulum elit ac, scelerisque nunc. Sed fringilla feugiat lectus, at hendrerit lectus nec.
Generated 8 paragraphs, 754 words, 5090 bytes of Lorem Ipsum


	*
	*/





definitions:


/*



Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque mattis ut nisl at pulvinar. Maecenas eu dolor sed tortor rhoncus bibendum. Integer faucibus turpis nunc, non interdum enim ullamcorper ut. Integer libero magna, mollis et blandit a, lacinia ut lacus. Maecenas ligula leo, posuere ut libero quis, vestibulum tincidunt lacus. Mauris a urna nec orci consectetur imperdiet ac id tortor. Etiam aliquet turpis in pretium tempus. Aliquam vulputate venenatis neque, in lobortis massa placerat id. Aenean augue turpis, ornare viverra neque et, cursus gravida nibh. Cras placerat ex a nisi ultrices vehicula eu sit amet tellus. Mauris in vulputate est. Nulla ac neque eget ligula accumsan congue eleifend non nisi. Quisque semper ipsum quam, vitae placerat sem rutrum in. Nam ultrices vel nulla at ultricies.

Curabitur eu risus neque. Morbi viverra velit nec scelerisque mollis. Morbi sit amet interdum diam, vitae vulputate ligula. Duis sit amet libero dui. Donec eu tellus id felis cursus luctus. Aenean ultricies blandit pulvinar. In convallis nulla ut massa volutpat, sed imperdiet nisi commodo. Donec et metus iaculis ipsum congue iaculis. Suspendisse fringilla vehicula ligula eget cursus. Pellentesque iaculis porta massa porta dapibus. Ut vulputate tempus scelerisque. Phasellus mattis, magna non vulputate ultricies, mi tortor placerat erat, id eleifend felis libero et est.

Nam gravida justo sed dolor ornare, sed consectetur lectus consectetur. Cras id porta enim. Morbi ac nulla hendrerit, euismod tellus non, commodo turpis. Donec dictum, quam at posuere dapibus, dui augue suscipit mauris, nec volutpat nisl nibh at felis. Praesent sapien justo, gravida sed erat eu, varius hendrerit augue. Sed vel purus at tortor fermentum blandit. Phasellus semper quam at erat mattis, a iaculis justo vestibulum. Vivamus imperdiet ultricies massa, a sollicitudin nunc gravida quis. Aenean rutrum mi ut malesuada sodales. Morbi ultricies scelerisque sem id laoreet. Vivamus non consequat leo, vitae pellentesque ligula. Proin vel magna ac justo volutpat congue. Donec a condimentum leo. Quisque pulvinar arcu tortor, eu ornare est sagittis quis. Fusce fringilla ut leo sed maximus. Curabitur euismod lacus odio, eget varius est lobortis consectetur.

Praesent malesuada pulvinar tellus, id gravida odio consequat eu. Aenean dictum dui id vulputate bibendum. Nulla facilisi. Ut arcu lectus, consectetur a lacus id, mollis fermentum sem. Nulla porttitor leo ut augue consequat, a fringilla velit congue. Ut eu egestas nisi. Vivamus vehicula eu sem quis gravida. Mauris non luctus dui, ut imperdiet risus. In sollicitudin turpis lorem, eget rutrum dolor fringilla vel. Nulla et odio id felis hendrerit porttitor at eu quam. Suspendisse accumsan massa ac est porttitor accumsan. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean eget tempus elit. Praesent aliquet, felis nec tincidunt tempor, nisi diam suscipit quam, eget ornare ipsum libero id ipsum. Curabitur nec mauris tortor.

Curabitur eu nunc ultrices, aliquam tortor a, mollis diam. Cras rutrum id nibh et feugiat. Maecenas hendrerit purus id fermentum vulputate. Pellentesque convallis felis odio, a rutrum ligula aliquam et. In non rhoncus magna, sit amet laoreet tellus. Nunc non rutrum libero. Donec pellentesque, sapien non viverra varius, tortor neque finibus ligula, in mollis enim nisl et erat. Pellentesque dictum vulputate fringilla. Sed augue est, pretium et nulla eu, cursus molestie diam. Praesent rhoncus diam quis nibh auctor, vel imperdiet magna placerat. Vivamus nec tincidunt sapien. Aenean sollicitudin ipsum sit amet metus dapibus vulputate.

Nullam quis sapien maximus, finibus elit eu, euismod lorem. Aenean at pulvinar justo, eu bibendum justo. Vivamus convallis mollis ligula id fringilla. Phasellus mattis ex a justo posuere venenatis. Curabitur eu facilisis diam. Sed accumsan consectetur leo et molestie. Morbi convallis odio ligula, vel porta augue gravida eu. Etiam ac facilisis nisl. Maecenas euismod tortor vitae dapibus accumsan.

Phasellus aliquet leo id nulla gravida tincidunt. Sed interdum eros et orci malesuada, aliquam elementum purus egestas. Cras tempor vehicula fringilla. Nunc vel lorem non nunc pellentesque gravida ac euismod turpis. In eget aliquam arcu, vel dictum lectus. Praesent pellentesque eros mauris, non elementum augue maximus at. Aenean iaculis rhoncus molestie.

Vestibulum id arcu ac elit porttitor tempus sed ut orci. Mauris et enim blandit, malesuada augue et, venenatis justo. Suspendisse vel nibh velit. Mauris erat eros, aliquet et mi vel, semper consectetur nunc. Donec sagittis laoreet lorem, sit amet dignissim ante viverra vel. Nam in magna sit amet enim sollicitudin aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce lacinia varius ligula iaculis accumsan. Cras viverra tempus hendrerit. Pellentesque tincidunt placerat sem sodales volutpat. Aenean sed sapien aliquam, vestibulum elit ac, scelerisque nunc. Sed fringilla feugiat lectus, at hendrerit lectus nec.
Generated 8 paragraphs, 754 words, 5090 bytes of Lorem Ipsum




Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque mattis ut nisl at pulvinar. Maecenas eu dolor sed tortor rhoncus bibendum. Integer faucibus turpis nunc, non interdum enim ullamcorper ut. Integer libero magna, mollis et blandit a, lacinia ut lacus. Maecenas ligula leo, posuere ut libero quis, vestibulum tincidunt lacus. Mauris a urna nec orci consectetur imperdiet ac id tortor. Etiam aliquet turpis in pretium tempus. Aliquam vulputate venenatis neque, in lobortis massa placerat id. Aenean augue turpis, ornare viverra neque et, cursus gravida nibh. Cras placerat ex a nisi ultrices vehicula eu sit amet tellus. Mauris in vulputate est. Nulla ac neque eget ligula accumsan congue eleifend non nisi. Quisque semper ipsum quam, vitae placerat sem rutrum in. Nam ultrices vel nulla at ultricies.

Curabitur eu risus neque. Morbi viverra velit nec scelerisque mollis. Morbi sit amet interdum diam, vitae vulputate ligula. Duis sit amet libero dui. Donec eu tellus id felis cursus luctus. Aenean ultricies blandit pulvinar. In convallis nulla ut massa volutpat, sed imperdiet nisi commodo. Donec et metus iaculis ipsum congue iaculis. Suspendisse fringilla vehicula ligula eget cursus. Pellentesque iaculis porta massa porta dapibus. Ut vulputate tempus scelerisque. Phasellus mattis, magna non vulputate ultricies, mi tortor placerat erat, id eleifend felis libero et est.

Nam gravida justo sed dolor ornare, sed consectetur lectus consectetur. Cras id porta enim. Morbi ac nulla hendrerit, euismod tellus non, commodo turpis. Donec dictum, quam at posuere dapibus, dui augue suscipit mauris, nec volutpat nisl nibh at felis. Praesent sapien justo, gravida sed erat eu, varius hendrerit augue. Sed vel purus at tortor fermentum blandit. Phasellus semper quam at erat mattis, a iaculis justo vestibulum. Vivamus imperdiet ultricies massa, a sollicitudin nunc gravida quis. Aenean rutrum mi ut malesuada sodales. Morbi ultricies scelerisque sem id laoreet. Vivamus non consequat leo, vitae pellentesque ligula. Proin vel magna ac justo volutpat congue. Donec a condimentum leo. Quisque pulvinar arcu tortor, eu ornare est sagittis quis. Fusce fringilla ut leo sed maximus. Curabitur euismod lacus odio, eget varius est lobortis consectetur.

Praesent malesuada pulvinar tellus, id gravida odio consequat eu. Aenean dictum dui id vulputate bibendum. Nulla facilisi. Ut arcu lectus, consectetur a lacus id, mollis fermentum sem. Nulla porttitor leo ut augue consequat, a fringilla velit congue. Ut eu egestas nisi. Vivamus vehicula eu sem quis gravida. Mauris non luctus dui, ut imperdiet risus. In sollicitudin turpis lorem, eget rutrum dolor fringilla vel. Nulla et odio id felis hendrerit porttitor at eu quam. Suspendisse accumsan massa ac est porttitor accumsan. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean eget tempus elit. Praesent aliquet, felis nec tincidunt tempor, nisi diam suscipit quam, eget ornare ipsum libero id ipsum. Curabitur nec mauris tortor.

Curabitur eu nunc ultrices, aliquam tortor a, mollis diam. Cras rutrum id nibh et feugiat. Maecenas hendrerit purus id fermentum vulputate. Pellentesque convallis felis odio, a rutrum ligula aliquam et. In non rhoncus magna, sit amet laoreet tellus. Nunc non rutrum libero. Donec pellentesque, sapien non viverra varius, tortor neque finibus ligula, in mollis enim nisl et erat. Pellentesque dictum vulputate fringilla. Sed augue est, pretium et nulla eu, cursus molestie diam. Praesent rhoncus diam quis nibh auctor, vel imperdiet magna placerat. Vivamus nec tincidunt sapien. Aenean sollicitudin ipsum sit amet metus dapibus vulputate.

Nullam quis sapien maximus, finibus elit eu, euismod lorem. Aenean at pulvinar justo, eu bibendum justo. Vivamus convallis mollis ligula id fringilla. Phasellus mattis ex a justo posuere venenatis. Curabitur eu facilisis diam. Sed accumsan consectetur leo et molestie. Morbi convallis odio ligula, vel porta augue gravida eu. Etiam ac facilisis nisl. Maecenas euismod tortor vitae dapibus accumsan.

Phasellus aliquet leo id nulla gravida tincidunt. Sed interdum eros et orci malesuada, aliquam elementum purus egestas. Cras tempor vehicula fringilla. Nunc vel lorem non nunc pellentesque gravida ac euismod turpis. In eget aliquam arcu, vel dictum lectus. Praesent pellentesque eros mauris, non elementum augue maximus at. Aenean iaculis rhoncus molestie.

Vestibulum id arcu ac elit porttitor tempus sed ut orci. Mauris et enim blandit, malesuada augue et, venenatis justo. Suspendisse vel nibh velit. Mauris erat eros, aliquet et mi vel, semper consectetur nunc. Donec sagittis laoreet lorem, sit amet dignissim ante viverra vel. Nam in magna sit amet enim sollicitudin aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce lacinia varius ligula iaculis accumsan. Cras viverra tempus hendrerit. Pellentesque tincidunt placerat sem sodales volutpat. Aenean sed sapien aliquam, vestibulum elit ac, scelerisque nunc. Sed fringilla feugiat lectus, at hendrerit lectus nec.
Generated 8 paragraphs, 754 words, 5090 bytes of Lorem Ipsum




Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque mattis ut nisl at pulvinar. Maecenas eu dolor sed tortor rhoncus bibendum. Integer faucibus turpis nunc, non interdum enim ullamcorper ut. Integer libero magna, mollis et blandit a, lacinia ut lacus. Maecenas ligula leo, posuere ut libero quis, vestibulum tincidunt lacus. Mauris a urna nec orci consectetur imperdiet ac id tortor. Etiam aliquet turpis in pretium tempus. Aliquam vulputate venenatis neque, in lobortis massa placerat id. Aenean augue turpis, ornare viverra neque et, cursus gravida nibh. Cras placerat ex a nisi ultrices vehicula eu sit amet tellus. Mauris in vulputate est. Nulla ac neque eget ligula accumsan congue eleifend non nisi. Quisque semper ipsum quam, vitae placerat sem rutrum in. Nam ultrices vel nulla at ultricies.

Curabitur eu risus neque. Morbi viverra velit nec scelerisque mollis. Morbi sit amet interdum diam, vitae vulputate ligula. Duis sit amet libero dui. Donec eu tellus id felis cursus luctus. Aenean ultricies blandit pulvinar. In convallis nulla ut massa volutpat, sed imperdiet nisi commodo. Donec et metus iaculis ipsum congue iaculis. Suspendisse fringilla vehicula ligula eget cursus. Pellentesque iaculis porta massa porta dapibus. Ut vulputate tempus scelerisque. Phasellus mattis, magna non vulputate ultricies, mi tortor placerat erat, id eleifend felis libero et est.

Nam gravida justo sed dolor ornare, sed consectetur lectus consectetur. Cras id porta enim. Morbi ac nulla hendrerit, euismod tellus non, commodo turpis. Donec dictum, quam at posuere dapibus, dui augue suscipit mauris, nec volutpat nisl nibh at felis. Praesent sapien justo, gravida sed erat eu, varius hendrerit augue. Sed vel purus at tortor fermentum blandit. Phasellus semper quam at erat mattis, a iaculis justo vestibulum. Vivamus imperdiet ultricies massa, a sollicitudin nunc gravida quis. Aenean rutrum mi ut malesuada sodales. Morbi ultricies scelerisque sem id laoreet. Vivamus non consequat leo, vitae pellentesque ligula. Proin vel magna ac justo volutpat congue. Donec a condimentum leo. Quisque pulvinar arcu tortor, eu ornare est sagittis quis. Fusce fringilla ut leo sed maximus. Curabitur euismod lacus odio, eget varius est lobortis consectetur.

Praesent malesuada pulvinar tellus, id gravida odio consequat eu. Aenean dictum dui id vulputate bibendum. Nulla facilisi. Ut arcu lectus, consectetur a lacus id, mollis fermentum sem. Nulla porttitor leo ut augue consequat, a fringilla velit congue. Ut eu egestas nisi. Vivamus vehicula eu sem quis gravida. Mauris non luctus dui, ut imperdiet risus. In sollicitudin turpis lorem, eget rutrum dolor fringilla vel. Nulla et odio id felis hendrerit porttitor at eu quam. Suspendisse accumsan massa ac est porttitor accumsan. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean eget tempus elit. Praesent aliquet, felis nec tincidunt tempor, nisi diam suscipit quam, eget ornare ipsum libero id ipsum. Curabitur nec mauris tortor.

Curabitur eu nunc ultrices, aliquam tortor a, mollis diam. Cras rutrum id nibh et feugiat. Maecenas hendrerit purus id fermentum vulputate. Pellentesque convallis felis odio, a rutrum ligula aliquam et. In non rhoncus magna, sit amet laoreet tellus. Nunc non rutrum libero. Donec pellentesque, sapien non viverra varius, tortor neque finibus ligula, in mollis enim nisl et erat. Pellentesque dictum vulputate fringilla. Sed augue est, pretium et nulla eu, cursus molestie diam. Praesent rhoncus diam quis nibh auctor, vel imperdiet magna placerat. Vivamus nec tincidunt sapien. Aenean sollicitudin ipsum sit amet metus dapibus vulputate.

Nullam quis sapien maximus, finibus elit eu, euismod lorem. Aenean at pulvinar justo, eu bibendum justo. Vivamus convallis mollis ligula id fringilla. Phasellus mattis ex a justo posuere venenatis. Curabitur eu facilisis diam. Sed accumsan consectetur leo et molestie. Morbi convallis odio ligula, vel porta augue gravida eu. Etiam ac facilisis nisl. Maecenas euismod tortor vitae dapibus accumsan.

Phasellus aliquet leo id nulla gravida tincidunt. Sed interdum eros et orci malesuada, aliquam elementum purus egestas. Cras tempor vehicula fringilla. Nunc vel lorem non nunc pellentesque gravida ac euismod turpis. In eget aliquam arcu, vel dictum lectus. Praesent pellentesque eros mauris, non elementum augue maximus at. Aenean iaculis rhoncus molestie.

Vestibulum id arcu ac elit porttitor tempus sed ut orci. Mauris et enim blandit, malesuada augue et, venenatis justo. Suspendisse vel nibh velit. Mauris erat eros, aliquet et mi vel, semper consectetur nunc. Donec sagittis laoreet lorem, sit amet dignissim ante viverra vel. Nam in magna sit amet enim sollicitudin aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce lacinia varius ligula iaculis accumsan. Cras viverra tempus hendrerit. Pellentesque tincidunt placerat sem sodales volutpat. Aenean sed sapien aliquam, vestibulum elit ac, scelerisque nunc. Sed fringilla feugiat lectus, at hendrerit lectus nec.
Generated 8 paragraphs, 754 words, 5090 bytes of Lorem Ipsum


*/

//CTLSPEC not(ef(initiatorState(nodeA)=END_A and receiverState(nodeB)=END_B))	

		
main rule r_Main = skip
		
default init s0:
	
