/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 08 11:05:20 GMT 2025
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ATM3_ATG_ESTest extends ATM3_ATG_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ATM3_ATG aTM3_ATG0 = new ATM3_ATG();
      
      aTM3_ATG0.step();
      
      int int4 = aTM3_ATG0.get_balance_card3();
      assertEquals(548, int4);
            
      aTM3_ATG0.set_insertMoneySizeOther(int4);
      
      String string0 = "card1";
      aTM3_ATG0.set_insertedCard(string0);
      
  }
}