/**
 * generated by Xtext 2.17.0
 */
package org.asmeta.avallaxt.avallaXt.impl;

import org.asmeta.avallaxt.avallaXt.AvallaXtPackage;
import org.asmeta.avallaxt.avallaXt.Step;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StepImpl extends CommandImpl implements Step
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AvallaXtPackage.Literals.STEP;
  }

} //StepImpl
