/*
 * generated by Xtext 2.14.0
 */
package org.asmeta.avallaxt.syntax

import com.google.inject.Inject
import org.asmeta.avallaxt.avalla.Scenario
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.asmeta.avallaxt.tests.AvallaInjectorProvider

@ExtendWith(InjectionExtension)
@InjectWith(AvallaInjectorProvider)
class AvallaXtParsingInvariantTest {
	@Inject
	ParseHelper<Scenario> parseHelper
	
	@Test
	def void inv1() {
		test("x");
	}

	@Test
	def void inv2() {
		test("x + yy");
		test("f(x,6) + yy = 90");
	}

	@Test
	def void invmolte() {
		test("x > 0");
	}

	
	def void test(String i){
		println("testing with " + i)
		val scenario = "scenario scen load spec invariant myInv : "+ i + " ;";
		val result = parseHelper.parse(scenario)
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty,'''Unexpected errors: «errors.join(", ")»''')
		Assertions.assertEquals((result as Scenario).invariants.get(0).expression,i)
		
	}
}
