/* Generated By:JavaCC: Do not edit this line. ASMParserConstants.java */
package org.asmeta.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ASMParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASM = 7;
  /** RegularExpression Id. */
  int MODULE = 8;
  /** RegularExpression Id. */
  int ASYNCR = 9;
  /** RegularExpression Id. */
  int IMPORT = 10;
  /** RegularExpression Id. */
  int EXPORT = 11;
  /** RegularExpression Id. */
  int SIGNATURE = 12;
  /** RegularExpression Id. */
  int INIT = 13;
  /** RegularExpression Id. */
  int Default = 14;
  /** RegularExpression Id. */
  int AGENT = 15;
  /** RegularExpression Id. */
  int INVARIANT = 16;
  /** RegularExpression Id. */
  int CTLSPEC = 17;
  /** RegularExpression Id. */
  int NAME = 18;
  /** RegularExpression Id. */
  int LTLSPEC = 19;
  /** RegularExpression Id. */
  int JUSTICE = 20;
  /** RegularExpression Id. */
  int FAIRNESS = 21;
  /** RegularExpression Id. */
  int COMPASSION = 22;
  /** RegularExpression Id. */
  int INVAR = 23;
  /** RegularExpression Id. */
  int OVER = 24;
  /** RegularExpression Id. */
  int DEFINITIONS = 25;
  /** RegularExpression Id. */
  int FUNCTION = 26;
  /** RegularExpression Id. */
  int STATIC = 27;
  /** RegularExpression Id. */
  int DYNAMIC = 28;
  /** RegularExpression Id. */
  int DERIVED = 29;
  /** RegularExpression Id. */
  int MONITORED = 30;
  /** RegularExpression Id. */
  int CONTROLLED = 31;
  /** RegularExpression Id. */
  int SHARED = 32;
  /** RegularExpression Id. */
  int OUT = 33;
  /** RegularExpression Id. */
  int DOMAIN = 34;
  /** RegularExpression Id. */
  int ANYDOMAIN = 35;
  /** RegularExpression Id. */
  int BASIC = 36;
  /** RegularExpression Id. */
  int ABSTRACT = 37;
  /** RegularExpression Id. */
  int ENUM = 38;
  /** RegularExpression Id. */
  int SUBSETOF = 39;
  /** RegularExpression Id. */
  int PROD = 40;
  /** RegularExpression Id. */
  int SEQ = 41;
  /** RegularExpression Id. */
  int POWERSET = 42;
  /** RegularExpression Id. */
  int BAG = 43;
  /** RegularExpression Id. */
  int MAP = 44;
  /** RegularExpression Id. */
  int RULEDOM = 45;
  /** RegularExpression Id. */
  int TRUE = 46;
  /** RegularExpression Id. */
  int FALSE = 47;
  /** RegularExpression Id. */
  int UNDEF = 48;
  /** RegularExpression Id. */
  int IM_PART = 49;
  /** RegularExpression Id. */
  int IF = 50;
  /** RegularExpression Id. */
  int THEN = 51;
  /** RegularExpression Id. */
  int ELSE = 52;
  /** RegularExpression Id. */
  int ENDIF = 53;
  /** RegularExpression Id. */
  int SWITCH = 54;
  /** RegularExpression Id. */
  int END_SWITCH = 55;
  /** RegularExpression Id. */
  int CASE = 56;
  /** RegularExpression Id. */
  int OTHERWISE = 57;
  /** RegularExpression Id. */
  int ENDCASE = 58;
  /** RegularExpression Id. */
  int LET = 59;
  /** RegularExpression Id. */
  int ENDLET = 60;
  /** RegularExpression Id. */
  int EXIST = 61;
  /** RegularExpression Id. */
  int UNIQUE = 62;
  /** RegularExpression Id. */
  int WITH = 63;
  /** RegularExpression Id. */
  int FORALL = 64;
  /** RegularExpression Id. */
  int Skip = 65;
  /** RegularExpression Id. */
  int RULE = 66;
  /** RegularExpression Id. */
  int MACRO = 67;
  /** RegularExpression Id. */
  int TURBO = 68;
  /** RegularExpression Id. */
  int MAIN = 69;
  /** RegularExpression Id. */
  int PAR = 70;
  /** RegularExpression Id. */
  int ENDPAR = 71;
  /** RegularExpression Id. */
  int CHOOSE = 72;
  /** RegularExpression Id. */
  int DO = 73;
  /** RegularExpression Id. */
  int IFNONE = 74;
  /** RegularExpression Id. */
  int EXTEND = 75;
  /** RegularExpression Id. */
  int seq = 76;
  /** RegularExpression Id. */
  int ENDSEQ = 77;
  /** RegularExpression Id. */
  int ITERATE = 78;
  /** RegularExpression Id. */
  int ENDITERATE = 79;
  /** RegularExpression Id. */
  int LOCAL = 80;
  /** RegularExpression Id. */
  int TRY = 81;
  /** RegularExpression Id. */
  int CATCH = 82;
  /** RegularExpression Id. */
  int WHILE = 83;
  /** RegularExpression Id. */
  int WHILEREC = 84;
  /** RegularExpression Id. */
  int IN = 85;
  /** RegularExpression Id. */
  int EQ = 86;
  /** RegularExpression Id. */
  int LT = 87;
  /** RegularExpression Id. */
  int LE = 88;
  /** RegularExpression Id. */
  int GT = 89;
  /** RegularExpression Id. */
  int GE = 90;
  /** RegularExpression Id. */
  int NEQ = 91;
  /** RegularExpression Id. */
  int PLUS = 92;
  /** RegularExpression Id. */
  int MINUS = 93;
  /** RegularExpression Id. */
  int MULT = 94;
  /** RegularExpression Id. */
  int DIV = 95;
  /** RegularExpression Id. */
  int PWR = 96;
  /** RegularExpression Id. */
  int NUMBER = 97;
  /** RegularExpression Id. */
  int NATNUMBER = 98;
  /** RegularExpression Id. */
  int REAL_NUMBER = 99;
  /** RegularExpression Id. */
  int COMPLEX_NUMBER = 100;
  /** RegularExpression Id. */
  int ID_VARIABLE = 101;
  /** RegularExpression Id. */
  int ID_ENUM = 102;
  /** RegularExpression Id. */
  int ID_DOMAIN = 103;
  /** RegularExpression Id. */
  int ID_RULE = 104;
  /** RegularExpression Id. */
  int ID_AXIOM = 105;
  /** RegularExpression Id. */
  int ID_CTL = 106;
  /** RegularExpression Id. */
  int ID_LTL = 107;
  /** RegularExpression Id. */
  int ID_FUNCTION = 108;
  /** RegularExpression Id. */
  int LETTER = 109;
  /** RegularExpression Id. */
  int DIGIT = 110;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 111;
  /** RegularExpression Id. */
  int STRING_LITERAL = 112;
  /** RegularExpression Id. */
  int ID = 113;
  /** RegularExpression Id. */
  int MOD_ID = 114;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int GENERIC_ID = 1;
  /** Lexical state. */
  int MODULE_ID = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"asm\"",
    "\"module\"",
    "\"asyncr\"",
    "\"import\"",
    "\"export\"",
    "\"signature\"",
    "\"init\"",
    "\"default\"",
    "\"agent\"",
    "\"invariant\"",
    "<CTLSPEC>",
    "\"NAME\"",
    "\"LTLSPEC\"",
    "\"JUSTICE\"",
    "\"FAIRNESS\"",
    "\"COMPASSION\"",
    "\"INVAR\"",
    "\"over\"",
    "\"definitions\"",
    "\"function\"",
    "\"static\"",
    "\"dynamic\"",
    "\"derived\"",
    "\"monitored\"",
    "\"controlled\"",
    "\"shared\"",
    "\"out\"",
    "\"domain\"",
    "\"anydomain\"",
    "\"basic\"",
    "\"abstract\"",
    "\"enum\"",
    "\"subsetof\"",
    "\"Prod\"",
    "\"Seq\"",
    "\"Powerset\"",
    "\"Bag\"",
    "\"Map\"",
    "\"Rule\"",
    "\"true\"",
    "\"false\"",
    "\"undef\"",
    "\"i\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"switch\"",
    "\"endswitch\"",
    "\"case\"",
    "\"otherwise\"",
    "\"endcase\"",
    "\"let\"",
    "\"endlet\"",
    "\"exist\"",
    "\"unique\"",
    "\"with\"",
    "\"forall\"",
    "\"skip\"",
    "\"rule\"",
    "\"macro\"",
    "\"turbo\"",
    "\"main\"",
    "\"par\"",
    "\"endpar\"",
    "\"choose\"",
    "\"do\"",
    "\"ifnone\"",
    "\"extend\"",
    "\"seq\"",
    "\"endseq\"",
    "\"iterate\"",
    "\"enditerate\"",
    "\"local\"",
    "\"try\"",
    "\"catch\"",
    "\"while\"",
    "\"whilerec\"",
    "\"in\"",
    "\"=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "<NUMBER>",
    "<NATNUMBER>",
    "<REAL_NUMBER>",
    "<COMPLEX_NUMBER>",
    "<ID_VARIABLE>",
    "<ID_ENUM>",
    "<ID_DOMAIN>",
    "<ID_RULE>",
    "<ID_AXIOM>",
    "<ID_CTL>",
    "<ID_LTL>",
    "<ID_FUNCTION>",
    "<LETTER>",
    "<DIGIT>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ID>",
    "<MOD_ID>",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\":\"",
    "\"{\"",
    "\"|\"",
    "\"}\"",
    "\"->\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"<<\"",
    "\">>\"",
    "\":=\"",
    "\"<-\"",
  };

}
