/*
 * generated by Xtext 2.14.0
 */
package org.asmeta.avallaxt.syntax

import com.google.inject.Inject
import org.asmeta.avallaxt.avalla.Scenario
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.asmeta.avallaxt.tests.AvallaInjectorProvider

@ExtendWith(InjectionExtension)
@InjectWith(AvallaInjectorProvider)
// test of load
class AvallaXtParsingImportTest {
	@Inject
	ParseHelper<Scenario> parseHelper
	
	@Test
	def void importID() {
		test("spec");
	}

	@Test
	def void importASM() {
		test("spec.asm");
	}

	@Test
	def void importRelative() {
		test("4ooo/spec.asm");
	}

	@Test
	def void importAbsolute() {
		// anche assoluto vuole le virgolette
		test("\"c:\\temp\\spec.asm\"");
	}

	@Test
	def void importwithspaces() {		
		test("\"c:\\My Documents\\spec.asm\"");
	}

	@Test
	def void import2() {
		test("../../temp/aaa");
	}
	
	@Test
	def void importDollar1() {
		test("$temp/aaa");
	}
	
	@Test
	def void importDollar2() {
		test("../aa/$temp/aaa");
	}
	
	@Test
	def void importDollar3() {
		test("$temp.asm");
	}


	// test only the parser	
	def void test(String i){
		println("testing with " + i)
		val scenario = "scenario scen load "+ i;
		val result = parseHelper.parse(scenario)
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty,'''Unexpected errors: «errors.join(", ")»''')
		Assertions.assertEquals((result as Scenario).spec,i)
					
	}
}
