# MODELS AND COMPOSITION

pedestrian.RUNTIME_MODEL_PATH=resources/models/trafficLightCoSimCross/pedestrian.asm
tram.RUNTIME_MODEL_PATH=resources/models/trafficLightCoSimCross/tram.asm
crossManager.RUNTIME_MODEL_PATH=resources/models/trafficLightCoSimCross/crossManager.asm
controller.RUNTIME_MODEL_PATH=resources/models/trafficLightCoSimCross/controller.asm
trafficlightA.RUNTIME_MODEL_PATH=resources/models/trafficLightCoSimCross/trafficlightA.asm
trafficlightB.RUNTIME_MODEL_PATH=resources/models/trafficLightCoSimCross/trafficlightB.asm


setup.setup_comp= (((pedestrian || tram) <|> crossManager) <||> controller) | (trafficlightA || trafficlightB)

#COMMONS
common.HOST=127.0.0.1
common.ASM_ENVIRONMENT_FUNCTIONS=newPedestrianComing,newTramComing,transitionC,mCurrTimeSecs

# Initial state values for bootstrap publish in CHOREOGRAPHED mode
# These values mirror the default init s0 of each ASM

controller.INITIAL_OUTPUTS=statusC=CONTR_OFF,operateMode=RED_AB
crossManager.INITIAL_OUTPUTS=crossManagerController=NORMAL
pedestrian.INITIAL_OUTPUTS=pedestrianComing=false,pedestrianLight=RED
tram.INITIAL_OUTPUTS=tramComing=false,tramLight=RED
trafficlightA.INITIAL_OUTPUTS=lightsA=ALL_OFF
trafficlightB.INITIAL_OUTPUTS=lightsB=ALL_OFF


# PEDESTRIAN CONFIGURATION
pedestrian.ZMQ_PUB_SOCKET=tcp://*:5556
pedestrian.ZMQ_SUB_CONNECT_ADDRESSES=tcp://127.0.0.1:5558
pedestrian.ASM_SUB_FUNCTIONS=crossManagerController
pedestrian.ASM_ENVIRONMENT_FUNCTIONS=newPedestrianComing,mCurrTimeSecs
pedestrian.ASM_ENVIRONMENT_ADDRESS=tcp://127.0.0.1:5570

# TRAM CONFIGURATION
tram.ZMQ_PUB_SOCKET=tcp://*:5557
tram.ZMQ_SUB_CONNECT_ADDRESSES=tcp://127.0.0.1:5558
tram.ASM_SUB_FUNCTIONS=crossManagerController
tram.ASM_ENVIRONMENT_FUNCTIONS=newTramComing,mCurrTimeSecs
tram.ASM_ENVIRONMENT_ADDRESS=tcp://127.0.0.1:5570

# CROSSMANAGER CONFIGURATION
crossManager.ZMQ_PUB_SOCKET=tcp://*:5558
crossManager.ZMQ_SUB_CONNECT_ADDRESSES=tcp://127.0.0.1:5556,tcp://127.0.0.1:5557,tcp://127.0.0.1:5559
crossManager.ASM_SUB_FUNCTIONS=pedestrianComing,tramComing,statusC
crossManager.ASM_ENVIRONMENT_FUNCTIONS=mCurrTimeSecs
crossManager.ASM_ENVIRONMENT_ADDRESS=tcp://127.0.0.1:5570

# CONTROLLER CONFIGURATION
controller.ZMQ_PUB_SOCKET=tcp://*:5559
controller.ZMQ_SUB_CONNECT_ADDRESSES=tcp://127.0.0.1:5558
controller.ASM_SUB_FUNCTIONS=crossManagerController
controller.ASM_ENVIRONMENT_FUNCTIONS=transitionC,mCurrTimeSecs
controller.ASM_ENVIRONMENT_ADDRESS=tcp://127.0.0.1:5570

# TRAFFICLIGHT_A CONFIGURATION
trafficlightA.ZMQ_PUB_SOCKET=tcp://*:5560
trafficlightA.ZMQ_SUB_CONNECT_ADDRESSES=tcp://127.0.0.1:5559
trafficlightA.ASM_SUB_FUNCTIONS=statusC,operateMode

# TRAFFICLIGHT_B CONFIGURATION
trafficlightB.ZMQ_PUB_SOCKET=tcp://*:5563
trafficlightB.ZMQ_SUB_CONNECT_ADDRESSES=tcp://127.0.0.1:5559
trafficlightB.ASM_SUB_FUNCTIONS=statusC,operateMode

# ENVIRONMENT
environment.address=tcp://*:5570
environment.pause=3000
environment.env_functions=newPedestrianComing,newTramComing,transitionC,mCurrTimeSecs

# each key = a topic name, value = list of message-values
environment.newPedestrianComing= false,false,false,false,false,true,true,false,false,false
environment.newTramComing= false,false,false,false,false,false,false,false,false,false
environment.transitionC= TURN_ON,OPERATE_T,OPERATE_T,OPERATE_T,OPERATE_T,OPERATE_T,OPERATE_T,OPERATE_T,OPERATE_T,OPERATE_T
environment.mCurrTimeSecs= 1,2,3,4,5,6,7,8,9,10