# MODELS AND COMPOSITION
#setup.M1=resources/models/digitalTwinExample/producerasm.asm
#setup.M2=resources/models/digitalTwinExample/consumerasm.asm

M1.RUNTIME_MODEL_PATH=resources/models/digitalTwinExample/producerasm.asm
M2.RUNTIME_MODEL_PATH=resources/models/digitalTwinExample/consumerasm.asm

setup.setup_comp=(M1|M2)

#COMMONS
common.HOST=127.0.0.1


# M1 CONFIGURATION
M1.ZMQ_PUB_SOCKET=tcp://*:5556
M1.ZMQ_SUB_CONNECT_ADDRESSES=tcp://127.0.0.1:5563
M1.ASM_ENVIRONMENT_FUNCTIONS=inputTemp,inputHR



# M2 CONFIGURATION
M2.ZMQ_SUB_CONNECT_ADDRESSES=tcp://127.0.0.1:5556
M2.ZMQ_PUB_SOCKET=tcp://*:5557

# ENVIRONMENT
environment.address=tcp://*:5563
# ms pause between sends
environment.pause=3000
environment.env_functions=inputTemp,inputHR
# each key = a topic name, value = list of message-values
environment.inputTemp=37,39,36,40,38,36
environment.inputHR=80,85,45,130,50,80
