/**
 * generated by Xtext 2.42.0
 */
package org.asmeta.xt.asmetal.impl;

import org.asmeta.xt.asmetal.AsmetalPackage;
import org.asmeta.xt.asmetal.ExistsUniqueTerm;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exists Unique Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExistsUniqueTermImpl extends FiniteQuantificationTermImpl implements ExistsUniqueTerm
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExistsUniqueTermImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetalPackage.Literals.EXISTS_UNIQUE_TERM;
  }

} //ExistsUniqueTermImpl
