/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 11 20:36:23 GMT 2025
 */

package domaintests;

import domaintests.AbstractTD.EnumDomain;
import org.junit.Test;
import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AbstractTD_ATG_ESTest extends AbstractTD_ATG_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AbstractTD_ATG abstractTD_ATG0 = new AbstractTD_ATG();
      assertNotNull(abstractTD_ATG0);
      assertEquals("Hello world", abstractTD_ATG0.get_stringControlledFunction());
      String string0 = abstractTD_ATG0.get_abstractControlledFunction();
      assertEquals("abstract_value1", string0);
      assertNotNull(string0);
      String string1 = abstractTD_ATG0.get_enumtoabstractControlledFunction_fromDomain_STATE3();
      assertEquals("abstract_value1", string1);
      assertNotNull(string1);
      Integer int0 = abstractTD_ATG0.get_abstracttointegerControlledFunction_fromDomain_value1();
      assertEquals(10, (int)int0);
      Double double0 = abstractTD_ATG0.get_abstracttorealControlledFunction_fromDomain_value1();
      assertEquals(2.2, (double)double0, 0.01);
      Character character0 = abstractTD_ATG0.get_abstracttocharControlledFunction_fromDomain_value1();
      assertEquals('c', (char)character0);
      String string2 = abstractTD_ATG0.get_abstracttostringControlledFunction_fromDomain_value2();
      assertEquals("hello world", string2);
      Boolean bool1 = abstractTD_ATG0.get_abstracttobooleanControlledFunction_fromDomain_value1();
      assertTrue(bool1);
      AbstractTD.EnumDomain enum0 = abstractTD_ATG0.get_abstracttoenumControlledFunction_fromDomain_value1();
      assertEquals(EnumDomain.STATE1, enum0);
      String string3 = abstractTD_ATG0.get_abstracttoabstractControlledFunction_fromDomain_value1();
      assertEquals("abstract_another1", string3);
      Integer int1 = abstractTD_ATG0.get_abstracttoconcreteControlledFunction_fromDomain_value2();
      assertEquals(5, (int)int1);
      assertEquals("hello world", abstractTD_ATG0.get_abstracttostringControlledFunction_fromDomain_value1());
      assertFalse(abstractTD_ATG0.get_abstracttobooleanControlledFunction_fromDomain_value2());

      abstractTD_ATG0.step();

      abstractTD_ATG0.set_stringMonitoredFunction("Hello world");
      abstractTD_ATG0.set_abstract_enumtoabstractMonitoredFunction_fromDomain_STATE3("value2");
      abstractTD_ATG0.set_abstract_abstractMonitoredFunction("value2");
      abstractTD_ATG0.set_abstracttointegerMonitoredFunction_fromDomain_value1(10);
      abstractTD_ATG0.set_abstracttobooleanMonitoredFunction_fromDomain_value1(false);
      abstractTD_ATG0.set_abstracttostringMonitoredFunction_fromDomain_value1("Hello world");
      abstractTD_ATG0.set_abstracttorealMonitoredFunction_fromDomain_value1(2.5);
      abstractTD_ATG0.set_abstracttocharMonitoredFunction_fromDomain_value1('d');
      abstractTD_ATG0.set_abstracttoenumMonitoredFunction_fromDomain_value1(EnumDomain.STATE1);
      abstractTD_ATG0.set_abstract_abstracttoabstractMonitoredFunction_fromDomain_value1("another1");
      abstractTD_ATG0.set_abstracttoconcreteMonitoredFunction_fromDomain_value2(5);
      abstractTD_ATG0.set_abstracttoconcreteMonitoredFunction_fromDomain_value1(int1);

      abstractTD_ATG0.step();
      
      String string4 = "Hello world";
      abstractTD_ATG0.set_stringMonitoredFunction(string4);
      String string5 = "value2";
      abstractTD_ATG0.set_abstract_enumtoabstractMonitoredFunction_fromDomain_STATE3(string5);
      abstractTD_ATG0.set_abstract_abstractMonitoredFunction(string5);
      int int2 = 10;
      abstractTD_ATG0.set_abstracttointegerMonitoredFunction_fromDomain_value1(int2);
      boolean boolean0 = false;
      abstractTD_ATG0.set_abstracttobooleanMonitoredFunction_fromDomain_value1(boolean0);
      abstractTD_ATG0.set_abstracttostringMonitoredFunction_fromDomain_value1(string4);
      double double0 = 2.5;
      abstractTD_ATG0.set_abstracttorealMonitoredFunction_fromDomain_value1(double0);
      char char0 = 'd';
      abstractTD_ATG0.set_abstracttocharMonitoredFunction_fromDomain_value1(char0);
      abstractTD_ATG0.set_abstracttoenumMonitoredFunction_fromDomain_value1(EnumDomain.STATE1);
      String string3 = "another1";
      abstractTD_ATG0.set_abstract_abstracttoabstractMonitoredFunction_fromDomain_value1(string3);
      int int3 = 5;
      abstractTD_ATG0.set_abstracttoconcreteMonitoredFunction_fromDomain_value2(int3);
      abstractTD_ATG0.set_abstracttoconcreteMonitoredFunction_fromDomain_value1(int1);

  }
}
