/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 20 18:00:34 GMT 2025
 */

package domaintests;

import org.junit.Test;
import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SequenceDomain_ATG_ESTest extends SequenceDomain_ATG_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SequenceDomain_ATG sequenceDomain_ATG0 = new SequenceDomain_ATG();
      assertNotNull(sequenceDomain_ATG0);
      
      String string0 = sequenceDomain_ATG0.get_seqAbstractControlledFunction();
      assertEquals("[value1, value2]", string0);
      String string1 = sequenceDomain_ATG0.get_seqEnumControlledFunction();
      assertEquals("[STATE1, STATE2]", string1);
      String string2 = sequenceDomain_ATG0.get_seqStringControlledFunction();
      assertEquals("[Hello,  , world, !]", string2);
      String string3 = sequenceDomain_ATG0.get_seqBooleanControlledFunction();
      assertEquals("[true, false]", string3);
      String string4 = sequenceDomain_ATG0.get_seqIntegerControlledFunction();
      assertEquals("[2, 2]", string4);
      String string5 = sequenceDomain_ATG0.get_seqRealControlledFunction();
      assertEquals("[5.5, 2.2, 7.6]", string5);
      String string6 = sequenceDomain_ATG0.get_seqCharControlledFunction();
      assertEquals("[a, b, c]", string6);

      sequenceDomain_ATG0.step();

      assertEquals("[value1, value2]", sequenceDomain_ATG0.get_seqAbstractControlledFunction());
      assertEquals("[STATE1, STATE2]", sequenceDomain_ATG0.get_seqEnumControlledFunction());
      assertEquals("[Hello,  , world, !]", sequenceDomain_ATG0.get_seqStringControlledFunction());
      assertEquals("[true, false]", sequenceDomain_ATG0.get_seqBooleanControlledFunction());
      assertEquals("[2, 2]", sequenceDomain_ATG0.get_seqIntegerControlledFunction());
      assertEquals("[5.5, 2.2, 7.6]", sequenceDomain_ATG0.get_seqRealControlledFunction());
      assertEquals("[a, b, c]", sequenceDomain_ATG0.get_seqCharControlledFunction());

      sequenceDomain_ATG0.step();

      sequenceDomain_ATG0.set_sequence_seqIntegerMonitoredFunction("[1,2,3]");
      sequenceDomain_ATG0.set_sequence_seqStringMonitoredFunction("[Hello,world!]");
      sequenceDomain_ATG0.set_sequence_seqBooleanMonitoredFunction("[true, false]");
      sequenceDomain_ATG0.set_sequence_seqRealMonitoredFunction("[1.1, 2.2, 3.3]");
      sequenceDomain_ATG0.set_sequence_seqCharMonitoredFunction("[a,e,i,o,u]");
      sequenceDomain_ATG0.set_sequence_seqEnumMonitoredFunction("[STATE1,STATE2]");
      sequenceDomain_ATG0.set_sequence_seqAbstractMonitoredFunction("[value1,value2]");

      sequenceDomain_ATG0.step();

      sequenceDomain_ATG0.set_sequence_seqIntegerMonitoredFunction("1,2,3");
      sequenceDomain_ATG0.set_sequence_seqStringMonitoredFunction("Hello,world!");
      sequenceDomain_ATG0.set_sequence_seqBooleanMonitoredFunction("true, false");
      sequenceDomain_ATG0.set_sequence_seqRealMonitoredFunction("1.1, 2.2, 3.3");
      sequenceDomain_ATG0.set_sequence_seqCharMonitoredFunction("a,e,i,o,u");
      sequenceDomain_ATG0.set_sequence_seqEnumMonitoredFunction("STATE1,STATE2");
      sequenceDomain_ATG0.set_sequence_seqAbstractMonitoredFunction("value1,value2");

  }
}
