# MODELS AND COMPOSITION

M1.RUNTIME_MODEL_PATH=resources/models/incDec/asmMulti.asm
M2.RUNTIME_MODEL_PATH=resources/models/incDec/asmIncPipe.asm
M3.RUNTIME_MODEL_PATH=resources/models/incDec/asmDecPipe.asm

setup.setup_comp= M1 | (M2 || M3)

#COMMONS
common.HOST=127.0.0.1

# M1 CONFIGURATION
M1.ZMQ_PUB_SOCKET=tcp://*:5556
M1.ASM_ENVIRONMENT_FUNCTIONS=myinput
M1.ASM_ENVIRONMENT_ADDRESS=tcp://127.0.0.1:5563


# M2 CONFIGURATION
M2.ZMQ_SUB_CONNECT_ADDRESSES=tcp://127.0.0.1:5556
M2.ZMQ_PUB_SOCKET=tcp://*:5557
M2.ASM_SUB_FUNCTIONS=funcInc


# M3 CONFIGURATION
M3.ZMQ_SUB_CONNECT_ADDRESSES=tcp://127.0.0.1:5556
M3.ZMQ_PUB_SOCKET=tcp://*:5558
M3.ASM_SUB_FUNCTIONS=funcDec
# ENVIRONMENT
environment.address=tcp://*:5563
# ms pause between sends
environment.pause=3000
environment.env_functions=myinput

# each key = a topic name, value = list of message-values
environment.myinput = 2,3,4
