package org.asmeta.xt.tests.parsing.positive;

import org.asmeta.xt.asmetal.Asm;
import org.asmeta.xt.asmetal.Domain;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.InputOutput;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

@SuppressWarnings("all")
public class AbstractAndAgentDomain extends ParserTest {
  @Test
  public void test1() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("asm blankpage");
    _builder.newLine();
    _builder.append("signature: ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("abstract domain Agent");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("abstract domain Student");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("basic domain Integer");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("static x : Student -> Integer");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("definitions: ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("function x($x in Student) = 4");
    _builder.newLine();
    Asm result = this.test(_builder.toString(), "blankpage");
    Assertions.assertEquals(0, result.getHeaderSection().getImportClause().size());
    Assertions.assertEquals(null, result.getHeaderSection().getExportClause());
    Assertions.assertEquals(3, result.getHeaderSection().getSignature().getDomain().size());
    InputOutput.<Class<? extends Domain>>println(result.getHeaderSection().getSignature().getDomain().get(0).getClass());
    InputOutput.<Class<? extends Domain>>println(result.getHeaderSection().getSignature().getDomain().get(1).getClass());
  }

  @Test
  public void testCashPoint() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("asm CashPoint");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import StandardLibrary");
    _builder.newLine();
    _builder.newLine();
    _builder.append("signature:");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("// domains");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("abstract domain Account  ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("abstract domain Card");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("abstract domain Till");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("abstract domain Date");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("//domain CashAmount subsetof Integer");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("enum domain TillState = { WAITCARD | WAITPIN | VALIDPIN}");
    _builder.newLine();
    _builder.append("        ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("controlled tillState : Till -> TillState");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("//   controlled balance : Account -> CashAmount");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("controlled balance : Account -> Integer");
    _builder.newLine();
    _builder.append(" ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("controlled legalCard: Card -> Boolean");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("controlled daily_withdraw_sum : Card -> Integer");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("controlled insertedCard : Till -> Card");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("monitored enteredPin: Till -> Integer");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("monitored amount : Till -> Integer");
    _builder.newLine();
    _builder.append("      ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("static withdrawLimit: Integer");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("static encodedPin : Card -> Integer");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("static cardAccount : Card -> Account");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("// current date != date stored in the card");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("monitored currentDate : Date");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("controlled cardLastUseDate : Card -> Date");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("derived stableState: Boolean");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("static card1: Card");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("static card2: Card");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("static till1 : Till");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("static account1 : Account");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("static monday : Date");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("static tuesday : Date");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("definitions:");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("//  \tdomain CashAmount = {-100 : 100}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("   \t");
    _builder.append("function encodedPin($c in Card) =");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("switch($c)");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("case card1 : 1");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("case card2 : 2");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("endswitch");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   \t");
    _builder.append("function cardAccount($c in Card) =");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("switch($c)");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("case card1 : account1");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("case card2 : account1");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("endswitch");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("function withdrawLimit = 1000");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    \t\t\t\t");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("// try to insert card $c in till $t");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("rule r_insertedCard($t in Till, $c in Card) =");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("if tillState($t) = WAITCARD then");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("par");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("tillState($t) := WAITPIN");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("insertedCard($t) := $c");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("endpar");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("endif ");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("   \t");
    _builder.append("rule r_insertCard($t in Till) = ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("choose $c in Card with true do r_insertedCard[$t,$c]   ");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("rule r_enterPin($t in Till) =");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("if tillState($t) = WAITPIN then");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("if legalCard(insertedCard($t)) then");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if enteredPin($t) = encodedPin(insertedCard($t)) then");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("par");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if cardLastUseDate(insertedCard($t)) != currentDate then");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("par");
    _builder.newLine();
    _builder.append("            \t");
    _builder.append("// reset the new daily amount sum");
    _builder.newLine();
    _builder.append("            \t");
    _builder.append("daily_withdraw_sum(insertedCard($t)) := 0");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("cardLastUseDate(insertedCard($t)) := currentDate");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("endpar");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("endif");
    _builder.newLine();
    _builder.append("        \t");
    _builder.append("tillState($t) := VALIDPIN");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("endpar");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("endif");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("endif");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("endif");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("rule r_validPin($t in Till) =");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("if tillState($t) = VALIDPIN then");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("// witdraw");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("let ($acc =  cardAccount(insertedCard($t))) in");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("// withdraw");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("if amount($t) > 0 and ");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("amount($t) <= balance($acc) and");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("daily_withdraw_sum(insertedCard($t)) < withdrawLimit - amount($t)then");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("par");
    _builder.newLine();
    _builder.append("\t          \t");
    _builder.append("balance($acc) := balance($acc) - amount($t)");
    _builder.newLine();
    _builder.append("\t          \t");
    _builder.append("daily_withdraw_sum(insertedCard($t)) := daily_withdraw_sum(insertedCard($t)) - amount($t)  ");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("endpar");
    _builder.newLine();
    _builder.append("\t     ");
    _builder.append("endif");
    _builder.newLine();
    _builder.append("\t     ");
    _builder.append("endlet");
    _builder.newLine();
    _builder.append("\t   ");
    _builder.append("endif");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("invariant inv_b0 over balance: (forall $a in Account with (balance($a) > 0))");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("main rule r_main =");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("choose $till in Till with true do //not necessary");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("par");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("r_insertCard[$till]");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("r_enterPin[$till]");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("r_validPin[$till]");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("endpar");
    _builder.newLine();
    _builder.newLine();
    _builder.append("default init s_0:");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("function tillState($m in Till) = WAITCARD");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("function legalCard($m in Card) = true");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("function balance($a in Account) = chooseone({1000,2000,3000})");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("function daily_withdraw_sum($c in Card) = 0");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("function cardLastUseDate($c in Card) = monday");
    _builder.newLine();
    Asm result = this.test(_builder.toString(), "CashPoint");
    Assertions.assertEquals(1, result.getHeaderSection().getImportClause().size());
    Assertions.assertEquals(null, result.getHeaderSection().getExportClause());
    Assertions.assertEquals(5, result.getHeaderSection().getSignature().getDomain().size());
    InputOutput.<Class<? extends Domain>>println(result.getHeaderSection().getSignature().getDomain().get(0).getClass());
    InputOutput.<Class<? extends Domain>>println(result.getHeaderSection().getSignature().getDomain().get(1).getClass());
    InputOutput.<Class<? extends Domain>>println(result.getHeaderSection().getSignature().getDomain().get(2).getClass());
    InputOutput.<Class<? extends Domain>>println(result.getHeaderSection().getSignature().getDomain().get(3).getClass());
    InputOutput.<Class<? extends Domain>>println(result.getHeaderSection().getSignature().getDomain().get(4).getClass());
  }
}
