/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package asmeta.definitions.validation;

import org.eclipse.emf.common.util.EList;

import asmeta.definitions.Function;
import asmeta.definitions.RuleDeclaration;
import asmeta.definitions.domains.Domain;
import asmeta.terms.basicterms.Term;

/**
 * A sample validator interface for {@link asmeta.definitions.Axiom}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AxiomValidator {
	boolean validate();

	boolean validateConstrainedDomain(EList<Domain> value);
	boolean validateBody(Term value);
	boolean validateConstrainedRule(EList<RuleDeclaration> value);
	boolean validateConstrainedFunction(EList<Function> value);
}
