package org.asmeta.xt.tests.parsing.positive;

import com.google.inject.Inject;
import org.asmeta.xt.asmetal.Asm;
import org.asmeta.xt.asmetal.Domain;
import org.asmeta.xt.asmetal.DomainDefinition;
import org.asmeta.xt.asmetal.Expression;
import org.asmeta.xt.asmetal.FairnessConstraint;
import org.asmeta.xt.asmetal.Function;
import org.asmeta.xt.asmetal.FunctionDefinition;
import org.asmeta.xt.asmetal.Invariant;
import org.asmeta.xt.asmetal.InvariantConstraint;
import org.asmeta.xt.asmetal.Property;
import org.asmeta.xt.asmetal.Term;
import org.asmeta.xt.asmetal.impl.AbstractTDImpl;
import org.asmeta.xt.asmetal.impl.BinaryOperationImpl;
import org.asmeta.xt.asmetal.impl.CaseTermImpl;
import org.asmeta.xt.asmetal.impl.CompassionConstraintImpl;
import org.asmeta.xt.asmetal.impl.ConcreteDomainImpl;
import org.asmeta.xt.asmetal.impl.CtlSpecImpl;
import org.asmeta.xt.asmetal.impl.DerivedFunctionImpl;
import org.asmeta.xt.asmetal.impl.EnumTermImpl;
import org.asmeta.xt.asmetal.impl.ExpressionImpl;
import org.asmeta.xt.asmetal.impl.FunctionTermImpl;
import org.asmeta.xt.asmetal.impl.IntegerTermImpl;
import org.asmeta.xt.asmetal.impl.InvariantConstraintImpl;
import org.asmeta.xt.asmetal.impl.InvariantImpl;
import org.asmeta.xt.asmetal.impl.JusticeConstraintImpl;
import org.asmeta.xt.asmetal.impl.LtlSpecImpl;
import org.asmeta.xt.asmetal.impl.SetTermImpl;
import org.asmeta.xt.asmetal.impl.StaticFunctionImpl;
import org.asmeta.xt.asmetal.impl.VariableTermImpl;
import org.asmeta.xt.tests.AsmParseHelper;
import org.asmeta.xt.tests.AsmetaLInjectorProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(AsmetaLInjectorProvider.class)
@SuppressWarnings("all")
public class BodyParsingTest {
  @Inject
  private AsmParseHelper parseHelper;

  @Inject
  @Extension
  private ValidationTestHelper _validationTestHelper;

  @Test
  public void testDomainFunctionDefinitions() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm domain_function");
      _builder.newLine();
      _builder.newLine();
      _builder.append("//import StandardLibrary(Integer, Any)");
      _builder.newLine();
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("basic domain Integer");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("anydomain Any");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("abstract domain Philosopher");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain NumOfCherries subsetof Integer");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static leftNeighbour: Philosopher -> Philosopher");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static rightNeighbour: Philosopher -> Philosopher");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static philo1: Philosopher");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static philo2: Philosopher");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static philo3: Philosopher");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static philo4: Philosopher");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static philo5: Philosopher");
      _builder.newLine();
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain NumOfCherries = {0 : 3}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("function leftNeighbour($p in Philosopher) =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("switch($p)");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("case philo1: philo5");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("case philo2: philo1");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("case philo3: philo2");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("case philo4: philo3");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("case philo5: philo4");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("endswitch");
      _builder.newLine();
      Asm result = this.parseHelper.parse(_builder, "domain_function");
      this._validationTestHelper.assertNoErrors(result);
      int i = 2;
      Assert.assertEquals(4, result.getHeaderSection().getSignature().getDomain().size());
      Assert.assertEquals(7, result.getHeaderSection().getSignature().getFunction().size());
      Domain abstr_dom = result.getHeaderSection().getSignature().getDomain().get(i);
      Assert.assertEquals("Philosopher", abstr_dom.getName());
      Assert.assertEquals(AbstractTDImpl.class, abstr_dom.getClass());
      i++;
      Domain conc_dom = result.getHeaderSection().getSignature().getDomain().get(i);
      Assert.assertEquals("NumOfCherries", conc_dom.getName());
      Assert.assertEquals(ConcreteDomainImpl.class, conc_dom.getClass());
      Assert.assertEquals("Integer", ((ConcreteDomainImpl) conc_dom).getTypeDomain().getName());
      i = 0;
      Function func = null;
      func = result.getHeaderSection().getSignature().getFunction().get(i);
      Assert.assertEquals(DerivedFunctionImpl.class, func.getClass());
      Assert.assertEquals("leftNeighbour", func.getName());
      Assert.assertEquals("Philosopher", func.getCodomain().getName());
      Assert.assertEquals("Philosopher", func.getDomain().getName());
      i++;
      func = result.getHeaderSection().getSignature().getFunction().get(i);
      Assert.assertEquals(DerivedFunctionImpl.class, func.getClass());
      Assert.assertEquals("rightNeighbour", func.getName());
      Assert.assertEquals("Philosopher", func.getCodomain().getName());
      Assert.assertEquals("Philosopher", func.getDomain().getName());
      i++;
      func = result.getHeaderSection().getSignature().getFunction().get(i);
      Assert.assertEquals(StaticFunctionImpl.class, func.getClass());
      Assert.assertEquals("philo1", func.getName());
      Assert.assertEquals("Philosopher", func.getCodomain().getName());
      Assert.assertEquals(null, func.getDomain());
      i++;
      func = result.getHeaderSection().getSignature().getFunction().get(i);
      Assert.assertEquals(StaticFunctionImpl.class, func.getClass());
      Assert.assertEquals("philo2", func.getName());
      Assert.assertEquals("Philosopher", func.getCodomain().getName());
      Assert.assertEquals(null, func.getDomain());
      i++;
      func = result.getHeaderSection().getSignature().getFunction().get(i);
      Assert.assertEquals(StaticFunctionImpl.class, func.getClass());
      Assert.assertEquals("philo3", func.getName());
      Assert.assertEquals("Philosopher", func.getCodomain().getName());
      Assert.assertEquals(null, func.getDomain());
      i++;
      func = result.getHeaderSection().getSignature().getFunction().get(i);
      Assert.assertEquals(StaticFunctionImpl.class, func.getClass());
      Assert.assertEquals("philo4", func.getName());
      Assert.assertEquals("Philosopher", func.getCodomain().getName());
      Assert.assertEquals(null, func.getDomain());
      i++;
      func = result.getHeaderSection().getSignature().getFunction().get(i);
      Assert.assertEquals(StaticFunctionImpl.class, func.getClass());
      Assert.assertEquals("philo5", func.getName());
      Assert.assertEquals("Philosopher", func.getCodomain().getName());
      Assert.assertEquals(null, func.getDomain());
      Assert.assertEquals(1, result.getBodySection().getDomainDefinition().size());
      Assert.assertEquals(1, result.getBodySection().getFunctionDefinition().size());
      i = 0;
      DomainDefinition dom_def = result.getBodySection().getDomainDefinition().get(0);
      Assert.assertEquals("NumOfCherries", dom_def.getDefinedDomainName());
      Assert.assertEquals(SetTermImpl.class, dom_def.getBody().getClass());
      Term _body = dom_def.getBody();
      SetTermImpl seq_term = ((SetTermImpl) _body);
      Assert.assertEquals(IntegerTermImpl.class, seq_term.getStart_term().getClass());
      Assert.assertEquals(IntegerTermImpl.class, seq_term.getEnd_term().getClass());
      Term _end_term = seq_term.getEnd_term();
      IntegerTermImpl val_term = ((IntegerTermImpl) _end_term);
      Assert.assertEquals("3", val_term.getSymbol());
      i = 0;
      FunctionDefinition func_def = result.getBodySection().getFunctionDefinition().get(i);
      Assert.assertEquals("leftNeighbour", func_def.getDefinedFunctionName());
      Assert.assertEquals(1, func_def.getVariables().size());
      Assert.assertEquals("$p", func_def.getVariables().get(0));
      Assert.assertEquals(1, func_def.getDomain().size());
      Assert.assertEquals("Philosopher", func_def.getDomain().get(0).getName());
      Assert.assertEquals(CaseTermImpl.class, func_def.getBody().getClass());
      Term _body_1 = func_def.getBody();
      CaseTermImpl switch_term = ((CaseTermImpl) _body_1);
      Assert.assertEquals(VariableTermImpl.class, switch_term.getComparedTerm().getClass());
      Term _comparedTerm = switch_term.getComparedTerm();
      Assert.assertEquals("$p", ((VariableTermImpl) _comparedTerm).getName());
      Assert.assertEquals(5, switch_term.getComparingTerm().size());
      Assert.assertEquals(5, switch_term.getResultTerms().size());
      Assert.assertEquals(null, switch_term.getOtherwiseTerm());
      Assert.assertEquals(FunctionTermImpl.class, switch_term.getComparingTerm().get(0).getClass());
      Term _get = switch_term.getComparingTerm().get(0);
      FunctionTermImpl func_term = ((FunctionTermImpl) _get);
      Assert.assertEquals("philo1", func_term.getFunctionName());
      Assert.assertEquals(FunctionTermImpl.class, switch_term.getComparingTerm().get(0).getClass());
      Term _get_1 = switch_term.getResultTerms().get(0);
      func_term = ((FunctionTermImpl) _get_1);
      Assert.assertEquals("philo5", func_term.getFunctionName());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void testInvariant() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm invariant_asm");
      _builder.newLine();
      _builder.newLine();
      _builder.append("import StandardLibrary");
      _builder.newLine();
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("enum domain Side = {LEFT | RIGHT}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("enum domain Actors = {FERRYMAN | GO | CA | WO}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic controlled position: Actors -> Side");
      _builder.newLine();
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("//Se la capra (GO) e il cavolo (CA) sono sulla stessa sponda, allora deve essere presente anche il FERRYMAN");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("invariant over position: position(GO)=position(CA) implies position(GO)=position(FERRYMAN)");
      _builder.newLine();
      Asm result = this.parseHelper.parse(_builder, "invariant_asm");
      this._validationTestHelper.assertNoErrors(result);
      int i = 0;
      Assert.assertEquals(1, result.getBodySection().getProperty().size());
      Assert.assertEquals(InvariantImpl.class, result.getBodySection().getProperty().get(i).getClass());
      Property _get = result.getBodySection().getProperty().get(i);
      Invariant inv = ((Invariant) _get);
      Assert.assertEquals(null, inv.getName());
      Assert.assertEquals(1, inv.getInvar_list().size());
      Assert.assertEquals("position", inv.getInvar_list().get(0).getConstrainedName());
      Term _body = inv.getBody();
      BinaryOperationImpl e1 = ((BinaryOperationImpl) _body);
      Assert.assertEquals("implies", e1.getOp());
      Assert.assertEquals(BinaryOperationImpl.class, e1.getRight().getClass());
      Assert.assertEquals(BinaryOperationImpl.class, e1.getLeft().getClass());
      Expression _left = e1.getLeft();
      BinaryOperationImpl e1_left = ((BinaryOperationImpl) _left);
      Assert.assertEquals("=", e1_left.getOp());
      Assert.assertEquals(FunctionTermImpl.class, e1_left.getLeft().getClass());
      Expression _left_1 = e1_left.getLeft();
      FunctionTermImpl func = ((FunctionTermImpl) _left_1);
      Assert.assertEquals("position", func.getFunctionName());
      Assert.assertEquals(1, func.getArguments().getTerms().size());
      Assert.assertEquals(EnumTermImpl.class, func.getArguments().getTerms().get(0).getClass());
      Term _get_1 = func.getArguments().getTerms().get(0);
      EnumTermImpl enum_ = ((EnumTermImpl) _get_1);
      Assert.assertEquals("GO", enum_.getSymbol());
      Expression _right = e1_left.getRight();
      func = ((FunctionTermImpl) _right);
      Assert.assertEquals("position", func.getFunctionName());
      Assert.assertEquals(1, func.getArguments().getTerms().size());
      Assert.assertEquals(EnumTermImpl.class, func.getArguments().getTerms().get(0).getClass());
      Term _get_2 = func.getArguments().getTerms().get(0);
      enum_ = ((EnumTermImpl) _get_2);
      Assert.assertEquals("CA", enum_.getSymbol());
      Expression _right_1 = e1.getRight();
      BinaryOperationImpl e1_right = ((BinaryOperationImpl) _right_1);
      Assert.assertEquals("=", e1_right.getOp());
      Assert.assertEquals(FunctionTermImpl.class, e1_left.getLeft().getClass());
      Expression _left_2 = e1_right.getLeft();
      func = ((FunctionTermImpl) _left_2);
      Assert.assertEquals("position", func.getFunctionName());
      Assert.assertEquals(1, func.getArguments().getTerms().size());
      Assert.assertEquals(EnumTermImpl.class, func.getArguments().getTerms().get(0).getClass());
      Term _get_3 = func.getArguments().getTerms().get(0);
      enum_ = ((EnumTermImpl) _get_3);
      Assert.assertEquals("GO", enum_.getSymbol());
      Expression _right_2 = e1_right.getRight();
      func = ((FunctionTermImpl) _right_2);
      Assert.assertEquals("position", func.getFunctionName());
      Assert.assertEquals(1, func.getArguments().getTerms().size());
      Assert.assertEquals(EnumTermImpl.class, func.getArguments().getTerms().get(0).getClass());
      Term _get_4 = func.getArguments().getTerms().get(0);
      enum_ = ((EnumTermImpl) _get_4);
      Assert.assertEquals("FERRYMAN", enum_.getSymbol());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  public void testTemporalProperty() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm temporal_pro");
      _builder.newLine();
      _builder.append("import LTLlibrary");
      _builder.newLine();
      _builder.append("import CTLlibrary");
      _builder.newLine();
      _builder.newLine();
      _builder.append("signature:\t\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain AgentDomain subsetof Agent");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain AgentDomainEnv subsetof Agent");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain Line subsetof Integer");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("enum domain State = { EXCLUSIVE | SHARED | INVALID}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static l1: Line");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("controlled ccState: Prod(AgentDomain, Line) -> State");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static a1: AgentDomain");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static a2: AgentDomain");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static ee: AgentDomainEnv");
      _builder.newLine();
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain Line = {1}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain AgentDomain = {a1, a2}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("function a1 = a1");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("function a2 = a2");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("//proprieta\' LTL");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("LTLSPEC g(not( (ccState(a1, 1) = EXCLUSIVE) and (ccState(a2, 1)=EXCLUSIVE) ))");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("CTLSPEC ag(ccState(a1, 1)=INVALID and ccState(a2, 1)=INVALID)\t");
      _builder.newLine();
      Asm result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertNoErrors(result);
      int i = 0;
      Assert.assertEquals(2, result.getBodySection().getProperty().size());
      Property spec = result.getBodySection().getProperty().get(i);
      Assert.assertEquals(null, spec.getName());
      Assert.assertEquals(LtlSpecImpl.class, spec.getClass());
      Assert.assertEquals(FunctionTermImpl.class, spec.getBody().getClass());
      Term _body = spec.getBody();
      FunctionTermImpl func = ((FunctionTermImpl) _body);
      Assert.assertEquals("g", func.getFunctionName());
      Assert.assertEquals(1, func.getArguments().getTerms().size());
      Assert.assertEquals(ExpressionImpl.class, func.getArguments().getTerms().get(0).getClass());
      Term _get = func.getArguments().getTerms().get(0);
      Expression expr = ((Expression) _get);
      Assert.assertEquals("not", expr.getOp());
      Assert.assertEquals(BinaryOperationImpl.class, expr.getOperand().getClass());
      Expression _operand = expr.getOperand();
      BinaryOperationImpl func_bin = ((BinaryOperationImpl) _operand);
      Assert.assertEquals("and", func_bin.getOp());
      Assert.assertEquals(BinaryOperationImpl.class, func_bin.getLeft().getClass());
      Assert.assertEquals(BinaryOperationImpl.class, func_bin.getRight().getClass());
      Expression _left = func_bin.getLeft();
      BinaryOperationImpl func_bin_left = ((BinaryOperationImpl) _left);
      Assert.assertEquals("=", func_bin_left.getOp());
      Assert.assertEquals(FunctionTermImpl.class, func_bin_left.getLeft().getClass());
      Assert.assertEquals(EnumTermImpl.class, func_bin_left.getRight().getClass());
      Expression _left_1 = func_bin_left.getLeft();
      FunctionTermImpl func_bin_left_left = ((FunctionTermImpl) _left_1);
      Assert.assertEquals("ccState", func_bin_left_left.getFunctionName());
      Assert.assertEquals(2, func_bin_left_left.getArguments().getTerms().size());
      Assert.assertEquals(EnumTermImpl.class, func_bin_left.getRight().getClass());
      Assert.assertEquals(FunctionTermImpl.class, func_bin_left_left.getArguments().getTerms().get(0).getClass());
      Term _get_1 = func_bin_left_left.getArguments().getTerms().get(0);
      func = ((FunctionTermImpl) _get_1);
      Assert.assertEquals("a1", func.getFunctionName());
      Assert.assertEquals(IntegerTermImpl.class, func_bin_left_left.getArguments().getTerms().get(1).getClass());
      Term _get_2 = func_bin_left_left.getArguments().getTerms().get(1);
      IntegerTermImpl number = ((IntegerTermImpl) _get_2);
      Assert.assertEquals("1", number.getSymbol());
      Expression _right = func_bin_left.getRight();
      EnumTermImpl func_bin_left_right = ((EnumTermImpl) _right);
      Assert.assertEquals("EXCLUSIVE", func_bin_left_right.getSymbol());
      Expression _right_1 = func_bin.getRight();
      BinaryOperationImpl func_bin_right = ((BinaryOperationImpl) _right_1);
      Assert.assertEquals("=", func_bin_right.getOp());
      Assert.assertEquals(FunctionTermImpl.class, func_bin_right.getLeft().getClass());
      Assert.assertEquals(EnumTermImpl.class, func_bin_right.getRight().getClass());
      Expression _left_2 = func_bin_right.getLeft();
      FunctionTermImpl func_bin_right_left = ((FunctionTermImpl) _left_2);
      Assert.assertEquals("ccState", func_bin_right_left.getFunctionName());
      Assert.assertEquals(2, func_bin_right_left.getArguments().getTerms().size());
      Assert.assertEquals(EnumTermImpl.class, func_bin_right.getRight().getClass());
      Assert.assertEquals(FunctionTermImpl.class, func_bin_right_left.getArguments().getTerms().get(0).getClass());
      Term _get_3 = func_bin_right_left.getArguments().getTerms().get(0);
      func = ((FunctionTermImpl) _get_3);
      Assert.assertEquals("a2", func.getFunctionName());
      Assert.assertEquals(IntegerTermImpl.class, func_bin_right_left.getArguments().getTerms().get(1).getClass());
      Term _get_4 = func_bin_right_left.getArguments().getTerms().get(1);
      number = ((IntegerTermImpl) _get_4);
      Assert.assertEquals("1", number.getSymbol());
      Expression _right_2 = func_bin_right.getRight();
      EnumTermImpl func_bin_right_right = ((EnumTermImpl) _right_2);
      Assert.assertEquals("EXCLUSIVE", func_bin_right_right.getSymbol());
      i++;
      spec = result.getBodySection().getProperty().get(i);
      Assert.assertEquals(null, spec.getName());
      Assert.assertEquals(CtlSpecImpl.class, spec.getClass());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void testInvarFairness() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm fairness");
      _builder.newLine();
      _builder.append("import StandardLibrary");
      _builder.newLine();
      _builder.append("signature: ");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("definitions: ");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("INVAR 5 > 6");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("JUSTICE 5 > 6");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("COMPASSION(  5 > 6, 5 > 6 )");
      _builder.newLine();
      Asm result = this.parseHelper.parse(_builder, "fairness");
      this._validationTestHelper.assertNoErrors(result);
      int i = 0;
      Assert.assertEquals(1, result.getBodySection().getInvariantConstraint().size());
      Assert.assertEquals(2, result.getBodySection().getFairnessConstraint().size());
      Assert.assertEquals(InvariantConstraintImpl.class, result.getBodySection().getInvariantConstraint().get(i).getClass());
      InvariantConstraint _get = result.getBodySection().getInvariantConstraint().get(i);
      InvariantConstraintImpl invar = ((InvariantConstraintImpl) _get);
      i = 0;
      Assert.assertEquals(JusticeConstraintImpl.class, result.getBodySection().getFairnessConstraint().get(i).getClass());
      FairnessConstraint _get_1 = result.getBodySection().getFairnessConstraint().get(i);
      JusticeConstraintImpl justice = ((JusticeConstraintImpl) _get_1);
      i++;
      Assert.assertEquals(CompassionConstraintImpl.class, result.getBodySection().getFairnessConstraint().get(i).getClass());
      FairnessConstraint _get_2 = result.getBodySection().getFairnessConstraint().get(i);
      CompassionConstraintImpl compassion = ((CompassionConstraintImpl) _get_2);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
