@echo off
setlocal enabledelayedexpansion

:: Env file
set "ENV_FILE=..\.env"

:: CLI options
set "ARG_ASMETAL2JAVA_INPUT=-input"
set "ARG_ASMETAL2JAVA_WORKING_DIR=-workingDir"
set "ARG_ASMETAL2JAVA_OUTPUT=-output"
set "ARG_ASMETAL2JAVA_MODE=-mode"
set "ARG_ASMETAL2JAVA_COMPILER_VERSION=-compilerVersion"
set "ARG_ASMETAL2JAVA_CLEAN=-clean"
set "ARG_ASMETAL2JAVA_PROPERTIES="
set "ARG_ASMETAL2JAVA_HELP=-help"
set "ARG_EVOSUITE_VERSION="
set "ARG_EVOSUITE_JAVA_VERSION="
set "ARG_EVOSUITE_TARGET=-target"
set "ARG_EVOSUITE_CLASS=-class"
set "ARG_EVOSUITE_CRITERION=-criterion"
set "ARG_EVOSUITE_SEARCH_BUDGET=-Dsearch_budget="
set "ARG_EVOSUITE_PROPERTIES="
set "ARG_JUNIT2AVALLA_INPUT=-input"
set "ARG_JUNIT2AVALLA_WORKING_DIR=-workingDir"
set "ARG_JUNIT2AVALLA_OUTPUT=-output"
set "ARG_JUNIT2AVALLA_PARSER=-parser"
set "ARG_JUNIT2AVALLA_CLEAN=-clean"
set "ARG_JUNIT2AVALLA_HELP=-help"

:: Set the fileName parameter
set "ASMFILE="
set "JAVACLASSFILE="
set "JUNITFILE"="
if NOT "%1"=="" (
    set "ASMFILE=./input/%1"
    set "ASMETAL2JAVA_INPUT=!ARG_ASMETAL2JAVA_INPUT! "!ASMFILE!""
    set "JAVACLASSFILE=%~n1_ATG"
    set "EVOSUITE_CLASS=!ARG_EVOSUITE_CLASS! !JAVACLASSFILE!"
    set "JUNITFILE=!JAVACLASSFILE!_ESTest.java"
    set "JUNIT2AVALLA_INPUT=!ARG_JUNIT2AVALLA_INPUT! ./evosuite/evosuite-tests/!JUNITFILE!"
)

:: Default values for each parameter
set "DEFAULT_ASMETAL2JAVA_INPUT=%ASMFILE%"
set "DEFAULT_ASMETAL2JAVA_WORKING_DIR=./input"
set "DEFAULT_ASMETAL2JAVA_OUTPUT=./output"
set "DEFAULT_ASMETAL2JAVA_MODE=testGen"
set "DEFAULT_ASMETAL2JAVA_COMPILER_VERSION=8"
set "DEFAULT_ASMETAL2JAVA_CLEAN="
set "DEFAULT_ASMETAL2JAVA_PROPERTIES=-DcopyAsm=true -DignoreDomainException=true"
set "DEFAULT_ASMETAL2JAVA_HELP="
set "DEFAULT_EVOSUITE_VERSION=1.0.6"
set "DEFAULT_EVOSUITE_JAVA_VERSION=8"
set "DEFAULT_EVOSUITE_TARGET=./evosuite-target"
set "DEFAULT_EVOSUITE_CLASS=%JAVACLASSFILE%"
set "DEFAULT_EVOSUITE_CRITERION=LINE:BRANCH"
set "DEFAULT_EVOSUITE_SEARCH_BUDGET=15"
set "DEFAULT_EVOSUITE_PROPERTIES=-Dtest_dir=./evosuite-tests -Dminimize=true -Dassertion_strategy=all -Dreport_dir=./evosuite-report"
set "DEFAULT_JUNIT2AVALLA_INPUT=./evosuite/evosuite-tests/%JUNITFILE%"
set "DEFAULT_JUNIT2AVALLA_WORKING_DIR=./input"
set "DEFAULT_JUNIT2AVALLA_OUTPUT=./output"
set "DEFAULT_JUNIT2AVALLA_PARSER=customParser"
set "DEFAULT_JUNIT2AVALLA_CLEAN="
set "DEFAULT_JUNIT2AVALLA_HELP=-help"

:: Load values from .env file if it exists
if exist "%ENV_FILE%" (
	echo loading pre-existing configurations
    for /F "usebackq tokens=1,* delims==" %%A in ("%ENV_FILE%") do (
        if /I "%%A"=="ASMETAL2JAVA_WORKING_DIR" set "ASMETAL2JAVA_WORKING_DIR=%%B"
        if /I "%%A"=="ASMETAL2JAVA_OUTPUT" set "ASMETAL2JAVA_OUTPUT=%%B"
        if /I "%%A"=="ASMETAL2JAVA_MODE" set "ASMETAL2JAVA_MODE=%%B"
        if /I "%%A"=="ASMETAL2JAVA_COMPILER_VERSION" set "ASMETAL2JAVA_COMPILER_VERSION=%%B"
        if /I "%%A"=="ASMETAL2JAVA_CLEAN" set "ASMETAL2JAVA_CLEAN=%%B"
        if /I "%%A"=="ASMETAL2JAVA_PROPERTIES" set "ASMETAL2JAVA_PROPERTIES=%%B"
        if /I "%%A"=="ASMETAL2JAVA_HELP" set "ASMETAL2JAVA_HELP=%%B"
        if /I "%%A"=="EVOSUITE_VERSION" set "EVOSUITE_VERSION=%%B"
        if /I "%%A"=="EVOSUITE_JAVA_VERSION" set "EVOSUITE_JAVA_VERSION=%%B"
        if /I "%%A"=="EVOSUITE_TARGET" set "EVOSUITE_TARGET=%%B"
        if /I "%%A"=="EVOSUITE_CRITERION" set "EVOSUITE_CRITERION=%%B"
        if /I "%%A"=="EVOSUITE_SEARCH_BUDGET" set "EVOSUITE_SEARCH_BUDGET=%%B"
        if /I "%%A"=="EVOSUITE_PROPERTIES" set "EVOSUITE_PROPERTIES=%%B"
        if /I "%%A"=="JUNIT2AVALLA_WORKING_DIR" set "JUNIT2AVALLA_WORKING_DIR=%%B"
        if /I "%%A"=="JUNIT2AVALLA_OUTPUT" set "JUNIT2AVALLA_OUTPUT=%%B"
        if /I "%%A"=="JUNIT2AVALLA_PARSER" set "JUNIT2AVALLA_PARSER=%%B"
        if /I "%%A"=="JUNIT2AVALLA_CLEAN" set "JUNIT2AVALLA_CLEAN=%%B"
        if /I "%%A"=="JUNIT2AVALLA_HELP" set "JUNIT2AVALLA_HELP=%%B"
    )
) else (
	echo generating a new configuration with default values
	goto RESET_DEFAULTS
)

:MENU
echo ================================
echo   Current Configuration:
echo ================================
if defined ASMETAL2JAVA_INPUT (echo 1.  ASMETAL2JAVA_INPUT:             %ASMETAL2JAVA_INPUT%) else (echo 1.  ASMETAL2JAVA_INPUT:             [ERROR - NOT SET])
if defined ASMETAL2JAVA_WORKING_DIR (echo 2.  ASMETAL2JAVA_WORKING_DIR:       %ASMETAL2JAVA_WORKING_DIR%) else (echo 2.  ASMETAL2JAVA_WORKING_DIR:       [NOT SET])
if defined ASMETAL2JAVA_OUTPUT (echo 3.  ASMETAL2JAVA_OUTPUT:            %ASMETAL2JAVA_OUTPUT%) else (echo 3.  ASMETAL2JAVA_OUTPUT:            [NOT SET])
if defined ASMETAL2JAVA_MODE (echo 4.  ASMETAL2JAVA_MODE:              %ASMETAL2JAVA_MODE%) else (echo 4.  ASMETAL2JAVA_MODE:              [NOT SET])
if defined ASMETAL2JAVA_COMPILER_VERSION (echo 5.  ASMETAL2JAVA_COMPILER_VERSION:  %ASMETAL2JAVA_COMPILER_VERSION%) else (echo 5.  ASMETAL2JAVA_COMPILER_VERSION:  [NOT SET])
if defined ASMETAL2JAVA_CLEAN (echo 6.  ASMETAL2JAVA_CLEAN:             %ASMETAL2JAVA_CLEAN%) else (echo 6.  ASMETAL2JAVA_CLEAN:             [NOT SET])
if defined ASMETAL2JAVA_PROPERTIES (echo 7.  ASMETAL2JAVA_PROPERTIES:       %ASMETAL2JAVA_PROPERTIES%) else (echo 7.  ASMETAL2JAVA_PROPERTIES:       [NOT SET])
if defined ASMETAL2JAVA_HELP (echo 8.  ASMETAL2JAVA_HELP:              %ASMETAL2JAVA_HELP%) else (echo 8.  ASMETAL2JAVA_HELP:              [NOT SET])                        
if defined EVOSUITE_VERSION (echo 9.  EVOSUITE_VERSION:               %EVOSUITE_VERSION%) else (echo 9.  EVOSUITE_VERSION:               [ERROR - NOT SET])
if defined EVOSUITE_JAVA_VERSION (echo 10. EVOSUITE_JAVA_VERSION:          %EVOSUITE_JAVA_VERSION%) else (echo 10. EVOSUITE_JAVA_VERSION:          [ERROR - NOT SET])
if defined EVOSUITE_TARGET (echo 11. EVOSUITE_TARGET:                %EVOSUITE_TARGET%) else (echo 11. EVOSUITE_TARGET:                [ERROR - NOT SET])
if defined EVOSUITE_CLASS (echo 12. EVOSUITE_CLASS:                 %EVOSUITE_CLASS%) else (echo 12. EVOSUITE_CLASS:                 [ERROR - NOT SET])            
if defined EVOSUITE_CRITERION (echo 13. EVOSUITE_CRITERION:             %EVOSUITE_CRITERION%) else (echo 13. EVOSUITE_CRITERION:             [NOT SET])
if defined EVOSUITE_SEARCH_BUDGET (echo 14. EVOSUITE_SEARCH_BUDGET          %EVOSUITE_SEARCH_BUDGET%) else (echo 14. EVOSUITE_SEARCH_BUDGET:         [NOT SET])
if defined EVOSUITE_PROPERTIES (echo 15. EVOSUITE_PROPERTIES:           %EVOSUITE_PROPERTIES%) else (echo 15. EVOSUITE_PROPERTIES:            [NOT SET])
if defined JUNIT2AVALLA_INPUT (echo 16. JUNIT2AVALLA_INPUT:             %JUNIT2AVALLA_INPUT%) else (echo 16. JUNIT2AVALLA_INPUT:              [NOT SET])
if defined JUNIT2AVALLA_WORKING_DIR (echo 17. JUNIT2AVALLA_WORKING_DIR:       %JUNIT2AVALLA_WORKING_DIR%) else (echo 17. JUNIT2AVALLA_WORKING_DIR:       [NOT SET])
if defined JUNIT2AVALLA_OUTPUT (echo 18. JUNIT2AVALLA_OUTPUT:            %JUNIT2AVALLA_OUTPUT%) else (echo 18. JUNIT2AVALLA_OUTPUT:            [NOT SET])
if defined JUNIT2AVALLA_PARSER (echo 19. JUNIT2AVALLA_PARSER:            %JUNIT2AVALLA_PARSER%) else (echo 19. JUNIT2AVALLA_PARSER:            [NOT SET])
if defined JUNIT2AVALLA_CLEAN (echo 20. JUNIT2AVALLA_CLEAN:             %JUNIT2AVALLA_CLEAN%) else (echo 20. JUNIT2AVALLA_CLEAN:             [NOT SET])
if defined JUNIT2AVALLA_HELP (echo 21. JUNIT2AVALLA_HELP:              %JUNIT2AVALLA_HELP%) else (echo 21. JUNIT2AVALLA_HELP:              [NOT SET])
echo.
echo R. Reset to default settings
echo 0. to save and continue
echo.
set /p choice="Enter the number of the parameter to modify (R to reset defaults, 0 to save and continue): "

if /I "%choice%"=="R" goto RESET_DEFAULTS
if /I "%choice%"=="0" goto SAVE

goto CHOICE_%choice%

echo Invalid choice. Please try again.
pause
goto MENU

:: Modify parameters
:CHOICE_1
    set /p newVal="Enter a value for ASMETAL2JAVA_INPUT (current: %ASMETAL2JAVA_INPUT%): %ARG_ASMETAL2JAVA_INPUT% "
    if not "!newVal!"=="" (set "ASMETAL2JAVA_INPUT=%ARG_ASMETAL2JAVA_INPUT% !newVal!") else set "ASMETAL2JAVA_INPUT="
    goto MENU

:CHOICE_2
    set /p newVal="Enter a value for ASMETAL2JAVA_WORKING_DIR (current: %ASMETAL2JAVA_WORKING_DIR%): %ARG_ASMETAL2JAVA_WORKING_DIR% "
    if not "!newVal!"=="" (set "ASMETAL2JAVA_WORKING_DIR=%ARG_ASMETAL2JAVA_WORKING_DIR% !newVal!") else set "ASMETAL2JAVA_WORKING_DIR="
    goto MENU

:CHOICE_3
    set /p newVal="Enter a value for ASMETAL2JAVA_OUTPUT (current: %ASMETAL2JAVA_OUTPUT%): %ARG_ASMETAL2JAVA_OUTPUT% "
    if not "!newVal!"=="" (set "ASMETAL2JAVA_OUTPUT=%ARG_ASMETAL2JAVA_OUTPUT% !newVal!") else set "ASMETAL2JAVA_OUTPUT="
    goto MENU

:CHOICE_4
    set /p newVal="Enter a value for ASMETAL2JAVA_MODE (current: %ASMETAL2JAVA_MODE%): %ARG_ASMETAL2JAVA_MODE% "
    if not "!newVal!"=="" (set "ASMETAL2JAVA_MODE=%ARG_ASMETAL2JAVA_MODE%  !newVal!") else set "ASMETAL2JAVA_MODE="
    goto MENU

:CHOICE_5
    set /p newVal="Enter a value for ASMETAL2JAVA_COMPILER_VERSION (current: %ASMETAL2JAVA_COMPILER_VERSION%): %ARG_ASMETAL2JAVA_COMPILER_VERSION% "
    if not "!newVal!"=="" (
        set "ASMETAL2JAVA_COMPILER_VERSION=%ARG_ASMETAL2JAVA_COMPILER_VERSION% !newVal!"
        set "EVOSUITE_JAVA_VERSION=%ARG_EVOSUITE_JAVA_VERSION%!newVal!"
    ) else set "ASMETAL2JAVA_COMPILER_VERSION="
    goto MENU

:CHOICE_6
    set /p newVal="Enter a value for ASMETAL2JAVA_CLEAN (current: %ASMETAL2JAVA_CLEAN%): %ARG_ASMETAL2JAVA_CLEAN%=ON/OFF "
    if /i "!newVal!"=="on" (set "ASMETAL2JAVA_CLEAN=%ARG_ASMETAL2JAVA_CLEAN%") else set "ASMETAL2JAVA_CLEAN="
    goto MENU

:CHOICE_7
    set /p newVal="Enter a value for ASMETAL2JAVA_PROPERTIES (current: %ASMETAL2JAVA_PROPERTIES%, use the -D format): "
    if not "!newVal!"=="" (set "ASMETAL2JAVA_PROPERTIES=!newVal!") else set "ASMETAL2JAVA_PROPERTIES="
    goto MENU

:CHOICE_8
    set /p newVal="Enter a value for ASMETAL2JAVA_HELP (current: %ASMETAL2JAVA_HELP%): %ARG_ASMETAL2JAVA_HELP%=ON/OFF "
    if /i "!newVal!"=="on" (set "ASMETAL2JAVA_HELP=%ARG_ASMETAL2JAVA_HELP%") else set "ASMETAL2JAVA_HELP="
    goto MENU
    
:CHOICE_9
    set /p newVal="Enter a value for EVOSUITE_VERSION(current: %EVOSUITE_VERSION%): %ARG_EVOSUITE_VERSION% "
    if not "!newVal!"=="" (set "EVOSUITE_VERSION=%ARG_EVOSUITE_VERSION%!newVal!") else set "EVOSUITE_VERSION="
    goto MENU

:CHOICE_10
    set /p newVal="Enter a value for EVOSUITE_JAVA_VERSION (current: %EVOSUITE_JAVA_VERSION%): %ARG_EVOSUITE_JAVA_VERSION% "
    if not "!newVal!"=="" (
        set "ASMETAL2JAVA_COMPILER_VERSION=%ARG_ASMETAL2JAVA_COMPILER_VERSION% !newVal!"
        set "EVOSUITE_JAVA_VERSION=%ARG_EVOSUITE_JAVA_VERSION%!newVal!"
    ) else set "EVOSUITE_JAVA_VERSION="
    goto MENU

:CHOICE_11
    set /p newVal="Enter a value for EVOSUITE_TARGET(current: %EVOSUITE_TARGET%): %ARG_EVOSUITE_TARGET% "
    if not "!newVal!"=="" (set "EVOSUITE_TARGET=%ARG_EVOSUITE_TARGET% !newVal!") else set "EVOSUITE_TARGET="
    goto MENU

:CHOICE_12
    set /p newVal="Enter a value for EVOSUITE_CLASS(current: %EVOSUITE_CLASS%): %ARG_EVOSUITE_CLASS% "
    if not "!newVal!"=="" (set "EVOSUITE_CLASS=%ARG_EVOSUITE_CLASS% !newVal!") else set "EVOSUITE_CLASS="
    goto MENU

:CHOICE_13
    set /p newVal="Enter a value for EVOSUITE_CRITERION(current: %EVOSUITE_CRITERION%): %ARG_EVOSUITE_CRITERION% "
    if not "!newVal!"=="" (set "EVOSUITE_CRITERION=%ARG_EVOSUITE_CRITERION% !newVal!") else set "EVOSUITE_CRITERION="
    goto MENU

:CHOICE_14
    set /p newVal="Enter a value for EVOSUITE_SEARCH_BUDGET(current: %EVOSUITE_SEARCH_BUDGET%): %ARG_EVOSUITE_SEARCH_BUDGET% "
    if not "!newVal!"=="" (set "EVOSUITE_SEARCH_BUDGET=%ARG_EVOSUITE_SEARCH_BUDGET%!newVal!") else set "EVOSUITE_SEARCH_BUDGET="
    goto MENU

:CHOICE_15
    set /p newVal="Enter a value for EVOSUITE_PROPERTIES(current: %EVOSUITE_PROPERTIES%): %ARG_EVOSUITE_PROPERTIES% "
    if not "!newVal!"=="" (set "EVOSUITE_PROPERTIES=%ARG_EVOSUITE_PROPERTIES% !newVal!") else set "EVOSUITE_PROPERTIES="
    goto MENU
)

:CHOICE_16
    set /p newVal="Enter a value for JUNIT2AVALLA_INPUT(current: %JUNIT2AVALLA_INPUT%): %ARG_JUNIT2AVALLA_INPUT% "
    if not "!newVal!"=="" (set "JUNIT2AVALLA_INPUT=%ARG_JUNIT2AVALLA_INPUT% !newVal!") else set "JUNIT2AVALLA_INPUT="
    goto MENU
)

:CHOICE_17
    set /p newVal="Enter a value for JUNIT2AVALLA_WORKING_DIR(current: %JUNIT2AVALLA_WORKING_DIR%): %ARG_JUNIT2AVALLA_WORKING_DIR% "
    if not "!newVal!"=="" (set "JUNIT2AVALLA_WORKING_DIR=%ARG_JUNIT2AVALLA_WORKING_DIR% !newVal!") else set "JUNIT2AVALLA_WORKING_DIR="
    goto MENU
)

:CHOICE_18
    set /p newVal="Enter a value for JUNIT2AVALLA_OUTPUT(current: %JUNIT2AVALLA_OUTPUT%): %ARG_JUNIT2AVALLA_OUTPUT% "
    if not "!newVal!"=="" (set "JUNIT2AVALLA_OUTPUT=%ARG_JUNIT2AVALLA_OUTPUT% !newVal!") else set "JUNIT2AVALLA_OUTPUT="
    goto MENU
)

:CHOICE_19
    set /p newVal="Enter a value for JUNIT2AVALLA_PARSER(current: %JUNIT2AVALLA_PARSER%): %ARG_JUNIT2AVALLA_PARSER% "
    if not "!newVal!"=="" (set "JUNIT2AVALLA_PARSER=%ARG_JUNIT2AVALLA_PARSER% !newVal!") else set "JUNIT2AVALLA_PARSER="
    goto MENU
)

:CHOICE_20
    set /p newVal="Enter a value for JUNIT2AVALLA_CLEAN(current: %JUNIT2AVALLA_CLEAN%): %ARG_JUNIT2AVALLA_CLEAN%=ON/OFF "
    if /i "!newVal!"=="on" (set "JUNIT2AVALLA_CLEAN=%ARG_JUNIT2AVALLA_CLEAN%") else set "JUNIT2AVALLA_CLEAN="
    goto MENU
)

:CHOICE_21
    set /p newVal="Enter a value for JUNIT2AVALLA_HELP(current: %JUNIT2AVALLA_HELP%): %ARG_JUNIT2AVALLA_HELP%=ON/OFF "
    if /i "!newVal!"=="on" (set "JUNIT2AVALLA_HELP=%ARG_JUNIT2AVALLA_HELP%") else set "JUNIT2AVALLA_HELP="
    goto MENU
)

:: Reset all parameters to default values
:RESET_DEFAULTS
    set "ASMETAL2JAVA_INPUT=%ARG_ASMETAL2JAVA_INPUT% %DEFAULT_ASMETAL2JAVA_INPUT%"
    set "ASMETAL2JAVA_WORKING_DIR=%ARG_ASMETAL2JAVA_WORKING_DIR% %DEFAULT_ASMETAL2JAVA_WORKING_DIR%"
    set "ASMETAL2JAVA_OUTPUT=%ARG_ASMETAL2JAVA_OUTPUT% %DEFAULT_ASMETAL2JAVA_OUTPUT%"
    set "ASMETAL2JAVA_MODE=%ARG_ASMETAL2JAVA_MODE% %DEFAULT_ASMETAL2JAVA_MODE%"
    set "ASMETAL2JAVA_COMPILER_VERSION=%ARG_ASMETAL2JAVA_COMPILER_VERSION% %DEFAULT_ASMETAL2JAVA_COMPILER_VERSION%"
    set "ASMETAL2JAVA_CLEAN=%ARG_ASMETAL2JAVA_CLEAN% %DEFAULT_ASMETAL2JAVA_CLEAN%"
    set "ASMETAL2JAVA_PROPERTIES=%ARG_ASMETAL2JAVA_PROPERTIES% %DEFAULT_ASMETAL2JAVA_PROPERTIES%"
    set "ASMETAL2JAVA_HELP="
    set "EVOSUITE_VERSION=%ARG_EVOSUITE_VERSION% %DEFAULT_EVOSUITE_VERSION%"
    set "EVOSUITE_JAVA_VERSION=%ARG_EVOSUITE_JAVA_VERSION% %DEFAULT_EVOSUITE_JAVA_VERSION%"
    set "EVOSUITE_TARGET=%ARG_EVOSUITE_TARGET% %DEFAULT_EVOSUITE_TARGET%"
    set "EVOSUITE_CLASS=%ARG_EVOSUITE_CLASS% %DEFAULT_EVOSUITE_CLASS%"
    set "EVOSUITE_CRITERION=%ARG_EVOSUITE_CRITERION% %DEFAULT_EVOSUITE_CRITERION%"
    set "EVOSUITE_SEARCH_BUDGET=%ARG_EVOSUITE_SEARCH_BUDGET%%DEFAULT_EVOSUITE_SEARCH_BUDGET%"
    set "EVOSUITE_PROPERTIES=%ARG_EVOSUITE_PROPERTIES% %DEFAULT_EVOSUITE_PROPERTIES%"
    set "JUNIT2AVALLA_INPUT=%ARG_JUNIT2AVALLA_INPUT% %DEFAULT_JUNIT2AVALLA_INPUT%"
    set "JUNIT2AVALLA_WORKING_DIR=%ARG_JUNIT2AVALLA_WORKING_DIR% %DEFAULT_JUNIT2AVALLA_WORKING_DIR%"
    set "JUNIT2AVALLA_OUTPUT=%ARG_JUNIT2AVALLA_OUTPUT% %DEFAULT_JUNIT2AVALLA_OUTPUT%"
    set "JUNIT2AVALLA_PARSER=%ARG_JUNIT2AVALLA_PARSER% %DEFAULT_JUNIT2AVALLA_PARSER%"
    set "JUNIT2AVALLA_CLEAN=%ARG_JUNIT2AVALLA_CLEAN% %DEFAULT_JUNIT2AVALLA_CLEAN%"
    set "JUNIT2AVALLA_HELP="
    echo Settings have been reset to default values.
    goto MENU

:SAVE
:: Save variables to .env
(
	echo ASMETAL2JAVA_INPUT=%ASMETAL2JAVA_INPUT%
    echo ASMETAL2JAVA_WORKING_DIR=%ASMETAL2JAVA_WORKING_DIR%
    echo ASMETAL2JAVA_OUTPUT=%ASMETAL2JAVA_OUTPUT%
    echo ASMETAL2JAVA_MODE=%ASMETAL2JAVA_MODE%
    echo ASMETAL2JAVA_COMPILER_VERSION=%ASMETAL2JAVA_COMPILER_VERSION%
    echo ASMETAL2JAVA_CLEAN=%ASMETAL2JAVA_CLEAN%
    echo ASMETAL2JAVA_PROPERTIES=%ASMETAL2JAVA_PROPERTIES%
    echo ASMETAL2JAVA_HELP=%ASMETAL2JAVA_HELP%
    echo EVOSUITE_VERSION=%EVOSUITE_VERSION%
    echo EVOSUITE_JAVA_VERSION=%EVOSUITE_JAVA_VERSION%
    echo EVOSUITE_TARGET=%EVOSUITE_TARGET%
    echo EVOSUITE_CLASS=%EVOSUITE_CLASS%
    echo EVOSUITE_CRITERION=%EVOSUITE_CRITERION%
    echo EVOSUITE_SEARCH_BUDGET=%EVOSUITE_SEARCH_BUDGET%
    echo EVOSUITE_PROPERTIES=%EVOSUITE_PROPERTIES%
    echo JUNIT2AVALLA_INPUT=%JUNIT2AVALLA_INPUT%
    echo JUNIT2AVALLA_WORKING_DIR=%JUNIT2AVALLA_WORKING_DIR%
    echo JUNIT2AVALLA_OUTPUT=%JUNIT2AVALLA_OUTPUT%
    echo JUNIT2AVALLA_PARSER=%JUNIT2AVALLA_PARSER%
    echo JUNIT2AVALLA_CLEAN=%JUNIT2AVALLA_CLEAN%
    echo JUNIT2AVALLA_HELP=%JUNIT2AVALLA_HELP%
) > "%ENV_FILE%"

echo.
echo .env file saved successfully:
type "%ENV_FILE%"
