/*
 * generated by Xtext 2.42.0
 */
package org.asmeta.xt.ui.tests;

import asmeta.xt.ui.internal.XtActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AsmetaLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtActivator.getInstance().getInjector("org.asmeta.xt.AsmetaL");
	}

}
