source.. = src/main/java/,\
           src/main/resources/,\
           src/test/java/,\
           src/test/resources/
bin.includes = META-INF/,\
               .,\
               lib/,\
               lib/annotations-13.0.jar,\
               lib/classmate-1.7.0.jar,\
               lib/error_prone_annotations-2.33.0.jar,\
               lib/jackson-annotations-2.17.1.jar,\
               lib/jackson-annotations-2.18.2.jar,\
               lib/jackson-core-2.17.1.jar,\
               lib/jackson-core-2.18.2.jar,\
               lib/jackson-databind-2.17.1.jar,\
               lib/jackson-databind-2.18.2.jar,\
               lib/jackson-datatype-jdk8-2.18.2.jar,\
               lib/jackson-datatype-jsr310-2.17.1.jar,\
               lib/jackson-datatype-jsr310-2.18.2.jar,\
               lib/jackson-module-kotlin-2.18.2.jar,\
               lib/jsonschema-generator-4.38.0.jar,\
               lib/jsonschema-module-jackson-4.38.0.jar,\
               lib/jsonschema-module-swagger-2-4.38.0.jar,\
               lib/jsoup-1.18.1.jar,\
               lib/kotlin-reflect-1.8.10.jar,\
               lib/kotlin-stdlib-1.8.0.jar,\
               lib/kotlin-stdlib-common-1.8.0.jar,\
               lib/kotlin-stdlib-jdk7-1.8.0.jar,\
               lib/kotlin-stdlib-jdk8-1.8.0.jar,\
               lib/logging-interceptor-4.12.0.jar,\
               lib/okhttp-4.12.0.jar,\
               lib/okio-3.6.0.jar,\
               lib/okio-jvm-3.6.0.jar,\
               lib/ollama4j-1.1.0.jar,\
               lib/openai-java-4.30.0.jar,\
               lib/openai-java-client-okhttp-4.30.0.jar,\
               lib/openai-java-core-4.30.0.jar,\
               lib/slf4j-api-2.0.16.jar,\
               lib/slf4j-api-2.0.9.jar,\
               lib/swagger-annotations-2.2.31.jar,\
               src/main/resources/simple_prompt_template_o3.txt,\
               src/main/resources/simple_prompt_template_o2.txt,\
               src/main/resources/simple_prompt_template_o1.txt
