/**
 * generated by Xtext 2.32.0
 */
package org.asmeta.xt.asmetal.impl;

import org.asmeta.xt.asmetal.AnyDomain;
import org.asmeta.xt.asmetal.AsmetalPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Any Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AnyDomainImpl extends TypeDomainImpl implements AnyDomain
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AnyDomainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetalPackage.Literals.ANY_DOMAIN;
  }

} //AnyDomainImpl
