/**
 * generated by Xtext 2.28.0
 */
package org.asmeta.xt.asmetal.impl;

import org.asmeta.xt.asmetal.AsmetalPackage;
import org.asmeta.xt.asmetal.ComplexDomain;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Complex Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ComplexDomainImpl extends StandardDomainImpl implements ComplexDomain
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComplexDomainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetalPackage.Literals.COMPLEX_DOMAIN;
  }

} //ComplexDomainImpl
