/**
 * generated by Xtext 2.21.0
 */
package org.asmeta.xt.asmetal.impl;

import java.util.Collection;

import org.asmeta.xt.asmetal.AsmetalPackage;
import org.asmeta.xt.asmetal.Domain;
import org.asmeta.xt.asmetal.FunctionDefinition;
import org.asmeta.xt.asmetal.Term;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Function Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.asmeta.xt.asmetal.impl.FunctionDefinitionImpl#getDefinedFunctionName <em>Defined Function Name</em>}</li>
 *   <li>{@link org.asmeta.xt.asmetal.impl.FunctionDefinitionImpl#getVariables <em>Variables</em>}</li>
 *   <li>{@link org.asmeta.xt.asmetal.impl.FunctionDefinitionImpl#getDomain <em>Domain</em>}</li>
 *   <li>{@link org.asmeta.xt.asmetal.impl.FunctionDefinitionImpl#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FunctionDefinitionImpl extends MinimalEObjectImpl.Container implements FunctionDefinition
{
  /**
   * The default value of the '{@link #getDefinedFunctionName() <em>Defined Function Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefinedFunctionName()
   * @generated
   * @ordered
   */
  protected static final String DEFINED_FUNCTION_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDefinedFunctionName() <em>Defined Function Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefinedFunctionName()
   * @generated
   * @ordered
   */
  protected String definedFunctionName = DEFINED_FUNCTION_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getVariables() <em>Variables</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariables()
   * @generated
   * @ordered
   */
  protected EList<String> variables;

  /**
   * The cached value of the '{@link #getDomain() <em>Domain</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDomain()
   * @generated
   * @ordered
   */
  protected EList<Domain> domain;

  /**
   * The cached value of the '{@link #getBody() <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBody()
   * @generated
   * @ordered
   */
  protected Term body;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunctionDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetalPackage.Literals.FUNCTION_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDefinedFunctionName()
  {
    return definedFunctionName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefinedFunctionName(String newDefinedFunctionName)
  {
    String oldDefinedFunctionName = definedFunctionName;
    definedFunctionName = newDefinedFunctionName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AsmetalPackage.FUNCTION_DEFINITION__DEFINED_FUNCTION_NAME, oldDefinedFunctionName, definedFunctionName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getVariables()
  {
    if (variables == null)
    {
      variables = new EDataTypeEList<String>(String.class, this, AsmetalPackage.FUNCTION_DEFINITION__VARIABLES);
    }
    return variables;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Domain> getDomain()
  {
    if (domain == null)
    {
      domain = new EObjectContainmentEList<Domain>(Domain.class, this, AsmetalPackage.FUNCTION_DEFINITION__DOMAIN);
    }
    return domain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Term getBody()
  {
    return body;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBody(Term newBody, NotificationChain msgs)
  {
    Term oldBody = body;
    body = newBody;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AsmetalPackage.FUNCTION_DEFINITION__BODY, oldBody, newBody);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBody(Term newBody)
  {
    if (newBody != body)
    {
      NotificationChain msgs = null;
      if (body != null)
        msgs = ((InternalEObject)body).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AsmetalPackage.FUNCTION_DEFINITION__BODY, null, msgs);
      if (newBody != null)
        msgs = ((InternalEObject)newBody).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AsmetalPackage.FUNCTION_DEFINITION__BODY, null, msgs);
      msgs = basicSetBody(newBody, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AsmetalPackage.FUNCTION_DEFINITION__BODY, newBody, newBody));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AsmetalPackage.FUNCTION_DEFINITION__DOMAIN:
        return ((InternalEList<?>)getDomain()).basicRemove(otherEnd, msgs);
      case AsmetalPackage.FUNCTION_DEFINITION__BODY:
        return basicSetBody(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AsmetalPackage.FUNCTION_DEFINITION__DEFINED_FUNCTION_NAME:
        return getDefinedFunctionName();
      case AsmetalPackage.FUNCTION_DEFINITION__VARIABLES:
        return getVariables();
      case AsmetalPackage.FUNCTION_DEFINITION__DOMAIN:
        return getDomain();
      case AsmetalPackage.FUNCTION_DEFINITION__BODY:
        return getBody();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AsmetalPackage.FUNCTION_DEFINITION__DEFINED_FUNCTION_NAME:
        setDefinedFunctionName((String)newValue);
        return;
      case AsmetalPackage.FUNCTION_DEFINITION__VARIABLES:
        getVariables().clear();
        getVariables().addAll((Collection<? extends String>)newValue);
        return;
      case AsmetalPackage.FUNCTION_DEFINITION__DOMAIN:
        getDomain().clear();
        getDomain().addAll((Collection<? extends Domain>)newValue);
        return;
      case AsmetalPackage.FUNCTION_DEFINITION__BODY:
        setBody((Term)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AsmetalPackage.FUNCTION_DEFINITION__DEFINED_FUNCTION_NAME:
        setDefinedFunctionName(DEFINED_FUNCTION_NAME_EDEFAULT);
        return;
      case AsmetalPackage.FUNCTION_DEFINITION__VARIABLES:
        getVariables().clear();
        return;
      case AsmetalPackage.FUNCTION_DEFINITION__DOMAIN:
        getDomain().clear();
        return;
      case AsmetalPackage.FUNCTION_DEFINITION__BODY:
        setBody((Term)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AsmetalPackage.FUNCTION_DEFINITION__DEFINED_FUNCTION_NAME:
        return DEFINED_FUNCTION_NAME_EDEFAULT == null ? definedFunctionName != null : !DEFINED_FUNCTION_NAME_EDEFAULT.equals(definedFunctionName);
      case AsmetalPackage.FUNCTION_DEFINITION__VARIABLES:
        return variables != null && !variables.isEmpty();
      case AsmetalPackage.FUNCTION_DEFINITION__DOMAIN:
        return domain != null && !domain.isEmpty();
      case AsmetalPackage.FUNCTION_DEFINITION__BODY:
        return body != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (definedFunctionName: ");
    result.append(definedFunctionName);
    result.append(", variables: ");
    result.append(variables);
    result.append(')');
    return result.toString();
  }

  public org.asmeta.xt.asmetal.Function getDefinedFunction()
  {
  	return org.asmeta.xt.validation.utility.Utility.getFunctionByName(this.definedFunctionName);
  }
  
  public java.util.List<org.asmeta.xt.asmetal.VariableTerm> getVariable() {
  	java.util.List<org.asmeta.xt.asmetal.VariableTerm> variableList = new java.util.ArrayList<org.asmeta.xt.asmetal.VariableTerm>();
	
	for (String s : variables) {
		org.asmeta.xt.asmetal.VariableTerm var = org.asmeta.xt.asmetal.AsmetalFactory.eINSTANCE.createVariableTerm();
		var.setName(s);
		var.setDomain(org.asmeta.xt.validation.utility.Utility.getDomain(s));
		variableList.add(var);
	}
	
	return variableList;
  }
} //FunctionDefinitionImpl
