/**
 * generated by Xtext 2.34.0
 */
package org.asmeta.xt.asmetal.impl;

import org.asmeta.xt.asmetal.AsmetalPackage;
import org.asmeta.xt.asmetal.IntegerDomain;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Integer Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IntegerDomainImpl extends StandardDomainImpl implements IntegerDomain
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntegerDomainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetalPackage.Literals.INTEGER_DOMAIN;
  }

} //IntegerDomainImpl
