/**
 * generated by Xtext 2.40.0
 */
package org.asmeta.xt.asmetal.impl;

import org.asmeta.xt.asmetal.AsmetalPackage;
import org.asmeta.xt.asmetal.NaturalDomain;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Natural Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NaturalDomainImpl extends StandardDomainImpl implements NaturalDomain
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NaturalDomainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetalPackage.Literals.NATURAL_DOMAIN;
  }

} //NaturalDomainImpl
