/**
 * generated by Xtext 2.40.0
 */
package org.asmeta.xt.asmetal.impl;

import org.asmeta.xt.asmetal.AsmetalPackage;
import org.asmeta.xt.asmetal.StaticFunction;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Static Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StaticFunctionImpl extends BasicFunctionImpl implements StaticFunction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StaticFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetalPackage.Literals.STATIC_FUNCTION;
  }

  public org.asmeta.xt.asmetal.DynamicFunction getInitializedFunction()
  {
  	org.asmeta.xt.asmetal.Function f = org.asmeta.xt.validation.utility.Utility.getFunctionByName(this.name);
	if (f instanceof org.asmeta.xt.asmetal.DynamicFunction)
		return (org.asmeta.xt.asmetal.DynamicFunction)f;
	return null;
  }
} //StaticFunctionImpl
