/**
 * generated by Xtext 2.16.0
 */
package org.asmeta.avallaxt.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AvallaIdeModule extends AbstractAvallaIdeModule {
}
