/**
 * generated by Xtext 2.21.0
 */
package org.asmeta.xt.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class AsmetaLDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
