/**
 * generated by Xtext 2.22.0
 */
package org.asmeta.avallaxt.avallaXt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exec Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.asmeta.avallaxt.avallaXt.ExecBlock#getScenario <em>Scenario</em>}</li>
 *   <li>{@link org.asmeta.avallaxt.avallaXt.ExecBlock#getBlock <em>Block</em>}</li>
 * </ul>
 *
 * @see org.asmeta.avallaxt.avallaXt.AvallaXtPackage#getExecBlock()
 * @model
 * @generated
 */
public interface ExecBlock extends Command
{
  /**
   * Returns the value of the '<em><b>Scenario</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenario</em>' attribute.
   * @see #setScenario(String)
   * @see org.asmeta.avallaxt.avallaXt.AvallaXtPackage#getExecBlock_Scenario()
   * @model
   * @generated
   */
  String getScenario();

  /**
   * Sets the value of the '{@link org.asmeta.avallaxt.avallaXt.ExecBlock#getScenario <em>Scenario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scenario</em>' attribute.
   * @see #getScenario()
   * @generated
   */
  void setScenario(String value);

  /**
   * Returns the value of the '<em><b>Block</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block</em>' attribute.
   * @see #setBlock(String)
   * @see org.asmeta.avallaxt.avallaXt.AvallaXtPackage#getExecBlock_Block()
   * @model
   * @generated
   */
  String getBlock();

  /**
   * Sets the value of the '{@link org.asmeta.avallaxt.avallaXt.ExecBlock#getBlock <em>Block</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block</em>' attribute.
   * @see #getBlock()
   * @generated
   */
  void setBlock(String value);

} // ExecBlock
