/**
 * generated by Xtext 2.22.0
 */
package org.asmeta.avallaxt.avallaXt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Step</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.asmeta.avallaxt.avallaXt.AvallaXtPackage#getStep()
 * @model
 * @generated
 */
public interface Step extends Command
{
} // Step
