/* Generated By:JJTree: Do not edit this line. ASTparse.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.asmeta.composition.parser;

public
class ASTparse extends SimpleNode {
  public ASTparse(int id) {
    super(id);
  }

  public ASTparse(CompositionFormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bb3925022fde17226fcccb8472c83fd7 (do not edit this line) */
