/**
 * generated by Xtext 2.21.0
 */
package org.asmeta.xt;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AsmetaLStandaloneSetup extends AsmetaLStandaloneSetupGenerated {
  public static void doSetup() {
    new AsmetaLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
