/**
 * generated by Xtext 2.24.0
 */
package org.asmeta.xt.asmetal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Basic Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getBasicRule()
 * @model
 * @generated
 */
public interface BasicRule extends Rule
{
} // BasicRule
