/**
 * generated by Xtext 2.28.0
 */
package org.asmeta.xt.asmetal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Basic TD</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getBasicTD()
 * @model
 * @generated
 */
public interface BasicTD extends TypeDomain
{
} // BasicTD
