/**
 * generated by Xtext 2.34.0
 */
package org.asmeta.xt.asmetal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complex Term</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getComplexTerm()
 * @model
 * @generated
 */
public interface ComplexTerm extends ConstantTerm
{
} // ComplexTerm
