/**
 * generated by Xtext 2.36.0
 */
package org.asmeta.xt.asmetal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complex Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getComplexDomain()
 * @model
 * @generated
 */
public interface ComplexDomain extends StandardDomain
{
} // ComplexDomain
