/**
 * generated by Xtext 2.40.0
 */
package org.asmeta.xt.asmetal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Controlled Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getControlledFunction()
 * @model
 * @generated
 */
public interface ControlledFunction extends DynamicFunction
{
} // ControlledFunction
