/**
 * generated by Xtext 2.21.0
 */
package org.asmeta.xt.asmetal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Forall Term</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getForallTerm()
 * @model
 * @generated
 */
public interface ForallTerm extends FiniteQuantificationTerm
{
} // ForallTerm
