/**
 * generated by Xtext 2.28.0
 */
package org.asmeta.xt.asmetal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Import Clause</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.asmeta.xt.asmetal.ImportClause#getModuleName <em>Module Name</em>}</li>
 *   <li>{@link org.asmeta.xt.asmetal.ImportClause#getImportedList <em>Imported List</em>}</li>
 * </ul>
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getImportClause()
 * @model
 * @generated
 */
public interface ImportClause extends EObject
{
  /**
   * Returns the value of the '<em><b>Module Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Module Name</em>' attribute.
   * @see #setModuleName(String)
   * @see org.asmeta.xt.asmetal.AsmetalPackage#getImportClause_ModuleName()
   * @model
   * @generated
   */
  String getModuleName();

  /**
   * Sets the value of the '{@link org.asmeta.xt.asmetal.ImportClause#getModuleName <em>Module Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Module Name</em>' attribute.
   * @see #getModuleName()
   * @generated
   */
  void setModuleName(String value);

  /**
   * Returns the value of the '<em><b>Imported List</b></em>' containment reference list.
   * The list contents are of type {@link org.asmeta.xt.asmetal.importData}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imported List</em>' containment reference list.
   * @see org.asmeta.xt.asmetal.AsmetalPackage#getImportClause_ImportedList()
   * @model containment="true"
   * @generated
   */
  EList<importData> getImportedList();

} // ImportClause
