/**
 * generated by Xtext 2.24.0
 */
package org.asmeta.xt.asmetal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Invariant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.asmeta.xt.asmetal.Invariant#getInvar_list <em>Invar list</em>}</li>
 * </ul>
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getInvariant()
 * @model
 * @generated
 */
public interface Invariant extends Property
{
  /**
   * Returns the value of the '<em><b>Invar list</b></em>' containment reference list.
   * The list contents are of type {@link org.asmeta.xt.asmetal.InvariantElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invar list</em>' containment reference list.
   * @see org.asmeta.xt.asmetal.AsmetalPackage#getInvariant_Invar_list()
   * @model containment="true"
   * @generated
   */
  EList<InvariantElement> getInvar_list();

  java.util.List<org.asmeta.xt.asmetal.RuleDeclaration> getConstrainedRule();
  
  java.util.List<org.asmeta.xt.asmetal.Function> getConstrainedFunction();
  
  java.util.List<org.asmeta.xt.asmetal.Domain> getConstrainedDomain();
} // Invariant
