/**
 * generated by Xtext 2.40.0
 */
package org.asmeta.xt.asmetal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Natural Term</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getNaturalTerm()
 * @model
 * @generated
 */
public interface NaturalTerm extends ConstantTerm
{
} // NaturalTerm
