/**
 * generated by Xtext 2.24.0
 */
package org.asmeta.xt.asmetal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Real Term</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getRealTerm()
 * @model
 * @generated
 */
public interface RealTerm extends NumberTerm
{
} // RealTerm
