/**
 * generated by Xtext 2.24.0
 */
package org.asmeta.xt.asmetal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Skip Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getSkipRule()
 * @model
 * @generated
 */
public interface SkipRule extends BasicRule
{
} // SkipRule
