/**
 * generated by Xtext 2.40.0
 */
package org.asmeta.xt.asmetal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Temporal Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getTemporalProperty()
 * @model
 * @generated
 */
public interface TemporalProperty extends Property
{
} // TemporalProperty
