/**
 * generated by Xtext 2.36.0
 */
package org.asmeta.xt.asmetal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Turbo Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getTurboDeclaration()
 * @model
 * @generated
 */
public interface TurboDeclaration extends RuleDeclaration
{
} // TurboDeclaration
