/**
 * generated by Xtext 2.28.0
 */
package org.asmeta.xt.asmetal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.asmeta.xt.asmetal.AsmetalPackage#getTypeDomain()
 * @model
 * @generated
 */
public interface TypeDomain extends Domain
{
} // TypeDomain
