package org.asmeta.xt.tests.parsing.negative;

import com.google.inject.Inject;
import org.asmeta.xt.asmetal.Asm;
import org.asmeta.xt.asmetal.AsmetalPackage;
import org.asmeta.xt.tests.AsmetaLInjectorProvider;
import org.asmeta.xt.validation.ErrorCode;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(AsmetaLInjectorProvider.class)
@SuppressWarnings("all")
public class BodyNegativeParsingTest {
  @Inject
  private ParseHelper<Asm> parseHelper;

  @Inject
  @Extension
  private ValidationTestHelper _validationTestHelper;

  @Test
  @Tag("TestToMavenSkip")
  public void testDomainDefinition() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("import BodyLibrary");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain Cherries = {0 .. 3} ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain Cherries = {0 .. 5} ");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.DOMAIN_DEFINITION, ErrorCode.DOMAIN_DEFINITION__DEFINED_TWICE);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("import BodyLibrary ");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("domain Cherries = {0 .. 3} ");
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.DOMAIN_DEFINITION, ErrorCode.SIGNATURE__DOMAIN_NOT_IMPORTED);
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("asm prova");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("import StandardLibrary");
      _builder_2.newLine();
      _builder_2.append("signature:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("abstract domain Philosopher");
      _builder_2.newLine();
      _builder_2.append("definitions:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("domain Philosopher = {0 .. 3} ");
      _builder_2.newLine();
      result = this.parseHelper.parse(_builder_2);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.DOMAIN_DEFINITION, ErrorCode.DOMAIN_DEFINITION__DOMAIN_NOT_CONCRETE);
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("asm prova");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("import StandardLibrary");
      _builder_3.newLine();
      _builder_3.append("signature:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_3.newLine();
      _builder_3.append("definitions:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("domain NumOfCherries = {0 .. 3} ");
      _builder_3.newLine();
      result = this.parseHelper.parse(_builder_3);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.DOMAIN_DEFINITION, ErrorCode.DOMAIN_DEFINITION__IS_DYNAMIC_DOMAIN);
      StringConcatenation _builder_4 = new StringConcatenation();
      _builder_4.append("asm prova");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("import StandardLibrary");
      _builder_4.newLine();
      _builder_4.append("signature:");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("domain NumOfCherries subsetof Integer");
      _builder_4.newLine();
      _builder_4.append("definitions:");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("domain NumOfCherries = {0 .. 3} ");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("domain NumOfCherries = {0 .. 5} ");
      _builder_4.newLine();
      result = this.parseHelper.parse(_builder_4);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.DOMAIN_DEFINITION, ErrorCode.DOMAIN_DEFINITION__DEFINED_TWICE);
      StringConcatenation _builder_5 = new StringConcatenation();
      _builder_5.append("asm prova");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("import StandardLibrary");
      _builder_5.newLine();
      _builder_5.append("signature:");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("domain NumOfCherries subsetof Integer");
      _builder_5.newLine();
      _builder_5.append("definitions:");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("domain NumOfCherries = \"A\"");
      _builder_5.newLine();
      result = this.parseHelper.parse(_builder_5);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.DOMAIN_DEFINITION, ErrorCode.DOMAIN_DEFINITION__ILL_FORMED_BODY);
      StringConcatenation _builder_6 = new StringConcatenation();
      _builder_6.append("asm prova");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("import StandardLibrary");
      _builder_6.newLine();
      _builder_6.append("signature:");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("domain NumOfCherries subsetof Integer");
      _builder_6.newLine();
      _builder_6.append("definitions:");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("domain NumOfCherries = { 1 .. \"Z\" }");
      _builder_6.newLine();
      result = this.parseHelper.parse(_builder_6);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__DIFFERENT_DOMAINS);
      StringConcatenation _builder_7 = new StringConcatenation();
      _builder_7.append("asm prova");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("import StandardLibrary");
      _builder_7.newLine();
      _builder_7.append("signature:");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("domain NumOfCherries subsetof Integer");
      _builder_7.newLine();
      _builder_7.append("definitions:");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("domain NumOfCherries = { \"A\" .. 5 }");
      _builder_7.newLine();
      result = this.parseHelper.parse(_builder_7);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__DIFFERENT_DOMAINS);
      StringConcatenation _builder_8 = new StringConcatenation();
      _builder_8.append("asm prova");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("import StandardLibrary");
      _builder_8.newLine();
      _builder_8.append("signature:");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("domain NumOfCherries subsetof Integer");
      _builder_8.newLine();
      _builder_8.append("definitions:");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("domain NumOfCherries = { 1, 2, 5.4 }");
      _builder_8.newLine();
      result = this.parseHelper.parse(_builder_8);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__DIFFERENT_DOMAINS);
      StringConcatenation _builder_9 = new StringConcatenation();
      _builder_9.append("asm prova");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("import StandardLibrary");
      _builder_9.newLine();
      _builder_9.append("signature:");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("domain NumOfCherries subsetof Integer");
      _builder_9.newLine();
      _builder_9.append("definitions:");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("domain NumOfCherries = { \"A\" .. \"Z\" }");
      _builder_9.newLine();
      result = this.parseHelper.parse(_builder_9);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.DOMAIN_DEFINITION, ErrorCode.DOMAIN_DEFINITION__ILL_FORMED_BODY);
      StringConcatenation _builder_10 = new StringConcatenation();
      _builder_10.append("asm prova");
      _builder_10.newLine();
      _builder_10.append("signature:");
      _builder_10.newLine();
      _builder_10.append("\t");
      _builder_10.append("domain NumOfCherries subsetof Integer");
      _builder_10.newLine();
      _builder_10.append("definitions:");
      _builder_10.newLine();
      _builder_10.append("\t");
      _builder_10.append("domain NumOfCherries = {}");
      _builder_10.newLine();
      result = this.parseHelper.parse(_builder_10);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__ANY_DOMAIN_NOT_DECLARED);
      StringConcatenation _builder_11 = new StringConcatenation();
      _builder_11.append("asm prova");
      _builder_11.newLine();
      _builder_11.append("\t");
      _builder_11.append("import StandardLibrary");
      _builder_11.newLine();
      _builder_11.append("signature:");
      _builder_11.newLine();
      _builder_11.append("\t");
      _builder_11.append("domain NumOfCherries subsetof Integer");
      _builder_11.newLine();
      _builder_11.append("definitions:");
      _builder_11.newLine();
      _builder_11.append("\t");
      _builder_11.append("domain NumOfCherries = {}");
      _builder_11.newLine();
      result = this.parseHelper.parse(_builder_11);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_12 = new StringConcatenation();
      _builder_12.append("asm prova");
      _builder_12.newLine();
      _builder_12.append("\t");
      _builder_12.append("import StandardLibrary");
      _builder_12.newLine();
      _builder_12.append("signature:");
      _builder_12.newLine();
      _builder_12.append("\t");
      _builder_12.append("domain NumOfCherries subsetof Integer");
      _builder_12.newLine();
      _builder_12.append("definitions:");
      _builder_12.newLine();
      _builder_12.append("\t");
      _builder_12.append("domain NumOfCherries = { 1, 2, 3 }");
      _builder_12.newLine();
      result = this.parseHelper.parse(_builder_12);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_13 = new StringConcatenation();
      _builder_13.append("asm prova");
      _builder_13.newLine();
      _builder_13.append("\t");
      _builder_13.append("import StandardLibrary");
      _builder_13.newLine();
      _builder_13.append("signature:");
      _builder_13.newLine();
      _builder_13.append("\t");
      _builder_13.append("domain NumOfCherries subsetof Integer");
      _builder_13.newLine();
      _builder_13.append("definitions:");
      _builder_13.newLine();
      _builder_13.append("\t");
      _builder_13.append("domain NumOfCherries = { 1, 2, 2, 3 }");
      _builder_13.newLine();
      result = this.parseHelper.parse(_builder_13);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__ADDED_TWICE);
      StringConcatenation _builder_14 = new StringConcatenation();
      _builder_14.append("asm prova");
      _builder_14.newLine();
      _builder_14.append("\t");
      _builder_14.append("import StandardLibrary");
      _builder_14.newLine();
      _builder_14.append("signature:");
      _builder_14.newLine();
      _builder_14.append("\t");
      _builder_14.append("domain NumOfCherries subsetof Integer");
      _builder_14.newLine();
      _builder_14.append("definitions:");
      _builder_14.newLine();
      _builder_14.append("\t");
      _builder_14.append("domain NumOfCherries = { 1 .. 1 }");
      _builder_14.newLine();
      result = this.parseHelper.parse(_builder_14);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__ADDED_TWICE);
      StringConcatenation _builder_15 = new StringConcatenation();
      _builder_15.append("asm prova");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("import StandardLibrary");
      _builder_15.newLine();
      _builder_15.append("signature:");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("domain NumOfCherries subsetof Integer");
      _builder_15.newLine();
      _builder_15.append("definitions:");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("domain NumOfCherries = { 1 .. 15, 2 }");
      _builder_15.newLine();
      result = this.parseHelper.parse(_builder_15);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_16 = new StringConcatenation();
      _builder_16.append("asm prova");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("import StandardLibrary");
      _builder_16.newLine();
      _builder_16.append("signature:");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("domain NumOfCherries subsetof Integer");
      _builder_16.newLine();
      _builder_16.append("definitions:");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("domain NumOfCherries = { 1 .. 15, +2 }");
      _builder_16.newLine();
      result = this.parseHelper.parse(_builder_16);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_17 = new StringConcatenation();
      _builder_17.append("asm prova");
      _builder_17.newLine();
      _builder_17.append("\t");
      _builder_17.append("import StandardLibrary");
      _builder_17.newLine();
      _builder_17.append("signature:");
      _builder_17.newLine();
      _builder_17.append("\t");
      _builder_17.append("domain NumOfCherries subsetof Integer");
      _builder_17.newLine();
      _builder_17.append("definitions:");
      _builder_17.newLine();
      _builder_17.append("\t");
      _builder_17.append("domain NumOfCherries = { 1 .. 15, -2 }");
      _builder_17.newLine();
      result = this.parseHelper.parse(_builder_17);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__STEP_NEGATIVE);
      StringConcatenation _builder_18 = new StringConcatenation();
      _builder_18.append("asm prova");
      _builder_18.newLine();
      _builder_18.append("\t");
      _builder_18.append("import StandardLibrary");
      _builder_18.newLine();
      _builder_18.append("signature:");
      _builder_18.newLine();
      _builder_18.append("\t");
      _builder_18.append("domain NumOfCherries subsetof Integer");
      _builder_18.newLine();
      _builder_18.append("definitions:");
      _builder_18.newLine();
      _builder_18.append("\t");
      _builder_18.append("domain NumOfCherries = { 1 .. 15, \"A\" }");
      _builder_18.newLine();
      result = this.parseHelper.parse(_builder_18);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__STEP_NAN);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  @Tag("TestToMavenSkip")
  public void testFunctionDefinition() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova\t\t\t\t");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("abstract domain Philosopher\t\t\t\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static leftNeighbour: Philosopher -> Philosopher");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static philo1: Philosopher");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static philo2: Philosopher");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("function leftNeighbour($p in Philosopher) =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("switch($p)");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("case philo1: philo2");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("case philo2: philo1");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("endswitch");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("function leftNeighbour($p in Philosopher) =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("switch($p)");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("case philo1: philo1");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("case philo2: philo2");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("endswitch");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_DEFINITION, ErrorCode.FUNCTION_DEFINITION__DEFINED_TWICE);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova\t");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("import StandardLibrary\t\t\t");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("abstract domain Philosopher\t");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("abstract domain PhilosopherOther\t\t\t\t");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("static leftNeighbour: Philosopher -> Philosopher");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("static leftNeighbour: PhilosopherOther -> PhilosopherOther");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("static philo1a: Philosopher");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("static philo2a: Philosopher");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("static philo1b: PhilosopherOther");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("static philo2b: PhilosopherOther");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("function leftNeighbour($p in Philosopher) =");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("switch($p)");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("case philo1a: philo1a");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("case philo2a: philo2a");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("endswitch");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("function leftNeighbour($po in PhilosopherOther) =");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("switch($po)");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("case philo1b: philo1b");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("case philo2b: philo2b");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("endswitch");
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("asm prova\t\t\t\t");
      _builder_2.newLine();
      _builder_2.append("signature:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("abstract domain Philosopher\t\t\t\t");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("static leftNeighbour: Philosopher -> Philosopher");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("static philo1: Philosopher");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("static philo2: Philosopher");
      _builder_2.newLine();
      _builder_2.append("definitions:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("function leftNeighbour($p in PhilosopherNone) =");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("switch($p)");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("case philo1: philo2");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("case philo2: philo1");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("endswitch");
      _builder_2.newLine();
      _builder_2.newLine();
      result = this.parseHelper.parse(_builder_2);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_DEFINITION, ErrorCode.SIGNATURE__DOMAIN_NOT_FOUND);
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("asm prova");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("import BodyLibrary2\t\t");
      _builder_3.newLine();
      _builder_3.append("signature:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("abstract domain Philosopher\t\t\t\t");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("static philo1: Philosopher");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("static philo2: Philosopher");
      _builder_3.newLine();
      _builder_3.append("definitions:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("function leftNeighbour($p in Integer) =");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("switch($p)");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("case 1: philo1");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("case 2: philo2");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("endswitch");
      _builder_3.newLine();
      _builder_3.newLine();
      result = this.parseHelper.parse(_builder_3);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_DEFINITION, ErrorCode.SIGNATURE__FUNCTION_NOT_IMPORTED);
      StringConcatenation _builder_4 = new StringConcatenation();
      _builder_4.append("asm prova");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("import StandardLibrary\t\t");
      _builder_4.newLine();
      _builder_4.append("signature:");
      _builder_4.newLine();
      _builder_4.newLine();
      _builder_4.append("definitions:");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("function leftNeighbour($p in Integer) =");
      _builder_4.newLine();
      _builder_4.append("\t\t");
      _builder_4.append("switch($p)");
      _builder_4.newLine();
      _builder_4.append("\t\t\t");
      _builder_4.append("case 1: philo1");
      _builder_4.newLine();
      _builder_4.append("\t\t\t");
      _builder_4.append("case 2: philo2");
      _builder_4.newLine();
      _builder_4.append("\t\t");
      _builder_4.append("endswitch");
      _builder_4.newLine();
      _builder_4.newLine();
      result = this.parseHelper.parse(_builder_4);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_DEFINITION, ErrorCode.SIGNATURE__FUNCTION_NOT_FOUND);
      StringConcatenation _builder_5 = new StringConcatenation();
      _builder_5.append("asm prova\t\t\t\t");
      _builder_5.newLine();
      _builder_5.append("signature:");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("abstract domain Philosopher\t\t\t\t");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("controlled leftNeighbour: Philosopher -> Philosopher");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("static philo1: Philosopher");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("static philo2: Philosopher");
      _builder_5.newLine();
      _builder_5.append("definitions:");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("function leftNeighbour($p in Philosopher) =");
      _builder_5.newLine();
      _builder_5.append("\t\t");
      _builder_5.append("switch($p)");
      _builder_5.newLine();
      _builder_5.append("\t\t\t");
      _builder_5.append("case philo1: philo2");
      _builder_5.newLine();
      _builder_5.append("\t\t\t");
      _builder_5.append("case philo2: philo1");
      _builder_5.newLine();
      _builder_5.append("\t\t");
      _builder_5.append("endswitch");
      _builder_5.newLine();
      _builder_5.newLine();
      result = this.parseHelper.parse(_builder_5);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_DEFINITION, ErrorCode.FUNCTION_DEFINITION__FUNCTION_NOT_STATIC_DERIVED);
      StringConcatenation _builder_6 = new StringConcatenation();
      _builder_6.append("asm prova\t\t\t\t");
      _builder_6.newLine();
      _builder_6.append("signature:");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("abstract domain Philosopher\t\t\t\t");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("static leftNeighbour: Philosopher -> Philosopher");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("static philo1: Philosopher");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("static philo2: Philosopher");
      _builder_6.newLine();
      _builder_6.append("definitions:");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("function leftNeighbour($p in Philosopher, $p in Philosopher ) =");
      _builder_6.newLine();
      _builder_6.append("\t\t");
      _builder_6.append("switch($p)");
      _builder_6.newLine();
      _builder_6.append("\t\t\t");
      _builder_6.append("case philo1: philo2");
      _builder_6.newLine();
      _builder_6.append("\t\t\t");
      _builder_6.append("case philo2: philo1");
      _builder_6.newLine();
      _builder_6.append("\t\t");
      _builder_6.append("endswitch");
      _builder_6.newLine();
      _builder_6.newLine();
      result = this.parseHelper.parse(_builder_6);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_DEFINITION, ErrorCode.FUNCTION_DEFINITION__INVALID_VARIABLE);
      StringConcatenation _builder_7 = new StringConcatenation();
      _builder_7.append("asm prova\t");
      _builder_7.newLine();
      _builder_7.append("import StandardLibrary\t\t\t\t");
      _builder_7.newLine();
      _builder_7.append("signature:");
      _builder_7.newLine();
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("dynamic abstract domain Library");
      _builder_7.newLine();
      _builder_7.newLine();
      _builder_7.append("    ");
      _builder_7.append("domain Isbn   \t\t subsetof String");
      _builder_7.newLine();
      _builder_7.append("    ");
      _builder_7.append("domain Title  \t\t subsetof String");
      _builder_7.newLine();
      _builder_7.append(" \t");
      _builder_7.append("domain AuthorSurname subsetof String");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("domain AuthorName    subsetof String");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("domain CopiesNumber  subsetof Natural");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("domain Book subsetof Prod( Isbn, Title, AuthorSurname, AuthorName, CopiesNumber)");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("dynamic controlled bookIsbn : Book -> Isbn\t\t");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("dynamic controlled libraryBooks: Library -> Powerset(Book)\t");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("derived bookExists: Prod( Book, Library) -> Boolean");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("derived bookExists: Prod( Book, Library) -> Boolean");
      _builder_7.newLine();
      _builder_7.append("definitions:");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("function bookExists( $b in String, $l in Library) =");
      _builder_7.newLine();
      _builder_7.append("\t\t\t");
      _builder_7.append("let ( $books = libraryBooks( $l ), $isbn = bookIsbn( $b ) ) in");
      _builder_7.newLine();
      _builder_7.append("\t\t\t\t");
      _builder_7.append("if ( exist $c in $books with bookIsbn( $c ) = $isbn ) then true");
      _builder_7.newLine();
      _builder_7.append("\t\t\t\t");
      _builder_7.append("else false");
      _builder_7.newLine();
      _builder_7.append("\t\t\t\t");
      _builder_7.append("endif");
      _builder_7.newLine();
      _builder_7.append("\t\t\t");
      _builder_7.append("endlet");
      _builder_7.newLine();
      _builder_7.newLine();
      result = this.parseHelper.parse(_builder_7);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_DEFINITION, ErrorCode.SIGNATURE__FUNCTION_NOT_FOUND);
      StringConcatenation _builder_8 = new StringConcatenation();
      _builder_8.append("asm prova");
      _builder_8.newLine();
      _builder_8.append("import StandardLibrary\t\t\t\t\t");
      _builder_8.newLine();
      _builder_8.append("signature:");
      _builder_8.newLine();
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("dynamic abstract domain Library");
      _builder_8.newLine();
      _builder_8.newLine();
      _builder_8.append("    ");
      _builder_8.append("domain Isbn   \t\t subsetof String");
      _builder_8.newLine();
      _builder_8.append("    ");
      _builder_8.append("domain Title  \t\t subsetof String");
      _builder_8.newLine();
      _builder_8.append(" \t");
      _builder_8.append("domain AuthorSurname subsetof String ");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("domain AuthorName    subsetof String");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("domain CopiesNumber  subsetof Natural");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("domain Book subsetof Prod( Isbn, Title, AuthorSurname, AuthorName, CopiesNumber)");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("dynamic controlled bookIsbn : Book -> Isbn\t\t");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("dynamic controlled libraryBooks: Library -> Powerset(Book)\t");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("derived bookExists: Prod( Book, Library) -> Boolean");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.newLine();
      _builder_8.append("definitions:");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("function bookExists( $b in Book, $l in Library) = \"prova\"");
      _builder_8.newLine();
      result = this.parseHelper.parse(_builder_8);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_DEFINITION, ErrorCode.FUNCTION_DEFINITION__ILL_FORMED_BODY);
      StringConcatenation _builder_9 = new StringConcatenation();
      _builder_9.append("asm prova");
      _builder_9.newLine();
      _builder_9.append("import StandardLibrary\t\t\t\t\t");
      _builder_9.newLine();
      _builder_9.append("signature:");
      _builder_9.newLine();
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("dynamic abstract domain Library");
      _builder_9.newLine();
      _builder_9.newLine();
      _builder_9.append("    ");
      _builder_9.append("domain Isbn   \t\t subsetof String");
      _builder_9.newLine();
      _builder_9.append("    ");
      _builder_9.append("domain Title  \t\t subsetof String");
      _builder_9.newLine();
      _builder_9.append(" \t");
      _builder_9.append("domain AuthorSurname subsetof String");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("domain AuthorName    subsetof String");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("domain CopiesNumber  subsetof Natural");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("domain Book subsetof Prod( Isbn, Title, AuthorSurname, AuthorName, CopiesNumber)");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("dynamic controlled bookIsbn : Book -> Isbn\t\t");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("dynamic controlled libraryBooks: Library -> Powerset(Book)\t");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("derived bookExists: Prod( Book, Library) -> Boolean");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.newLine();
      _builder_9.append("definitions:");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("function bookExists( $b in Book, $l in Library) = ");
      _builder_9.newLine();
      _builder_9.append("\t\t");
      _builder_9.append("let ( $books = libraryBooks( $l ), $isbn = bookIsbn( $b ) ) in");
      _builder_9.newLine();
      _builder_9.append("\t\t\t");
      _builder_9.append("if ( exist $c in $books with bookIsbn( $c ) = $isbn ) then \"a\"");
      _builder_9.newLine();
      _builder_9.append("\t\t\t");
      _builder_9.append("else \"b\"");
      _builder_9.newLine();
      _builder_9.append("\t\t\t");
      _builder_9.append("endif");
      _builder_9.newLine();
      _builder_9.append("\t\t");
      _builder_9.append("endlet");
      _builder_9.newLine();
      result = this.parseHelper.parse(_builder_9);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_DEFINITION, ErrorCode.FUNCTION_DEFINITION__ILL_FORMED_BODY);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  @Tag("TestToMavenSkip")
  public void testRuleDeclaration() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova\t\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("import StandardLibrary\t\t");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain NumOfCherries subsetof Integer");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("abstract domain Philosopher\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("controlled cherriesInPlate: Philosopher -> NumOfCherries");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain NumOfCherries = {0 .. 3}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("rule r_philoRule($p in Philosopher) =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("if(cherriesInPlate($p) > 0) then");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("cherriesInPlate($p) := cherriesInPlate($p) - 1");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("else");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("cherriesInPlate($p) := cherriesInPlate($p) + 1");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("endif");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("rule r_philoRule($p in Philosopher) =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("if(cherriesInPlate($p) > 0) then");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("cherriesInPlate($p) := cherriesInPlate($p) - 1");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("else");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("cherriesInPlate($p) := cherriesInPlate($p) + 1");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("endif");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.RULE_DECLARATION, ErrorCode.RULE_DECLARATION__DEFINED_TWICE);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova\t\t");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("import StandardLibrary\t\t");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("domain NumOfCherries subsetof Integer");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("abstract domain Philosopher\t");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("controlled cherriesInPlate: Philosopher -> NumOfCherries");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("domain NumOfCherries = {0 .. 3}");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("rule r_philoRule($p in Philosopher, $p in Philosopher) =");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("if(cherriesInPlate($p) > 0) then");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("cherriesInPlate($p) := cherriesInPlate($p) - 1");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("else");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("cherriesInPlate($p) := cherriesInPlate($p) + 1");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("endif");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.RULE_DECLARATION, ErrorCode.RULE_DECLARATION__INVALID_VARIABLE);
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("asm prova\t\t");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("import StandardLibrary\t\t");
      _builder_2.newLine();
      _builder_2.append("signature:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("domain NumOfCherries subsetof Integer");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("abstract domain Philosopher\t");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("controlled cherriesInPlate: Philosopher -> NumOfCherries");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.newLine();
      _builder_2.append("definitions:");
      _builder_2.newLine();
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("domain NumOfCherries = {0 .. 3}");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("rule r_philoRule($p in PhilosopherNone) =");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("if(cherriesInPlate($p) > 0) then");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("cherriesInPlate($p) := cherriesInPlate($p) - 1");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("else");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("cherriesInPlate($p) := cherriesInPlate($p) + 1");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("endif");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.newLine();
      result = this.parseHelper.parse(_builder_2);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.RULE_DECLARATION, ErrorCode.SIGNATURE__DOMAIN_NOT_FOUND);
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("asm prova\t\t");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("import BodyLibrary\t\t");
      _builder_3.newLine();
      _builder_3.append("signature:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("domain NumOfCherries subsetof Integer");
      _builder_3.newLine();
      _builder_3.append("definitions:");
      _builder_3.newLine();
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("domain NumOfCherries = {0 .. 3}");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("rule r_philoRule($p in Integer) =");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("if(1 > 0) then");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("cherriesInPlate($p) := cherriesInPlate($p) - 1");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("else");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("cherriesInPlate($p) := cherriesInPlate($p) + 1");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("endif");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.newLine();
      result = this.parseHelper.parse(_builder_3);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.RULE_DECLARATION, ErrorCode.SIGNATURE__DOMAIN_NOT_IMPORTED);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  public void testInvariant() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("import StandardLibrary\t\t\t\t");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("definitions:\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("invariant over position: position(GO)=position(CA) implies position(GO)=position(FERRYMAN)");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.INVARIANT_ELEMENT, ErrorCode.INVARINT__NOT_FOUND);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova\t\t");
      _builder_1.newLine();
      _builder_1.append("import StandardLibrary\t\t");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("enum domain Actors = {FERRYMAN | GO | CA | WO}");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("enum domain Side = {LEFT | RIGHT}");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic controlled position: Actors -> Side");
      _builder_1.newLine();
      _builder_1.append("definitions:\t");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("invariant over position, position: position(GO)=position(CA) implies position(GO)=position(FERRYMAN)");
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.INVARIANT_ELEMENT, ErrorCode.INVARINT__CALLED_TWICE);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  @Tag("TestToMavenSkip")
  public void testTemporalSpec() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova\t\t");
      _builder.newLine();
      _builder.append("import StandardLibrary\t\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("definitions:\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("CTL prova : 6 > 5");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("CTL prova : 6 > 5");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.CTL_SPEC, ErrorCode.CTL_SPEC__DUPLICATE_NAME);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova\t");
      _builder_1.newLine();
      _builder_1.append("import StandardLibrary\t\t\t");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("definitions:\t");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("LTL prova : 6 > 5");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("LTL prova : 6 > 5");
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.LTL_SPEC, ErrorCode.LTL_SPEC__DUPLICATE_NAME);
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("asm prova\t\t");
      _builder_2.newLine();
      _builder_2.append("import StandardLibrary\t\t");
      _builder_2.newLine();
      _builder_2.append("signature:");
      _builder_2.newLine();
      _builder_2.append("definitions:\t");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("LTL prova : 6 > 5 ");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("LTL prova2 : 6 > 5");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("CTL prova : 6 > 5");
      _builder_2.newLine();
      result = this.parseHelper.parse(_builder_2);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("asm prova\t");
      _builder_3.newLine();
      _builder_3.append("import StandardLibrary\t\t\t");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("signature:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("definitions:\t");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("CTL prova : 6 + 5");
      _builder_3.newLine();
      result = this.parseHelper.parse(_builder_3);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.CTL_SPEC, ErrorCode.CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN);
      StringConcatenation _builder_4 = new StringConcatenation();
      _builder_4.append("asm prova\t");
      _builder_4.newLine();
      _builder_4.append("import StandardLibrary\t\t\t");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("signature:");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("definitions:\t");
      _builder_4.newLine();
      _builder_4.append("\t\t");
      _builder_4.append("JUSTICE 6 + 5");
      _builder_4.newLine();
      result = this.parseHelper.parse(_builder_4);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.JUSTICE_CONSTRAINT, ErrorCode.CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN);
      StringConcatenation _builder_5 = new StringConcatenation();
      _builder_5.append("asm prova\t\t");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("import StandardLibrary\t\t");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("signature:");
      _builder_5.newLine();
      _builder_5.append("\t\t");
      _builder_5.append("static alwaysTrue : Boolean");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("definitions:\t");
      _builder_5.newLine();
      _builder_5.append("\t\t");
      _builder_5.append("COMPASSION ( 6 + 5, alwaysTrue )");
      _builder_5.newLine();
      result = this.parseHelper.parse(_builder_5);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.COMPASSION_CONSTRAINT, ErrorCode.CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN);
      StringConcatenation _builder_6 = new StringConcatenation();
      _builder_6.append("asm prova\t");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("import StandardLibrary\t\t\t");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("signature:");
      _builder_6.newLine();
      _builder_6.append("\t\t");
      _builder_6.append("static alwaysTrue : Boolean");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("definitions:\t");
      _builder_6.newLine();
      _builder_6.append("\t\t");
      _builder_6.append("COMPASSION ( alwaysTrue, 6 + 5 )");
      _builder_6.newLine();
      result = this.parseHelper.parse(_builder_6);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.COMPASSION_CONSTRAINT, ErrorCode.CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN);
      StringConcatenation _builder_7 = new StringConcatenation();
      _builder_7.append("asm prova\t\t");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("import StandardLibrary\t\t");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("signature:");
      _builder_7.newLine();
      _builder_7.append("\t\t");
      _builder_7.append("static alwaysTrue : Boolean");
      _builder_7.newLine();
      _builder_7.append("\t\t");
      _builder_7.append("static notBoolean : String");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("definitions:\t");
      _builder_7.newLine();
      _builder_7.append("\t\t");
      _builder_7.append("COMPASSION ( notBoolean, alwaysTrue )");
      _builder_7.newLine();
      result = this.parseHelper.parse(_builder_7);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.COMPASSION_CONSTRAINT, ErrorCode.CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN);
      StringConcatenation _builder_8 = new StringConcatenation();
      _builder_8.append("asm prova\t\t");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("import StandardLibrary\t\t");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("signature:");
      _builder_8.newLine();
      _builder_8.append("\t\t");
      _builder_8.append("static alwaysTrue : Boolean");
      _builder_8.newLine();
      _builder_8.append("\t\t");
      _builder_8.append("static notBoolean : String");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("definitions:\t");
      _builder_8.newLine();
      _builder_8.append("\t\t");
      _builder_8.append("COMPASSION ( alwaysTrue, notBoolean )");
      _builder_8.newLine();
      result = this.parseHelper.parse(_builder_8);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.COMPASSION_CONSTRAINT, ErrorCode.CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN);
      StringConcatenation _builder_9 = new StringConcatenation();
      _builder_9.append("asm prova\t");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("import StandardLibrary\t\t\t");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("signature:");
      _builder_9.newLine();
      _builder_9.append("\t\t");
      _builder_9.append("static notBoolean : String");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("definitions:\t");
      _builder_9.newLine();
      _builder_9.append("\t\t");
      _builder_9.append("INVAR notBoolean");
      _builder_9.newLine();
      result = this.parseHelper.parse(_builder_9);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.INVARIANT_CONSTRAINT, ErrorCode.CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN);
      StringConcatenation _builder_10 = new StringConcatenation();
      _builder_10.append("asm prova\t");
      _builder_10.newLine();
      _builder_10.append("\t");
      _builder_10.append("import StandardLibrary\t\t\t");
      _builder_10.newLine();
      _builder_10.append("\t");
      _builder_10.append("signature:");
      _builder_10.newLine();
      _builder_10.append("\t\t");
      _builder_10.append("static notBoolean : String");
      _builder_10.newLine();
      _builder_10.append("\t");
      _builder_10.append("definitions:\t");
      _builder_10.newLine();
      _builder_10.append("\t\t");
      _builder_10.append("CTL prova : notBoolean");
      _builder_10.newLine();
      result = this.parseHelper.parse(_builder_10);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.CTL_SPEC, ErrorCode.CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN);
      StringConcatenation _builder_11 = new StringConcatenation();
      _builder_11.append("asm prova\t\t");
      _builder_11.newLine();
      _builder_11.append("\t");
      _builder_11.append("import StandardLibrary\t\t");
      _builder_11.newLine();
      _builder_11.append("\t");
      _builder_11.append("signature:");
      _builder_11.newLine();
      _builder_11.append("\t\t");
      _builder_11.append("static notBoolean : String");
      _builder_11.newLine();
      _builder_11.append("\t");
      _builder_11.append("definitions:\t");
      _builder_11.newLine();
      _builder_11.append("\t\t");
      _builder_11.append("JUSTICE notBoolean");
      _builder_11.newLine();
      result = this.parseHelper.parse(_builder_11);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.JUSTICE_CONSTRAINT, ErrorCode.CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN);
      StringConcatenation _builder_12 = new StringConcatenation();
      _builder_12.append("asm prova\t\t");
      _builder_12.newLine();
      _builder_12.append("\t");
      _builder_12.append("import StandardLibrary\t\t");
      _builder_12.newLine();
      _builder_12.append("\t");
      _builder_12.append("signature:");
      _builder_12.newLine();
      _builder_12.append("\t\t");
      _builder_12.append("static alwaysTrue : Boolean");
      _builder_12.newLine();
      _builder_12.append("\t\t");
      _builder_12.append("static notBoolean : String");
      _builder_12.newLine();
      _builder_12.append("\t");
      _builder_12.append("definitions:\t");
      _builder_12.newLine();
      _builder_12.append("\t\t");
      _builder_12.append("COMPASSION ( notBoolean, alwaysTrue )");
      _builder_12.newLine();
      result = this.parseHelper.parse(_builder_12);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.COMPASSION_CONSTRAINT, ErrorCode.CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN);
      StringConcatenation _builder_13 = new StringConcatenation();
      _builder_13.append("asm prova\t\t");
      _builder_13.newLine();
      _builder_13.append("\t");
      _builder_13.append("import StandardLibrary\t\t");
      _builder_13.newLine();
      _builder_13.append("\t");
      _builder_13.append("signature:");
      _builder_13.newLine();
      _builder_13.append("\t\t");
      _builder_13.append("static alwaysTrue : Boolean");
      _builder_13.newLine();
      _builder_13.append("\t");
      _builder_13.append("definitions:\t");
      _builder_13.newLine();
      _builder_13.append("\t\t");
      _builder_13.append("COMPASSION ( alwaysTrue, notBoolean )");
      _builder_13.newLine();
      result = this.parseHelper.parse(_builder_13);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.COMPASSION_CONSTRAINT, ErrorCode.CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN);
      StringConcatenation _builder_14 = new StringConcatenation();
      _builder_14.append("asm prova\t\t");
      _builder_14.newLine();
      _builder_14.append("\t");
      _builder_14.append("import StandardLibrary\t\t");
      _builder_14.newLine();
      _builder_14.append("\t");
      _builder_14.append("signature:");
      _builder_14.newLine();
      _builder_14.append("\t\t");
      _builder_14.append("static alwaysTrue : Boolean");
      _builder_14.newLine();
      _builder_14.append("\t");
      _builder_14.append("definitions:\t");
      _builder_14.newLine();
      _builder_14.append("\t\t");
      _builder_14.append("INVAR notBoolean");
      _builder_14.newLine();
      result = this.parseHelper.parse(_builder_14);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.INVARIANT_CONSTRAINT, ErrorCode.CONSTRAINT_DOMAIN_BODY_NOT_BOOLEAN);
      StringConcatenation _builder_15 = new StringConcatenation();
      _builder_15.append("asm prova\t");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("import StandardLibrary\t\t");
      _builder_15.newLine();
      _builder_15.append("signature:");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("static position : Integer");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("static alwaysTrue : Boolean");
      _builder_15.newLine();
      _builder_15.append("definitions:");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("INVAR alwaysTrue");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("JUSTICE alwaysTrue");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("COMPASSION ( alwaysTrue, alwaysTrue )");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("invariant over position: alwaysTrue");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("CTL prova : alwaysTrue\t");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("LTL prova : alwaysTrue");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.newLine();
      result = this.parseHelper.parse(_builder_15);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_16 = new StringConcatenation();
      _builder_16.append("asm prova\t");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("import StandardLibrary\t\t");
      _builder_16.newLine();
      _builder_16.append("signature:");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("static position : Integer");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("static alwaysTrue : Integer -> Boolean");
      _builder_16.newLine();
      _builder_16.append("definitions:");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("INVAR alwaysTrue(1)");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("JUSTICE alwaysTrue(1)");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("COMPASSION ( alwaysTrue(1), alwaysTrue(1) )");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("invariant over position: alwaysTrue(1)");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("CTL prova : alwaysTrue(1)\t");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("LTL prova : alwaysTrue(1)");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.newLine();
      result = this.parseHelper.parse(_builder_16);
      this._validationTestHelper.assertNoErrors(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
