package org.asmeta.xt.tests.parsing.negative;

import com.google.inject.Inject;
import org.asmeta.xt.asmetal.Asm;
import org.asmeta.xt.asmetal.AsmetalPackage;
import org.asmeta.xt.tests.AsmParseHelper;
import org.asmeta.xt.tests.AsmetaLInjectorProvider;
import org.asmeta.xt.validation.ErrorCode;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(AsmetaLInjectorProvider.class)
@SuppressWarnings("all")
public class InizializationNegativeParsingTest {
  @Inject
  private AsmParseHelper parseHelper;

  @Inject
  @Extension
  private ValidationTestHelper _validationTestHelper;

  @Test
  @Tag("TestToMavenSkip")
  public void testInizialization() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.append("default init s0:");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.INITIALIZATION, ErrorCode.INITILIZATION_EMPTY_INIT);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  @Tag("TestToMavenSkip")
  public void testDomainInizialization() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("import StandardLibrary");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic domain NumOfCherries subsetof Integer");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.append("default init s0:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain NumOfCherries = {0 : 3} ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain NumOfCherries = {0 : 5} ");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.DOMAIN_INITIALIZATION, ErrorCode.DOMAIN_INIZIALIZATION__DEFINED_TWICE);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.append("default init s0:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("domain NumOfCherries = {0 : 3} ");
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.DOMAIN_INITIALIZATION, ErrorCode.SIGNATURE__DOMAIN_NOT_FOUND);
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("asm prova");
      _builder_2.newLine();
      _builder_2.append("import StandardLibrary");
      _builder_2.newLine();
      _builder_2.append("signature:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("domain NumOfCherries subsetof Integer");
      _builder_2.newLine();
      _builder_2.append("definitions:");
      _builder_2.newLine();
      _builder_2.append("default init s0:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("domain NumOfCherries = {0 : 3}");
      _builder_2.newLine();
      result = this.parseHelper.parse(_builder_2);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.DOMAIN_INITIALIZATION, ErrorCode.DOMAIN_INIZIALIZATION__IS_STATIC);
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("asm prova");
      _builder_3.newLine();
      _builder_3.append("import StandardLibrary");
      _builder_3.newLine();
      _builder_3.append("signature:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_3.newLine();
      _builder_3.append("definitions:");
      _builder_3.newLine();
      _builder_3.append("default init s0:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("domain NumOfCherries = {0 : 3} ");
      _builder_3.newLine();
      result = this.parseHelper.parse(_builder_3);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_4 = new StringConcatenation();
      _builder_4.append("asm prova");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("import StandardLibrary");
      _builder_4.newLine();
      _builder_4.append("signature:");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_4.newLine();
      _builder_4.append("definitions:");
      _builder_4.newLine();
      _builder_4.append("default init s0:");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("domain NumOfCherries = \"A\"");
      _builder_4.newLine();
      result = this.parseHelper.parse(_builder_4);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.DOMAIN_INITIALIZATION, ErrorCode.DOMAIN_INIZIALIZATION__ILL_FORMED_BODY);
      StringConcatenation _builder_5 = new StringConcatenation();
      _builder_5.append("asm prova");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("import StandardLibrary");
      _builder_5.newLine();
      _builder_5.append("signature:");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_5.newLine();
      _builder_5.append("definitions:");
      _builder_5.newLine();
      _builder_5.append("default init s0:");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("domain NumOfCherries = { 1 : \"Z\" }");
      _builder_5.newLine();
      result = this.parseHelper.parse(_builder_5);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__DIFFERENT_DOMAINS);
      StringConcatenation _builder_6 = new StringConcatenation();
      _builder_6.append("asm prova");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("import StandardLibrary");
      _builder_6.newLine();
      _builder_6.append("signature:");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_6.newLine();
      _builder_6.append("definitions:");
      _builder_6.newLine();
      _builder_6.append("default init s0:");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("domain NumOfCherries = { \"A\" : 5 }");
      _builder_6.newLine();
      result = this.parseHelper.parse(_builder_6);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__DIFFERENT_DOMAINS);
      StringConcatenation _builder_7 = new StringConcatenation();
      _builder_7.append("asm prova");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("import StandardLibrary");
      _builder_7.newLine();
      _builder_7.append("signature:");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_7.newLine();
      _builder_7.append("definitions:");
      _builder_7.newLine();
      _builder_7.append("default init s0:");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("domain NumOfCherries = { 1, 2, 5.4 }");
      _builder_7.newLine();
      result = this.parseHelper.parse(_builder_7);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__DIFFERENT_DOMAINS);
      StringConcatenation _builder_8 = new StringConcatenation();
      _builder_8.append("asm prova");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("import StandardLibrary");
      _builder_8.newLine();
      _builder_8.append("signature:");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_8.newLine();
      _builder_8.append("definitions:");
      _builder_8.newLine();
      _builder_8.append("default init s0:");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("domain NumOfCherries = { \"A\" : \"Z\" }");
      _builder_8.newLine();
      result = this.parseHelper.parse(_builder_8);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.DOMAIN_INITIALIZATION, ErrorCode.DOMAIN_INIZIALIZATION__ILL_FORMED_BODY);
      StringConcatenation _builder_9 = new StringConcatenation();
      _builder_9.append("asm prova");
      _builder_9.newLine();
      _builder_9.append("signature:");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_9.newLine();
      _builder_9.append("definitions:");
      _builder_9.newLine();
      _builder_9.append("default init s0:");
      _builder_9.newLine();
      _builder_9.append("\t");
      _builder_9.append("domain NumOfCherries = {}");
      _builder_9.newLine();
      result = this.parseHelper.parse(_builder_9);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__ANY_DOMAIN_NOT_DECLARED);
      StringConcatenation _builder_10 = new StringConcatenation();
      _builder_10.append("asm prova");
      _builder_10.newLine();
      _builder_10.append("\t");
      _builder_10.append("import StandardLibrary");
      _builder_10.newLine();
      _builder_10.append("signature:");
      _builder_10.newLine();
      _builder_10.append("\t");
      _builder_10.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_10.newLine();
      _builder_10.append("definitions:");
      _builder_10.newLine();
      _builder_10.append("default init s0:");
      _builder_10.newLine();
      _builder_10.append("\t");
      _builder_10.append("domain NumOfCherries = {}");
      _builder_10.newLine();
      result = this.parseHelper.parse(_builder_10);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_11 = new StringConcatenation();
      _builder_11.append("asm prova");
      _builder_11.newLine();
      _builder_11.append("\t");
      _builder_11.append("import StandardLibrary");
      _builder_11.newLine();
      _builder_11.append("signature:");
      _builder_11.newLine();
      _builder_11.append("\t");
      _builder_11.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_11.newLine();
      _builder_11.append("definitions:");
      _builder_11.newLine();
      _builder_11.append("default init s0:");
      _builder_11.newLine();
      _builder_11.append("\t");
      _builder_11.append("domain NumOfCherries = { 1, 2, 3 }");
      _builder_11.newLine();
      result = this.parseHelper.parse(_builder_11);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_12 = new StringConcatenation();
      _builder_12.append("asm prova");
      _builder_12.newLine();
      _builder_12.append("\t");
      _builder_12.append("import StandardLibrary");
      _builder_12.newLine();
      _builder_12.append("signature:");
      _builder_12.newLine();
      _builder_12.append("\t");
      _builder_12.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_12.newLine();
      _builder_12.append("definitions:");
      _builder_12.newLine();
      _builder_12.append("default init s0:");
      _builder_12.newLine();
      _builder_12.append("\t");
      _builder_12.append("domain NumOfCherries = { 1, 2, 2, 3 }");
      _builder_12.newLine();
      result = this.parseHelper.parse(_builder_12);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__ADDED_TWICE);
      StringConcatenation _builder_13 = new StringConcatenation();
      _builder_13.append("asm prova");
      _builder_13.newLine();
      _builder_13.append("\t");
      _builder_13.append("import StandardLibrary");
      _builder_13.newLine();
      _builder_13.append("signature:");
      _builder_13.newLine();
      _builder_13.append("\t");
      _builder_13.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_13.newLine();
      _builder_13.append("definitions:");
      _builder_13.newLine();
      _builder_13.append("default init s0:");
      _builder_13.newLine();
      _builder_13.append("\t");
      _builder_13.append("domain NumOfCherries = { 1 : 1 }");
      _builder_13.newLine();
      result = this.parseHelper.parse(_builder_13);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__ADDED_TWICE);
      StringConcatenation _builder_14 = new StringConcatenation();
      _builder_14.append("asm prova");
      _builder_14.newLine();
      _builder_14.append("\t");
      _builder_14.append("import StandardLibrary");
      _builder_14.newLine();
      _builder_14.append("signature:");
      _builder_14.newLine();
      _builder_14.append("\t");
      _builder_14.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_14.newLine();
      _builder_14.append("definitions:");
      _builder_14.newLine();
      _builder_14.append("default init s0:");
      _builder_14.newLine();
      _builder_14.append("\t");
      _builder_14.append("domain NumOfCherries = { 1 : 15, 2 }");
      _builder_14.newLine();
      result = this.parseHelper.parse(_builder_14);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_15 = new StringConcatenation();
      _builder_15.append("asm prova");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("import StandardLibrary");
      _builder_15.newLine();
      _builder_15.append("signature:");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_15.newLine();
      _builder_15.append("definitions:");
      _builder_15.newLine();
      _builder_15.append("default init s0:");
      _builder_15.newLine();
      _builder_15.append("\t");
      _builder_15.append("domain NumOfCherries = { 1 .. 15, +2 }");
      _builder_15.newLine();
      result = this.parseHelper.parse(_builder_15);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_16 = new StringConcatenation();
      _builder_16.append("asm prova");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("import StandardLibrary");
      _builder_16.newLine();
      _builder_16.append("signature:");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_16.newLine();
      _builder_16.append("definitions:");
      _builder_16.newLine();
      _builder_16.append("default init s0:");
      _builder_16.newLine();
      _builder_16.append("\t");
      _builder_16.append("domain NumOfCherries = { 1 .. 15, -2 }");
      _builder_16.newLine();
      result = this.parseHelper.parse(_builder_16);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__STEP_NEGATIVE);
      StringConcatenation _builder_17 = new StringConcatenation();
      _builder_17.append("asm prova");
      _builder_17.newLine();
      _builder_17.append("\t");
      _builder_17.append("import StandardLibrary");
      _builder_17.newLine();
      _builder_17.append("signature:");
      _builder_17.newLine();
      _builder_17.append("\t");
      _builder_17.append("dynamic domain NumOfCherries subsetof Integer");
      _builder_17.newLine();
      _builder_17.append("definitions:");
      _builder_17.newLine();
      _builder_17.append("default init s0:");
      _builder_17.newLine();
      _builder_17.append("\t");
      _builder_17.append("domain NumOfCherries = { 1 .. 15, \"A\" }");
      _builder_17.newLine();
      result = this.parseHelper.parse(_builder_17);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.SET_TERM, ErrorCode.SET_TERM__STEP_NAN);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  @Tag("TestToMavenSkip")
  public void testFunctionInizialization() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("enum domain Actors = {FERRYMAN | GO | CA | WO}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("enum domain Side = {LEFT | RIGHT}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic controlled position: Actors -> Side");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.append("default init s0:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("function position($a in Actors) = LEFT");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("function position($a in Actors) = RIGHT\t\t\t\t");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_INITIALIZATION, ErrorCode.FUNCTION_INIZIALIZATION__DEFINED_TWICE);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("enum domain Actors = {FERRYMAN | GO | CA | WO}");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("enum domain Side = {LEFT | RIGHT}");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic controlled position: Prod(Actors,Actors) -> Side");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.append("default init s0:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("function position($a in Actors, $a in Actors) = LEFT");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_INITIALIZATION, ErrorCode.FUNCTION_INIZIALIZATION__INVALID_VARIABLE);
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("asm prova");
      _builder_2.newLine();
      _builder_2.append("signature:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("enum domain Actors = {FERRYMAN | GO | CA | WO}");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("enum domain Side = {LEFT | RIGHT}");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("dynamic controlled position: Prod(Actors,Actors) -> Side");
      _builder_2.newLine();
      _builder_2.append("definitions:");
      _builder_2.newLine();
      _builder_2.append("default init s0:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("function position($a in Actors, $b in Actors) = LEFT");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.newLine();
      result = this.parseHelper.parse(_builder_2);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("asm prova");
      _builder_3.newLine();
      _builder_3.append("signature:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("enum domain Actors = {FERRYMAN | GO | CA | WO}");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("enum domain Side = {LEFT | RIGHT}");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("dynamic controlled position: Actors -> Side");
      _builder_3.newLine();
      _builder_3.append("definitions:");
      _builder_3.newLine();
      _builder_3.append("default init s0:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("function position($a in ActorsNone) = LEFT\t\t\t\t");
      _builder_3.newLine();
      result = this.parseHelper.parse(_builder_3);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_INITIALIZATION, ErrorCode.SIGNATURE__DOMAIN_NOT_FOUND);
      StringConcatenation _builder_4 = new StringConcatenation();
      _builder_4.append("asm prova");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("import BodyLibrary");
      _builder_4.newLine();
      _builder_4.append("signature:");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("enum domain Actors = {FERRYMAN | GO | CA | WO}");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("enum domain Side = {LEFT | RIGHT}");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("dynamic controlled position: Integer -> Side");
      _builder_4.newLine();
      _builder_4.append("definitions:");
      _builder_4.newLine();
      _builder_4.append("default init s0:");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("function position($a in Integer) = LEFT\t\t\t\t");
      _builder_4.newLine();
      result = this.parseHelper.parse(_builder_4);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_INITIALIZATION, ErrorCode.SIGNATURE__DOMAIN_NOT_IMPORTED);
      StringConcatenation _builder_5 = new StringConcatenation();
      _builder_5.append("asm prova");
      _builder_5.newLine();
      _builder_5.append("signature:");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("enum domain Actors = {FERRYMAN | GO | CA | WO}");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("enum domain Side = {LEFT | RIGHT}");
      _builder_5.newLine();
      _builder_5.append("definitions:");
      _builder_5.newLine();
      _builder_5.append("default init s0:");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("function position($a in Actors) = LEFT");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.newLine();
      result = this.parseHelper.parse(_builder_5);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_INITIALIZATION, ErrorCode.SIGNATURE__FUNCTION_NOT_FOUND);
      StringConcatenation _builder_6 = new StringConcatenation();
      _builder_6.append("asm prova");
      _builder_6.newLine();
      _builder_6.append("signature:");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("enum domain Actors = {FERRYMAN | GO | CA | WO}");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("enum domain Side = {LEFT | RIGHT}");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("static position: Actors -> Side");
      _builder_6.newLine();
      _builder_6.append("definitions:");
      _builder_6.newLine();
      _builder_6.append("default init s0:");
      _builder_6.newLine();
      _builder_6.append("\t");
      _builder_6.append("function position($a in Actors) = LEFT\t\t\t\t");
      _builder_6.newLine();
      result = this.parseHelper.parse(_builder_6);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_INITIALIZATION, ErrorCode.FUNCTION_INIZIALIZATION__FUNCTION_NOT_DYNAMIC);
      StringConcatenation _builder_7 = new StringConcatenation();
      _builder_7.append("asm prova");
      _builder_7.newLine();
      _builder_7.append("signature:");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("enum domain Actors = {FERRYMAN | GO | CA | WO}");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("enum domain Side = {LEFT | RIGHT}");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("dynamic controlled  position: Actors -> Side");
      _builder_7.newLine();
      _builder_7.append("definitions:");
      _builder_7.newLine();
      _builder_7.append("default init s0:");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("function position($a in Actors) = LEFT");
      _builder_7.newLine();
      _builder_7.append("init s1:");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.append("function position($a in Actors) = RIGHT");
      _builder_7.newLine();
      _builder_7.append("\t");
      _builder_7.newLine();
      result = this.parseHelper.parse(_builder_7);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_8 = new StringConcatenation();
      _builder_8.append("asm prova");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("import StandardLibrary");
      _builder_8.newLine();
      _builder_8.append("signature:");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("enum domain Actors = {FERRYMAN | GO | CA | WO}");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("enum domain Side = {LEFT | RIGHT}");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("dynamic controlled  position: Actors -> Side");
      _builder_8.newLine();
      _builder_8.append("definitions:");
      _builder_8.newLine();
      _builder_8.append("default init s0:");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.append("function position($a in Actors) = \"prova\"");
      _builder_8.newLine();
      _builder_8.append("\t");
      _builder_8.newLine();
      result = this.parseHelper.parse(_builder_8);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FUNCTION_INITIALIZATION, ErrorCode.FUNCTION_INIZIALIZATION__ILL_FORMED_BODY);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  @Tag("TestToMavenSkip")
  public void testAgentInizialization() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("import StandardLibrary");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic domain Person subsetof Agent");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic controlled age: Person -> Natural");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic controlled alive: Person -> Boolean\t\t\t\t");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("rule r_dead =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("choose $x in {1 .. 100} with true do");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("if($x > 95) then");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("alive(self) := false");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("endif");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("rule r_lifeRule =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("par");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("age(self) := age(self) + 1n");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("r_dead[]");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("endpar   ");
      _builder.newLine();
      _builder.append("default init s0:");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("agent Person:");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("r_lifeRule[]\t\t");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova");
      _builder_1.newLine();
      _builder_1.append("import StandardLibrary");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic domain Person subsetof Integer");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic controlled age: Person -> Natural");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic controlled alive: Person -> Boolean\t\t\t\t");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("rule r_dead =");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("choose $x in {1 .. 100} with true do");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("if($x > 95) then");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("alive(self) := false");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("endif");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("rule r_lifeRule =");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("par");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("age(self) := age(self) + 1n");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("r_dead[]");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("endpar");
      _builder_1.newLine();
      _builder_1.append("default init s0:");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("agent Person:");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("r_lifeRule[]\t\t");
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.AGENT_INITIALIZATION, ErrorCode.AGENT_INIZIALIZATION__INVALID_DOMAIN);
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("asm prova");
      _builder_2.newLine();
      _builder_2.append("import StandardLibrary");
      _builder_2.newLine();
      _builder_2.append("signature:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("dynamic controlled age: Person -> Natural");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("dynamic controlled alive: Person -> Boolean\t\t\t\t");
      _builder_2.newLine();
      _builder_2.append("definitions:");
      _builder_2.newLine();
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("rule r_dead =");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("choose $x in {1 .. 100} with true do");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("if($x > 95) then");
      _builder_2.newLine();
      _builder_2.append("\t\t\t\t");
      _builder_2.append("alive(self) := false");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("endif");
      _builder_2.newLine();
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("rule r_lifeRule =");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("par");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("age(self) := age(self) + 1n");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("r_dead[]");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("endpar");
      _builder_2.newLine();
      _builder_2.append("default init s0:");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("agent Person:");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("r_lifeRule[]\t\t");
      _builder_2.newLine();
      result = this.parseHelper.parse(_builder_2);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.AGENT_INITIALIZATION, ErrorCode.SIGNATURE__DOMAIN_NOT_FOUND);
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("asm prova");
      _builder_3.newLine();
      _builder_3.append("signature:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("dynamic domain Person subsetof Agent");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("dynamic controlled age: Person -> Natural");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("dynamic controlled alive: Person -> Boolean\t\t\t\t");
      _builder_3.newLine();
      _builder_3.append("definitions:");
      _builder_3.newLine();
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("rule r_dead =");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("choose $x in {1 .. 100} with true do");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("if($x > 95) then");
      _builder_3.newLine();
      _builder_3.append("\t\t\t\t");
      _builder_3.append("alive(self) := false");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("endif");
      _builder_3.newLine();
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("rule r_lifeRule =");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("par");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("age(self) := age(self) + 1n");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("r_dead[]");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("endpar");
      _builder_3.newLine();
      _builder_3.append("default init s0:");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("agent Person:");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("r_lifeRule[]\t\t");
      _builder_3.newLine();
      result = this.parseHelper.parse(_builder_3);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.AGENT_INITIALIZATION, ErrorCode.AGENT_INIZIALIZATION__AGENT_DOMAIN_NOT_DECLARED);
      StringConcatenation _builder_4 = new StringConcatenation();
      _builder_4.append("asm prova");
      _builder_4.newLine();
      _builder_4.append("import StandardLibrary");
      _builder_4.newLine();
      _builder_4.append("signature:");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("dynamic domain Person subsetof Agent");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("dynamic controlled age: Person -> Natural");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("dynamic controlled alive: Person -> Boolean\t\t\t\t");
      _builder_4.newLine();
      _builder_4.append("definitions:");
      _builder_4.newLine();
      _builder_4.append("default init s0:");
      _builder_4.newLine();
      _builder_4.append("\t\t");
      _builder_4.append("agent Person:");
      _builder_4.newLine();
      _builder_4.append("\t\t\t");
      _builder_4.append("r_lifeRule[]\t\t");
      _builder_4.newLine();
      result = this.parseHelper.parse(_builder_4);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.AGENT_INITIALIZATION, ErrorCode.AGENT_INIZIALIZATION__PROGRAM_NOT_FOUND);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
