package org.asmeta.xt.tests.parsing.negative;

import com.google.inject.Inject;
import org.asmeta.xt.asmetal.Asm;
import org.asmeta.xt.asmetal.AsmetalPackage;
import org.asmeta.xt.tests.AsmetaLInjectorProvider;
import org.asmeta.xt.validation.ErrorCode;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(AsmetaLInjectorProvider.class)
@SuppressWarnings("all")
public class RuleNegativeParsingTest {
  @Inject
  private ParseHelper<Asm> parseHelper;

  @Inject
  @Extension
  private ValidationTestHelper _validationTestHelper;

  @Test
  @Tag("TestToMavenSkip")
  public void testUpdateRule() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("import StandardLibrary");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic domain Person subsetof Agent");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic controlled alive: Person -> Boolean");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("rule r_dead =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("choose $x in {1 .. 100} with true do");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("if($x > 95) then");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("alive(self) := 5");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("endif");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.UPDATE_RULE, ErrorCode.UPDATE_RULE__DOMAINS_NOT_COMPATIBLE);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova");
      _builder_1.newLine();
      _builder_1.append("import StandardLibrary");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic domain Person subsetof Agent");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("static alive: Person -> Boolean");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("rule r_dead =");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("choose $x in {1 .. 100} with true do");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("if($x > 95) then");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("alive(self) := false");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("endif");
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.UPDATE_RULE, ErrorCode.LOCATION_TERM__NOT_DYNAMIC);
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("asm prova");
      _builder_2.newLine();
      _builder_2.append("import StandardLibrary");
      _builder_2.newLine();
      _builder_2.append("signature:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("dynamic domain Person subsetof Agent");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("controlled alive: Person -> Boolean");
      _builder_2.newLine();
      _builder_2.append("definitions:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("rule r_dead =");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("choose $x in {1 .. 100} with true do");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("if($x > 95) then");
      _builder_2.newLine();
      _builder_2.append("\t\t\t\t");
      _builder_2.append("alive(self) := false");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("endif");
      _builder_2.newLine();
      result = this.parseHelper.parse(_builder_2);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("asm prova");
      _builder_3.newLine();
      _builder_3.append("import StandardLibrary");
      _builder_3.newLine();
      _builder_3.append("signature:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("dynamic domain Person subsetof Agent");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("dynamic monitored alive: Person -> Boolean");
      _builder_3.newLine();
      _builder_3.append("definitions:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("rule r_dead =");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("choose $x in {1 .. 100} with true do");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("if($x > 95) then");
      _builder_3.newLine();
      _builder_3.append("\t\t\t\t");
      _builder_3.append("alive(self) := false");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("endif");
      _builder_3.newLine();
      result = this.parseHelper.parse(_builder_3);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.UPDATE_RULE, ErrorCode.UPDATE_RULE__INVALID_LOCATION);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  @Tag("TestToMavenSkip")
  public void testConditionalRule() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("\t");
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("import StandardLibrary");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("dynamic domain Person subsetof Agent");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("dynamic controlled alive: Person -> Boolean");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("rule r_dead =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("choose $x in {1 .. 100} with true do");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("if($x > 95) then");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("alive(self) := false");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("endif");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("\t");
      _builder_1.append("asm prova");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("import StandardLibrary");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("dynamic domain Person subsetof Agent");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("dynamic controlled alive: Person -> Boolean");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("rule r_dead =");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("choose $x in {1 .. 100} with true do");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("if($x + 95) then");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("alive(self) := false");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("endif");
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.CONDITIONAL_RULE, ErrorCode.TERM__DOMAIN_GUARD_NOT_BOOLEAN);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  @Tag("TestToMavenSkip")
  public void testLetRule() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("import StandardLibrary");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("abstract domain Philosopher");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("domain NumOfCherries subsetof Integer");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("controlled cherriesInPlate: Philosopher -> NumOfCherries");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("static leftNeighbour: Philosopher -> Philosopher");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("rule r_philoRule($p in Philosopher) =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("if(cherriesInPlate($p) > 0) then");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("cherriesInPlate($p) := cherriesInPlate($p) - 1");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("else");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("let($left=leftNeighbour($p)) in");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("if(cherriesInPlate($left) > 0) then");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("par");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("cherriesInPlate($left) := cherriesInPlate($left) - 1");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("cherriesInPlate($p) := cherriesInPlate($p) + 1");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("endpar");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("endif");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("endlet");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("endif");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova");
      _builder_1.newLine();
      _builder_1.append("import StandardLibrary");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("abstract domain Philosopher");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("domain NumOfCherries subsetof Integer");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("controlled cherriesInPlate: Philosopher -> NumOfCherries");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("static leftNeighbour: Philosopher -> Philosopher");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("rule r_philoRule($p in Philosopher) =");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("if(cherriesInPlate($p) > 0) then");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("cherriesInPlate($p) := cherriesInPlate($p) - 1");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("else");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("let($p=leftNeighbour($p)) in");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("if(cherriesInPlate($left) > 0) then");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t\t");
      _builder_1.append("par");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t\t\t");
      _builder_1.append("cherriesInPlate($left) := cherriesInPlate($left) - 1");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t\t\t");
      _builder_1.append("cherriesInPlate($p) := cherriesInPlate($p) + 1");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t\t");
      _builder_1.append("endpar");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("endif");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("endlet");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("endif");
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.LET_RULE, ErrorCode.LET_RULE__VARIABLE_ALREADY_USED);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  @Tag("TestToMavenSkip")
  public void testChooseRule() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("import StandardLibrary");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic domain Person subsetof Agent");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic controlled alive: Person -> Boolean");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("rule r_dead =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("choose $x in {1 .. 100} with true do");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("if($x > 95) then");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("alive(self) := false");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("endif");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova");
      _builder_1.newLine();
      _builder_1.append("import StandardLibrary");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic domain Person subsetof Agent");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic controlled alive: Person -> Boolean");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("rule r_dead =");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("choose $x in [1 .. 100] with true do");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("if($x > 95) then");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("alive(self) := false");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("endif");
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.CHOOSE_RULE, ErrorCode.CHOOSE_RULE__RANGE_NOT_POWERSET);
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("asm prova");
      _builder_2.newLine();
      _builder_2.append("import StandardLibrary");
      _builder_2.newLine();
      _builder_2.append("signature:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("dynamic domain Person subsetof Agent");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("dynamic controlled alive: Person -> Boolean");
      _builder_2.newLine();
      _builder_2.append("definitions:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("rule r_dead =");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("let ( $x=5 ) in");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("choose $x in {1 .. 100} with true do");
      _builder_2.newLine();
      _builder_2.append("\t\t\t\t");
      _builder_2.append("if($x > 95) then");
      _builder_2.newLine();
      _builder_2.append("\t\t\t\t\t");
      _builder_2.append("alive(self) := false");
      _builder_2.newLine();
      _builder_2.append("\t\t\t\t");
      _builder_2.append("endif");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("endlet");
      _builder_2.newLine();
      result = this.parseHelper.parse(_builder_2);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.CHOOSE_RULE, ErrorCode.CHOOSE_RULE__VARIABLE_ALREADY_USED);
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("asm prova");
      _builder_3.newLine();
      _builder_3.append("import StandardLibrary");
      _builder_3.newLine();
      _builder_3.append("signature:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("dynamic domain Person subsetof Agent");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("dynamic controlled alive: Person -> Boolean");
      _builder_3.newLine();
      _builder_3.append("definitions:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("rule r_dead =");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("choose $x in {1 .. 100} with 5 + 6 do");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("if($x > 95) then");
      _builder_3.newLine();
      _builder_3.append("\t\t\t\t");
      _builder_3.append("alive(self) := false");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("endif");
      _builder_3.newLine();
      result = this.parseHelper.parse(_builder_3);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.CHOOSE_RULE, ErrorCode.TERM__DOMAIN_GUARD_NOT_BOOLEAN);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  @Tag("TestToMavenSkip")
  public void testForallRule() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("import StandardLibrary");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic domain Person subsetof Agent");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic controlled alive: Person -> Boolean");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("main rule r_Main =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("forall $p in Person with alive($p) do");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("program($p) ");
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova");
      _builder_1.newLine();
      _builder_1.append("import StandardLibrary");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic domain Person subsetof Agent");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic controlled alive: Person -> Boolean");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic controlled no_powerset : Person -> Person");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("main rule r_Main =");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("forall $p in no_powerset with alive($p) do");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("program($p) ");
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FORALL_RULE, ErrorCode.FORALL_RULE__RANGE_NOT_POWERSET);
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("asm prova");
      _builder_2.newLine();
      _builder_2.append("import StandardLibrary");
      _builder_2.newLine();
      _builder_2.append("signature:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("dynamic domain Person subsetof Agent");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("dynamic controlled alive: Person -> Boolean");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("controlled persona : Person");
      _builder_2.newLine();
      _builder_2.append("definitions:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("main rule r_Main =");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("let($p=persona) in");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("forall $p in Person with alive($p) do");
      _builder_2.newLine();
      _builder_2.append("\t\t\t\t");
      _builder_2.append("program($p) ");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("endlet");
      _builder_2.newLine();
      result = this.parseHelper.parse(_builder_2);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FORALL_RULE, ErrorCode.FORALL_RULE__VARIABLE_ALREADY_USED);
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("asm prova");
      _builder_3.newLine();
      _builder_3.append("import StandardLibrary");
      _builder_3.newLine();
      _builder_3.append("signature:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("dynamic domain Person subsetof Agent");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("dynamic controlled age: Person -> Integer");
      _builder_3.newLine();
      _builder_3.append("definitions:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("main rule r_Main =");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("forall $p in Person with age($p) do");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("program($p) ");
      _builder_3.newLine();
      result = this.parseHelper.parse(_builder_3);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.FORALL_RULE, ErrorCode.TERM__DOMAIN_GUARD_NOT_BOOLEAN);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  @Tag("TestToMavenSkip")
  public void testExtendRule() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("import StandardLibrary");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic domain Person subsetof Agent");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("enum domain GenderDomain = {MALE | FEMALE}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic controlled alive: Person -> Boolean");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("rule r_reproduce =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("choose $father in Person with alive($father) do");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("extend Person with $child do");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("choose $g in GenderDomain with true do");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("alive($child) := true");
      _builder.newLine();
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova");
      _builder_1.newLine();
      _builder_1.append("import StandardLibrary");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic domain Person subsetof Agent");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("enum domain GenderDomain = {MALE | FEMALE}");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic controlled alive: Person -> Boolean");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("rule r_reproduce =");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("choose $father in Person with alive($father) do");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("extend Person with $father do");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("choose $g in GenderDomain with true do");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t\t");
      _builder_1.append("alive($child) := true");
      _builder_1.newLine();
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.EXTEND_RULE, ErrorCode.EXTENDED_RULE__VARIABLE_ALREADY_USED);
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("asm prova");
      _builder_2.newLine();
      _builder_2.append("import StandardLibrary");
      _builder_2.newLine();
      _builder_2.append("signature:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("dynamic domain Person subsetof Integer");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("enum domain GenderDomain = {MALE | FEMALE}");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("dynamic controlled alive: Person -> Boolean");
      _builder_2.newLine();
      _builder_2.append("definitions:");
      _builder_2.newLine();
      _builder_2.append("\t");
      _builder_2.append("rule r_reproduce =");
      _builder_2.newLine();
      _builder_2.append("\t\t");
      _builder_2.append("choose $father in Person with alive($father) do");
      _builder_2.newLine();
      _builder_2.append("\t\t\t");
      _builder_2.append("extend Person with $child do");
      _builder_2.newLine();
      _builder_2.append("\t\t\t\t");
      _builder_2.append("choose $g in GenderDomain with true do");
      _builder_2.newLine();
      _builder_2.append("\t\t\t\t\t");
      _builder_2.append("alive($child) := true");
      _builder_2.newLine();
      _builder_2.newLine();
      result = this.parseHelper.parse(_builder_2);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.EXTEND_RULE, ErrorCode.EXTENDED_RULE__INVALID_DOMAIN);
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("asm prova");
      _builder_3.newLine();
      _builder_3.append("import StandardLibrary");
      _builder_3.newLine();
      _builder_3.append("signature:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("domain Person subsetof Agent");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("enum domain GenderDomain = {MALE | FEMALE}");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("dynamic controlled alive: Person -> Boolean");
      _builder_3.newLine();
      _builder_3.append("definitions:");
      _builder_3.newLine();
      _builder_3.append("\t");
      _builder_3.append("rule r_reproduce =");
      _builder_3.newLine();
      _builder_3.append("\t\t");
      _builder_3.append("choose $father in Person with alive($father) do");
      _builder_3.newLine();
      _builder_3.append("\t\t\t");
      _builder_3.append("extend Person with $child do");
      _builder_3.newLine();
      _builder_3.append("\t\t\t\t");
      _builder_3.append("choose $g in GenderDomain with true do");
      _builder_3.newLine();
      _builder_3.append("\t\t\t\t\t");
      _builder_3.append("alive($child) := true");
      _builder_3.newLine();
      _builder_3.newLine();
      result = this.parseHelper.parse(_builder_3);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.EXTEND_RULE, ErrorCode.EXTENDED_RULE__INVALID_DOMAIN);
      StringConcatenation _builder_4 = new StringConcatenation();
      _builder_4.append("asm prova");
      _builder_4.newLine();
      _builder_4.append("import StandardLibrary");
      _builder_4.newLine();
      _builder_4.append("signature:");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("dynamic domain Person subsetof Agent");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("enum domain GenderDomain = {MALE | FEMALE}");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("dynamic controlled alive: Person -> Boolean");
      _builder_4.newLine();
      _builder_4.append("definitions:");
      _builder_4.newLine();
      _builder_4.append("\t");
      _builder_4.append("rule r_reproduce =");
      _builder_4.newLine();
      _builder_4.append("\t\t");
      _builder_4.append("choose $father in Person with alive($father) do");
      _builder_4.newLine();
      _builder_4.append("\t\t\t");
      _builder_4.append("extend Integer with $child do");
      _builder_4.newLine();
      _builder_4.append("\t\t\t\t");
      _builder_4.append("choose $g in GenderDomain with true do");
      _builder_4.newLine();
      _builder_4.append("\t\t\t\t\t");
      _builder_4.append("alive($child) := true");
      _builder_4.newLine();
      _builder_4.newLine();
      result = this.parseHelper.parse(_builder_4);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.EXTEND_RULE, ErrorCode.EXTENDED_RULE__INVALID_DOMAIN);
      StringConcatenation _builder_5 = new StringConcatenation();
      _builder_5.append("asm prova");
      _builder_5.newLine();
      _builder_5.append("import StandardLibrary ( Boolean ) ");
      _builder_5.newLine();
      _builder_5.append("signature:");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("dynamic domain Person subsetof Agent");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("enum domain GenderDomain = {MALE | FEMALE}");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("dynamic controlled alive: Person -> Boolean");
      _builder_5.newLine();
      _builder_5.append("definitions:");
      _builder_5.newLine();
      _builder_5.append("\t");
      _builder_5.append("rule r_reproduce =");
      _builder_5.newLine();
      _builder_5.append("\t\t");
      _builder_5.append("choose $father in Person with alive($father) do");
      _builder_5.newLine();
      _builder_5.append("\t\t\t");
      _builder_5.append("extend Person with $child do");
      _builder_5.newLine();
      _builder_5.append("\t\t\t\t");
      _builder_5.append("choose $g in GenderDomain with true do");
      _builder_5.newLine();
      _builder_5.append("\t\t\t\t\t");
      _builder_5.append("alive($child) := true");
      _builder_5.newLine();
      _builder_5.newLine();
      result = this.parseHelper.parse(_builder_5);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.EXTEND_RULE, ErrorCode.EXTENDED_RULE__RESERVE_DOMAIN_NOT_DECLARED);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  @Tag("TestToMavenSkip")
  public void testCaseRule() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("import StandardLibrary");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("enum domain Actors = {FERRYMAN | GO | CA | WO}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("enum domain CarryDomain = {GOAT | CABBAGE | WOLF | NONE}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("enum domain Side = {LEFT | RIGHT}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic monitored carry: CarryDomain");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("dynamic controlled position: Actors -> Side");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("derived oppositeSide: Side -> Side");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.newLine();
      _builder.append("rule r_carry($a in Actors) =");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("position($a) := oppositeSide(position($a))");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("rule r_travel =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("switch(carry)");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("case GOAT: r_carry[GO]");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("case CABBAGE: r_carry[CA]");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("case WOLF: r_carry[WO]");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("case NONE:");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("position(FERRYMAN) := oppositeSide(position(FERRYMAN))");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("endswitch");
      _builder.newLine();
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova");
      _builder_1.newLine();
      _builder_1.append("import StandardLibrary");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("enum domain Actors = {FERRYMAN | GO | CA | WO}");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("enum domain CarryDomain = {GOAT | CABBAGE | WOLF | NONE}");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("enum domain Side = {LEFT | RIGHT}");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic monitored carry: CarryDomain");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("dynamic controlled position: Actors -> Side");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("derived oppositeSide: Side -> Side");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("rule r_carry($a in Actors) =");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("position($a) := oppositeSide(position($a))");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("rule r_travel =");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("switch(carry)");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("case GO: r_carry[GO]");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("case CABBAGE: r_carry[CA]");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("case WOLF: r_carry[WO]");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("case NONE:");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("position(FERRYMAN) := oppositeSide(position(FERRYMAN))");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("endswitch");
      _builder_1.newLine();
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.CASE_RULE, ErrorCode.CASE_RULE__BRANCH_DOMAIN_NOT_COMPATIBLE);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  @Test
  @Tag("TestToMavenSkip")
  public void testWhileRule() {
    try {
      Asm result = null;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("asm prova");
      _builder.newLine();
      _builder.append("import StandardLibrary");
      _builder.newLine();
      _builder.append("signature:");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("controlled contrC: Integer");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("monitored mon: Integer");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("monitored doWhile: Boolean");
      _builder.newLine();
      _builder.append("definitions:");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("main rule r_Main =");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("if( doWhile ) then ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("while( contrC < mon ) do");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("contrC := contrC + 1");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("else");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("contrC := 0");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("endif");
      _builder.newLine();
      _builder.newLine();
      result = this.parseHelper.parse(_builder);
      this._validationTestHelper.assertNoErrors(result);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("asm prova");
      _builder_1.newLine();
      _builder_1.append("import StandardLibrary");
      _builder_1.newLine();
      _builder_1.append("signature:");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("controlled contrC: Integer");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("monitored mon: Integer");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("monitored doWhile: Boolean");
      _builder_1.newLine();
      _builder_1.append("definitions:");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("main rule r_Main =");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("if( doWhile ) then ");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("while( contrC + mon ) do");
      _builder_1.newLine();
      _builder_1.append("\t\t\t\t");
      _builder_1.append("contrC := contrC + 1");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("else");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("contrC := 0");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("endif");
      _builder_1.newLine();
      _builder_1.newLine();
      result = this.parseHelper.parse(_builder_1);
      this._validationTestHelper.assertError(result, AsmetalPackage.Literals.TURBO_DERIVED_RULE, ErrorCode.TERM__DOMAIN_GUARD_NOT_BOOLEAN);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
