/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package asmeta.definitions.domains.validation;

import org.eclipse.emf.common.util.EList;

import asmeta.definitions.Invariant;
import asmeta.structure.Signature;

/**
 * A sample validator interface for {@link asmeta.definitions.domains.Domain}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DomainValidator {
	boolean validate();

	boolean validateConstraint(EList<Invariant> value);
	boolean validateSignature(Signature value);
}
