name: Build and Push CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test with Maven
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/experimental/asmetal2java/asmetal2java_codegen
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install dependencies
        working-directory: . /code/core
        run: mvn --batch-mode install -DskipTests

      - name: Build and test with Maven
        run: mvn --batch-mode clean verify

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: asmetal2java.jar
          path: ./dist/asmetal2java.jar
          retention-days: 1

