name: EvoAsmetaTG - Build and Deploy CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test with Maven
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/experimental/asmeta.evotest/evoAsmetaTG
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install dependencies
        working-directory: .
        run: mvn --batch-mode install -DskipTests
     
      - name: Install asmetal2java
        working-directory: ./code/experimental/asmetal2java/asmetal2java_codegen
        run: mvn --batch-mode install -DskipTests
     
      - name: Install junit2avalla
        working-directory: ./code/experimental/asmeta.evotest/junit2avalla
        run: mvn --batch-mode install -DskipTests
        
      - name: Test and Build with Maven
        run: mvn --batch-mode verify

      - name: Upload Artifact
        #if: github.ref == 'refs/heads/master' || github.event.pull_request.base.ref == 'master'
        uses: actions/upload-artifact@v4
        with:
          name: evoasmetatg.zip
          path: ./code/experimental/asmeta.evotest/evoAsmetaTG/dist/evoasmetatg.zip
          retention-days: 1
  
  deploy:
    name: Upload EvoAsmetaTG Release Asset
    needs: build
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/master' || github.event.pull_request.base.ref == 'master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: evoasmetatg.zip
          path: ./code/experimental/asmeta.evotest/evoAsmetaTG/dist
      
      - name: Update the release and upload the assert
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "EvoAsmetaTG Latest Release"
          files: ./code/experimental/asmeta.evotest/evoAsmetaTG/dist/evoasmetatg.zip
