on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

name: EvoAsmetaTG - Upload Release Asset

jobs:
  build:
    name: Upload EvoAsmetaTG Release Asset
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/experimental/asmeta.evotest/evoAsmetaTG
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install dependencies
        working-directory: .
        run: mvn --batch-mode install -DskipTests
     
      - name: Install asmetal2java
        working-directory: ./code/experimental/asmetal2java/asmetal2java_codegen
        run: mvn --batch-mode install -DskipTests
     
      - name: Install junit2avalla
        working-directory: ./code/experimental/asmeta.evotest/junit2avalla
        run: mvn --batch-mode install -DskipTests
          
      - name: Test and Build with Maven
        run: mvn --batch-mode verify
      
      - name: Update the release and upload the assert
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "EvoAsmetaTG Latest Release"
          files: ./code/experimental/asmeta.evotest/evoAsmetaTG/dist/evoasmetatg.zip
